# Generated by Django 2.1.8 on 2019-05-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmanager', '0002_auto_20190517_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
