# Generated by Django 2.1.8 on 2019-05-26 21:55

from django.db import migrations

def forward(apps, schema_editor):
    Convention = apps.get_model('cmanager.convention')
    cs = Convention.objects.all()
    for c in cs:
        if c.district == 'BHS' and c.season == 1:
            pre = "BHS {0}".format(str(c.year))
        else:
            pre = "{0} {1} {2}".format(
                c.district,
                c.get_season_display(),
                str(c.year),
            )
        name = c.name.replace(pre, '').strip()
        c.name = name
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cmanager', '0005_auto_20190526_1455'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
