# Generated by Django 2.1.8 on 2019-06-04 16:43

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('cmanager', '0009_auto_20190604_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-25, 'Manual'), (-20, 'Incomplete'), (-15, 'Imported'), (-10, 'Inactive'), (0, 'New'), (5, 'Built'), (10, 'Active')], default=0, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.'),
        ),
    ]
