# Generated by Django 2.1.8 on 2019-06-07 19:13

from django.db import migrations

def forward(apps, schema_editor):
    Old = apps.get_model('api.session')
    New = apps.get_model('smanager.session')

    items = Old.objects.values()
    for item in items:
        New.objects.create(**item)

    Old = apps.get_model('api.contest')
    New = apps.get_model('smanager.contest')

    items = Old.objects.values()
    for item in items:
        New.objects.create(**item)

    Old = apps.get_model('api.contestant')
    New = apps.get_model('smanager.contestant')

    items = Old.objects.values()
    for item in items:
        New.objects.create(**item)


    Old = apps.get_model('api.entry')
    New = apps.get_model('smanager.entry')

    items = Old.objects.values()
    for item in items:
        New.objects.create(**item)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_appearance_onstage'),
        ('smanager', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
