# Generated by Django 2.1.8 on 2019-06-08 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0002_auto_20190607_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='cmanager.Award'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The Winner of the Contest.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contests', to='bhs.Group'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='smanager.Session'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='smanager.Contest'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='smanager.Entry'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='bhs.Group'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='smanager.Session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='convention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cmanager.Convention'),
        ),
        migrations.AlterField(
            model_name='session',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeders', to='smanager.Session'),
        ),
    ]
