# Generated by Django 2.1.8 on 2019-06-08 05:30

import apps.smanager.fields
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0003_auto_20190607_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='drcj_report',
            field=models.FileField(blank=True, default='', storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=apps.smanager.fields.FileUploadPath()),
        ),
        migrations.AlterField(
            model_name='session',
            name='legacy_report',
            field=models.FileField(blank=True, default='', storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=apps.smanager.fields.FileUploadPath()),
        ),
    ]
