# Generated by Django 2.2.4 on 2019-09-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.CharField(blank=True, default='', help_text='\n            The name of the group.\n        ', max_length=255),
        ),
    ]
