# Generated by Django 2.2.5 on 2019-09-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20190904_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='seed',
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('group_id', 'session'), name='unique_entry'),
        ),
    ]
