# Generated by Django 2.2.5 on 2019-09-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20190905_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.TextField(blank=True, help_text='\n            Group description.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='entry',
            name='notes',
            field=models.TextField(blank=True, help_text='\n            Specific notes and/or requests.'),
        ),
    ]
