# Generated by Django 2.2.5 on 2019-09-05 20:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20190905_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='awards',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='entry',
            name='charts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='Repertory',
        ),
    ]
