# Generated by Django 2.2.5 on 2019-09-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20190905_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='is_mt',
            field=models.BooleanField(default=False, help_text='\n            Mic Tester.'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_senior',
            field=models.BooleanField(default=False, help_text='Qualifies as a Senior Group.  Must be set manually.'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='participants',
            field=models.CharField(blank=True, default='', help_text='The Members/Director(s).', max_length=255),
        ),
        migrations.AlterField(
            model_name='entry',
            name='representing',
            field=models.CharField(blank=True, default='', help_text='Representing (based on District)', max_length=255),
        ),
    ]
