# Generated by Django 2.2.5 on 2019-09-09 13:26

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20190906_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='representing',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='representing',
            new_name='area',
        ),
    ]
