# Generated by Django 2.2.5 on 2019-09-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20190909_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='area',
            field=models.CharField(blank=True, default='', help_text='\n            Free-form field (based on district)', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='area',
            field=models.CharField(blank=True, default='', help_text='Free-form field (based on district)', max_length=255),
        ),
    ]
