# Generated by Django 2.2.5 on 2019-09-10 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20190910_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='group_emails',
        ),
    ]
