# Generated by Django 2.2.5 on 2019-09-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_remove_session_group_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='image_id',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
