# Generated by Django 2.2.5 on 2019-09-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_assignment_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='image_id',
            field=models.CharField(default='missing_image', max_length=255, null=True),
        ),
    ]
