# Generated by Django 2.2.5 on 2019-09-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20190912_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='kind',
            field=models.IntegerField(choices=[(10, 'Official'), (20, 'Practice')]),
        ),
    ]
