# Generated by Django 2.2.5 on 2019-09-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_auto_20190914_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
