# Generated by Django 2.2.5 on 2019-09-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_entry_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True, help_text='\n            The Public Description.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, help_text='\n            Private Notes (for internal use only).'),
        ),
    ]
