# Generated by Django 2.2.20 on 2021-07-02 18:04

import apps.registration.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0008_auto_20210702_1049'),
        ('registration', '0021_auto_20200310_1234'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entry',
            name='unique_entry',
        ),
        migrations.RemoveField(
            model_name='session',
            name='convention_id',
        ),
        migrations.AddField(
            model_name='session',
            name='convention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bhs.Convention'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='district',
            field=models.CharField(blank=True, choices=[('BHS', [(200, 'CAR'), (205, 'CSD'), (210, 'DIX'), (215, 'EVG'), (220, 'FWD'), (225, 'ILL'), (230, 'JAD'), (235, 'LOL'), (240, 'MAD'), (345, 'NED'), (350, 'NSC'), (355, 'ONT'), (360, 'PIO'), (365, 'RMD'), (370, 'SLD'), (375, 'SUN'), (380, 'SWD')]), ('Associated', [(410, 'NxtGn'), (420, 'MBHA'), (430, 'HI'), (440, 'SAI')]), ('Affiliated', [(510, 'BABS'), (515, 'BHA'), (520, 'BHNZ'), (525, 'BinG'), (530, 'FABS'), (540, 'HHar'), (550, 'IABS'), (560, 'LABBS'), (565, 'SABS'), (570, 'SNOBS'), (575, 'SPATS')])], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='district',
            field=models.CharField(blank=True, choices=[(110, 'BHS'), (200, 'CAR'), (205, 'CSD'), (210, 'DIX'), (215, 'EVG'), (220, 'FWD'), (225, 'ILL'), (230, 'JAD'), (235, 'LOL'), (240, 'MAD'), (345, 'NED'), (350, 'NSC'), (355, 'ONT'), (360, 'PIO'), (365, 'RMD'), (370, 'SLD'), (375, 'SUN'), (380, 'SWD')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='is_novice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contest',
            name='is_single',
            field=models.BooleanField(default=True, help_text='Single-round award'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='district',
            field=models.CharField(blank=True, choices=[('BHS', [(200, 'CAR'), (205, 'CSD'), (210, 'DIX'), (215, 'EVG'), (220, 'FWD'), (225, 'ILL'), (230, 'JAD'), (235, 'LOL'), (240, 'MAD'), (345, 'NED'), (350, 'NSC'), (355, 'ONT'), (360, 'PIO'), (365, 'RMD'), (370, 'SLD'), (375, 'SUN'), (380, 'SWD')]), ('Associated', [(410, 'NxtGn'), (420, 'MBHA'), (430, 'HI'), (440, 'SAI')]), ('Affiliated', [(510, 'BABS'), (515, 'BHA'), (520, 'BHNZ'), (525, 'BinG'), (530, 'FABS'), (540, 'HHar'), (550, 'IABS'), (560, 'LABBS'), (565, 'SABS'), (570, 'SNOBS'), (575, 'SPATS')])], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='district',
            field=models.CharField(blank=True, choices=[(110, 'BHS'), (200, 'CAR'), (205, 'CSD'), (210, 'DIX'), (215, 'EVG'), (220, 'FWD'), (225, 'ILL'), (230, 'JAD'), (235, 'LOL'), (240, 'MAD'), (345, 'NED'), (350, 'NSC'), (355, 'ONT'), (360, 'PIO'), (365, 'RMD'), (370, 'SLD'), (375, 'SUN'), (380, 'SWD')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='num_rounds',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='session',
            name='owners',
            field=models.ManyToManyField(default=apps.registration.models.Session.get_default_owners, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='year',
            field=models.IntegerField(blank=True, choices=[(2031, 2031), (2030, 2030), (2029, 2029), (2028, 2028), (2027, 2027), (2026, 2026), (2025, 2025), (2024, 2024), (2023, 2023), (2022, 2022), (2021, 2021), (2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970), (1969, 1969), (1968, 1968), (1967, 1967), (1966, 1966), (1965, 1965), (1964, 1964), (1963, 1963), (1962, 1962), (1961, 1961), (1960, 1960), (1959, 1959), (1958, 1958), (1957, 1957), (1956, 1956), (1955, 1955), (1954, 1954), (1953, 1953), (1952, 1952), (1951, 1951), (1950, 1950), (1949, 1949), (1948, 1948), (1947, 1947), (1946, 1946), (1945, 1945), (1944, 1944), (1943, 1943), (1942, 1942), (1941, 1941), (1940, 1940), (1939, 1939)], null=True),
        ),
    ]
