# Generated by Django 2.2.20 on 2021-09-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_auto_20210702_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='kind',
            field=models.IntegerField(choices=[(10, 'Official'), (20, 'Practice'), (30, 'Former')]),
        ),
    ]
