# Generated by Django 2.2.27 on 2022-03-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_auto_20220225_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='notification_list',
            field=models.TextField(blank=True, help_text='\n            Comma separated list of email addresses to notify with reports.'),
        ),
        migrations.AddField(
            model_name='session',
            name='notification_list',
            field=models.TextField(blank=True, help_text='\n            Comma separated list of email addresses to notify with reports.'),
        ),
    ]
