# Generated by Django 2.2.27 on 2022-08-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0028_auto_20220530_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='category',
            field=models.IntegerField(blank=True, choices=[(5, 'DRCJ'), (9, 'PC'), (10, 'ADM'), (30, 'Music'), (40, 'Performance'), (50, 'Singing')], null=True),
        ),
    ]
