# Generated by Django 2.2.27 on 2022-09-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0029_auto_20220814_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='tree_sort',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
