# Generated by Django 2.2.27 on 2023-08-20 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20230820_0530'),
        ('registration', '0032_auto_20230819_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.Organization'),
        ),
    ]
