# Generated by Django 2.2.27 on 2023-08-27 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0033_session_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='session',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='registration.Session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='owners',
            field=models.ManyToManyField(related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
