# Generated by Django 2.2.3 on 2019-07-22 17:15

import apps.bhs.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('first_name', apps.bhs.fields.NoPunctuationCharField(editable=False, max_length=255)),
                ('middle_name', apps.bhs.fields.NoPunctuationCharField(db_column='middle_initial', editable=False, max_length=255)),
                ('last_name', apps.bhs.fields.NoPunctuationCharField(editable=False, max_length=255)),
                ('nick_name', apps.bhs.fields.NoPunctuationCharField(db_column='preferred_name', editable=False, max_length=255)),
                ('email', apps.bhs.fields.LowerEmailField(db_column='username', editable=False, max_length=254, null=True)),
                ('birth_date', apps.bhs.fields.ReasonableBirthDate(db_column='birthday', editable=False, null=True)),
                ('home_phone', apps.bhs.fields.ValidatedPhoneField(db_column='phone', editable=False, max_length=255)),
                ('cell_phone', apps.bhs.fields.ValidatedPhoneField(editable=False, max_length=255)),
                ('work_phone', apps.bhs.fields.ValidatedPhoneField(editable=False, max_length=255)),
                ('bhs_id', models.IntegerField(db_column='legacy_id', editable=False, null=True, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], db_column='sex', editable=False, max_length=255)),
                ('part', apps.bhs.fields.VoicePartField(choices=[('tenor', 'Tenor'), ('lead', 'Lead'), ('baritone', 'Baritone'), ('bass', 'Bass')], db_column='primary_voice_part', editable=False, max_length=255)),
                ('mon', models.IntegerField(db_column='trusted_mon', editable=False)),
                ('is_deceased', models.BooleanField(editable=False)),
                ('is_honorary', models.BooleanField(db_column='honorary_member', editable=False)),
                ('is_suspended', models.BooleanField(editable=False)),
                ('is_expelled', models.BooleanField(editable=False)),
                ('merged_id', models.CharField(db_column='merged_into', editable=False, max_length=255, null=True)),
                ('deleted_id', models.CharField(db_column='deleted_by_id', editable=False, max_length=255, null=True)),
                ('created', models.DateTimeField(db_column='created', editable=False, null=True)),
                ('modified', models.DateTimeField(db_column='updated', editable=False, null=True)),
            ],
            options={
                'db_table': 'vwMembers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('status', models.BooleanField(editable=False)),
                ('paid', models.BooleanField(editable=False)),
                ('part', apps.bhs.fields.VoicePartField(choices=[('tenor', 'Tenor'), ('lead', 'Lead'), ('baritone', 'Baritone'), ('bass', 'Bass')], db_column='vocal_part', editable=False, max_length=255)),
                ('established_date', models.DateField(db_column='created', editable=False, null=True)),
                ('inactive_date', models.DateField(db_column='inactive', editable=False, null=True)),
                ('inactive_reason', models.CharField(db_column='inactive_reason', editable=False, max_length=255)),
                ('deleted', models.DateTimeField(db_column='deleted', editable=False, null=True)),
                ('created', models.DateTimeField(db_column='created_on', editable=False, null=True)),
                ('modified', models.DateTimeField(db_column='modified', editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Join',
                'verbose_name_plural': 'Joins',
                'db_table': 'vwSubscriptions_Memberships',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=255)),
                ('created', models.DateTimeField(db_column='created', editable=False)),
                ('modified', models.DateTimeField(db_column='modified', editable=False)),
                ('deleted_id', models.CharField(db_column='deleted_by_id', editable=False, max_length=255, null=True)),
            ],
            options={
                'db_table': 'vwMemberships',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=255)),
                ('abbv', models.CharField(editable=False, max_length=255)),
                ('officer_roles_id', models.CharField(editable=False, max_length=255)),
                ('start_date', models.DateField(editable=False, null=True)),
                ('end_date', models.DateField(editable=False, null=True)),
                ('created', models.DateTimeField(db_column='created', editable=False, null=True)),
                ('modified', models.DateTimeField(db_column='updated', editable=False, null=True)),
            ],
            options={
                'db_table': 'vwOfficers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'statuses',
                'db_table': 'vwStatuses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=255)),
                ('kind', models.CharField(choices=[('organization', 'Organization'), ('district', 'District'), ('group', 'Group'), ('chapter', 'Chapter'), ('chorus', 'Chorus'), ('quartet', 'Quartet')], db_column='object_type', editable=False, max_length=255)),
                ('gender', models.CharField(choices=[('men', 'Male'), ('women', 'Female'), ('mixed', 'Mixed')], db_column='category', editable=False, max_length=255)),
                ('division', models.CharField(choices=[('EVG', [('EVG Division I', 'EVG Division I'), ('EVG Division II', 'EVG Division II'), ('EVG Division III', 'EVG Division III'), ('EVG Division IV', 'EVG Division IV'), ('EVG Division V', 'EVG Division V')]), ('FWD', [('FWD Arizona', 'FWD Arizona'), ('FWD Northeast', 'FWD Northeast'), ('FWD Northwest', 'FWD Northwest'), ('FWD Southeast', 'FWD Southeast'), ('FWD Southwest', 'FWD Southwest')]), ('LOL', [('LOL 10000 Lakes', 'LOL 10000 Lakes'), ('LOL Division One', 'LOL Division One'), ('LOL Northern Plains', 'LOL Northern Plains'), ('LOL Packerland', 'LOL Packerland'), ('LOL Southwest', 'LOL Southwest')]), ('MAD', [('MAD Central', 'MAD Central'), ('MAD Northern', 'MAD Northern'), ('MAD Southern', 'MAD Southern')]), ('NED', [('NED Granite and Pine', 'NED Granite and Pine'), ('NED Mountain', 'NED Mountain'), ('NED Patriot', 'NED Patriot'), ('NED Sunrise', 'NED Sunrise'), ('NED Yankee', 'NED Yankee')]), ('SWD', [('SWD Northeast', 'SWD Northeast'), ('SWD Northwest', 'SWD Northwest'), ('SWD Southeast', 'SWD Southeast'), ('SWD Southwest', 'SWD Southwest')])], db_column='division', editable=False, max_length=255, null=True)),
                ('bhs_id', models.IntegerField(db_column='legacy_id', editable=False, null=True, unique=True)),
                ('chapter_code', models.CharField(db_column='legacy_code', editable=False, max_length=255)),
                ('website', models.CharField(editable=False, max_length=255)),
                ('email', models.CharField(editable=False, max_length=255)),
                ('chorus_name', models.CharField(editable=False, max_length=255)),
                ('phone', models.CharField(editable=False, max_length=255)),
                ('fax', models.CharField(editable=False, max_length=255)),
                ('facebook', models.CharField(editable=False, max_length=255)),
                ('twitter', models.CharField(editable=False, max_length=255)),
                ('youtube', models.CharField(editable=False, max_length=255)),
                ('pinterest', models.CharField(editable=False, max_length=255)),
                ('flickr', models.CharField(editable=False, max_length=255)),
                ('instagram', models.CharField(editable=False, max_length=255)),
                ('soundcloud', models.CharField(editable=False, max_length=255)),
                ('tin', models.CharField(editable=False, max_length=18)),
                ('preferred_name', models.CharField(editable=False, max_length=255)),
                ('first_alternate_name', models.CharField(editable=False, max_length=255)),
                ('second_alternate_name', models.CharField(editable=False, max_length=255)),
                ('visitor_information', models.TextField(editable=False)),
                ('established_date', models.DateField(editable=False)),
                ('chartered_date', models.DateField(editable=False)),
                ('licenced_date', models.DateField(editable=False)),
                ('deleted_id', models.CharField(db_column='deleted_by_id', editable=False, max_length=255, null=True)),
                ('created', models.DateTimeField(db_column='created', editable=False)),
                ('modified', models.DateTimeField(db_column='updated', editable=False)),
            ],
            options={
                'db_table': 'vwStructures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('current_through', models.DateField(db_column='valid_through', editable=False, null=True)),
                ('status', models.CharField(editable=False, max_length=255)),
                ('items_editable', models.BooleanField(editable=False)),
                ('deleted', models.DateTimeField(db_column='deleted', editable=False, null=True)),
                ('created', models.DateTimeField(db_column='created', editable=False, null=True)),
                ('modified', models.DateTimeField(db_column='updated', editable=False, null=True)),
            ],
            options={
                'db_table': 'vwSubscriptions',
                'managed': False,
            },
        ),
    ]
