# Generated by Django 2.2.4 on 2019-09-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='pos',
            field=models.IntegerField(blank=True, help_text='\n            The number of active performers.', null=True),
        ),
    ]
