# Generated by Django 2.2.5 on 2019-09-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0002_group_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='chapters',
            field=models.CharField(blank=True, editable=False, help_text='\n            The denormalized chapter group.', max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='participants',
            field=models.CharField(blank=True, default='', editable=False, help_text='Director(s) or Members (listed TLBB)', max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='pos',
            field=models.IntegerField(blank=True, editable=False, help_text='\n            The number of active performers.', null=True),
        ),
    ]
