# Generated by Django 2.2.3 on 2019-07-30 03:57

from django.db import migrations

def forward(apps, schema_migration):
    Person = apps.get_model('bhs.person')
    ps = Person.objects.all()
    for p in ps:
        if p.nick_name:
            first = p.nick_name
        else:
            first = p.first_name
        p.name = "{0} {1}".format(first, p.last_name)
        p.save()



class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0003_person_name'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
