# Generated by Django 2.2.5 on 2019-09-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0003_auto_20190906_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='chapters',
        ),
        migrations.RemoveField(
            model_name='group',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='group',
            name='pos',
        ),
    ]
