# Generated by Django 2.2.3 on 2019-07-13 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bhs', '0004_auto_20190625_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='owners',
            field=models.ManyToManyField(related_name='groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
