# Generated by Django 2.2.3 on 2019-07-25 21:07

from django.db import migrations

def forward(apps, schema_migration):
    rep_map = {
        'BHS':110,
        'CAR':200,
        'CSD':205,
        'DIX':210,
        'EVG':215,
        'FWD':220,
        'ILL':225,
        'JAD':230,
        'LOL':235,
        'MAD':240,
        'NED':345,
        'NSC':350,
        'ONT':355,
        'PIO':360,
        'RMD':365,
        'SLD':370,
        'SUN':375,
        'SWD':380,
    }
    Award = apps.get_model('bhs.award')
    Group = apps.get_model('bhs.group')
    Person = apps.get_model('bhs.person')

    ws = Award.objects.exclude(
        district='',
    )
    for w in ws:
        rep = rep_map.get(w.district, None)
        w.representing = rep
        w.save()

    gs = Group.objects.exclude(
        district='',
    )
    for g in gs:
        rep = rep_map.get(g.district, None)
        g.representing = rep
        g.save()

    ps = Person.objects.exclude(
        district='',
    )
    for p in ps:
        rep = rep_map.get(p.district, None)
        p.representing = rep
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0004_auto_20190725_1407'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
