# Generated by Django 2.2.3 on 2019-07-30 04:44

import apps.bhs.fields
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0004_auto_20190729_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='mc_pk',
            new_name='source_id',
        ),
        migrations.RemoveField(
            model_name='award',
            name='district',
        ),
        migrations.RemoveField(
            model_name='award',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='composers',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='holders',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='lyricists',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='district',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_deceased',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_expelled',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_honorary',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_suspended',
        ),
        migrations.RemoveField(
            model_name='person',
            name='location',
        ),
        migrations.RemoveField(
            model_name='person',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='mon',
        ),
        migrations.RemoveField(
            model_name='person',
            name='nick_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='person',
            name='spouse',
        ),
        migrations.RemoveField(
            model_name='person',
            name='suffix',
        ),
        migrations.RemoveField(
            model_name='person',
            name='website',
        ),
        migrations.AddField(
            model_name='convention',
            name='district',
            field=models.CharField(blank=True, default='', help_text='\n            Private Notes (for internal use only).', max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='\n            The name of the resource.\n        ', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='airports',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=3), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='bhs_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='cell_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='\n            The cell phone number of the resource.  Include country code.', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=apps.bhs.fields.LowerEmailField(blank=True, help_text='\n            The contact email of the resource.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(help_text='\n            The first name of the person.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(10, 'Male'), (20, 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='home_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='\n            The home phone number of the resource.  Include country code.', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(help_text='\n            The last name of the person.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='\n            The common name of the person.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='persons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='part',
            field=models.IntegerField(blank=True, choices=[(1, 'Tenor'), (2, 'Lead'), (3, 'Baritone'), (4, 'Bass')], null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='\n            The work phone number of the resource.  Include country code.', max_length=128, region=None),
        ),
    ]
