# Generated by Django 2.2.3 on 2019-07-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0005_auto_20190725_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='office',
            field=models.IntegerField(choices=[(10, 'SCJC'), (20, 'DRCJ'), (30, 'CA'), (40, 'Judge'), (50, 'Manager'), (60, 'Librarian')]),
        ),
    ]
