# Generated by Django 2.2.3 on 2019-07-30 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0005_auto_20190729_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='representing',
            new_name='district',
        ),
    ]
