# Generated by Django 2.2.3 on 2019-07-13 19:15

from django.db import migrations

def forward(apps, schema_editor):
    Group = apps.get_model('bhs.group')
    User = apps.get_model('rest_framework_jwt.user')

    groups = Group.objects.filter(
        officers__isnull=False,
    )
    for group in groups:
        fs = group.officers.filter(
            status__gt=0,
        )
        for f in fs:
            person = f.person
            if not person.email:
                continue
            try:
                user = User.objects.get(
                    email=person.email,
                )
            except User.DoesNotExist:
                continue
            group.owners.add(user)

class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0005_group_owners'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
