# Generated by Django 2.2.5 on 2019-09-10 18:39

import apps.bhs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0006_auto_20190910_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(help_text='\n            The first name of the person.', max_length=255, validators=[apps.bhs.validators.validate_punctuation]),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(help_text='\n            The last name of the person.', max_length=255, validators=[apps.bhs.validators.validate_punctuation]),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='\n            The common name of the person.', max_length=255, validators=[apps.bhs.validators.validate_punctuation]),
        ),
    ]
