# Generated by Django 2.2.3 on 2019-07-30 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0006_auto_20190729_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='representing',
            new_name='district',
        ),
    ]
