# Generated by Django 2.2.3 on 2019-07-30 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0007_auto_20190729_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='representing',
            new_name='district',
        ),
    ]
