# Generated by Django 2.2.3 on 2019-07-19 14:41

from django.db import migrations

def forward(apps, schema_editor):
    Old = apps.get_model('cmanager.award')
    New = apps.get_model('bhs.award')

    olds = Old.objects.values()
    for old in olds:
        old.pop('parent_id')
        New.objects.create(**old)

class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0007_award'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
