# Generated by Django 2.2.3 on 2019-07-25 23:17

from django.db import migrations

def forward(apps, schema_editor):
    Officer = apps.get_model('bhs.officer')

    fs = Officer.objects.filter(
        office__in=[
            100,
            110,
            170,
        ]
    )
    fs.update(office=10)

    fs = Officer.objects.filter(
        office__in=[
            210,
            220,
        ]
    )
    fs.update(office=20)

    fs = Officer.objects.filter(
        office__in=[
            120,
            230,
            270,
        ]
    )
    fs.update(office=30)

    fs = Officer.objects.filter(
        office__in=[
            130,
            140,
            150,
            240,
            250,
            260,
            280,
            290,
            295,
        ]
    )
    fs.update(office=40)

    fs = Officer.objects.filter(
        office__in=[
            310,
            320,
            330,
            340,
            350,
            410,
        ]
    )
    fs.update(office=50)

    fs = Officer.objects.filter(
        office__in=[
            160,
        ]
    )
    fs.update(office=60)


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0007_auto_20190725_1617'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
