# Generated by Django 2.2.3 on 2019-07-27 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0008_auto_20190725_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
    ]
