# Generated by Django 2.2.3 on 2019-07-19 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0008_auto_20190719_0741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Human',
        ),
        migrations.DeleteModel(
            name='Join',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Structure',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
