# Generated by Django 2.2.3 on 2019-07-30 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0009_remove_convention_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convention',
            old_name='representing',
            new_name='district',
        ),
    ]
