# Generated by Django 2.2.3 on 2019-07-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0009_remove_person_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repertory',
        ),
    ]
