# Generated by Django 2.2.3 on 2019-07-30 05:07

from django.db import migrations

def forward(apps, schema_editor):
    Group = apps.get_model('bhs.group')
    gs = Group.objects.all()
    district_map = {
        'BHS': 110,
        'CAR': 200,
        'CSD': 205,
        'DIX': 210,
        'EVG': 215,
        'FWD': 220,
        'ILL': 225,
        'JAD': 230,
        'LOL': 235,
        'MAD': 240,
        'NED': 345,
        'NSC': 350,
        'ONT': 355,
        'PIO': 360,
        'RMD': 365,
        'SLD': 370,
        'SUN': 375,
        'SWD': 380,
    }
    for g in gs:
        district = district_map.get(g.code, None)
        g.district = district
        g.save()



class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0010_auto_20190729_2202'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
