# Generated by Django 2.2.3 on 2019-07-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0012_auto_20190729_2212'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='convention',
            name='unique_convention',
        ),
        migrations.RemoveField(
            model_name='group',
            name='parent',
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='The name of the quartet/chorus.', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='convention',
            constraint=models.UniqueConstraint(fields=('year', 'season', 'name', 'district'), name='unique_convention'),
        ),
    ]
