# Generated by Django 2.2.3 on 2019-07-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0012_auto_20190728_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name_plural': 'Groups'},
        ),
        migrations.RemoveField(
            model_name='convention',
            name='group_id',
        ),
        migrations.AlterUniqueTogether(
            name='chart',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='chart',
            constraint=models.UniqueConstraint(fields=('title', 'arrangers'), name='unique_chart'),
        ),
        migrations.AddConstraint(
            model_name='convention',
            constraint=models.UniqueConstraint(fields=('year', 'season', 'name', 'representing'), name='unique_convention'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('bhs_id', 'kind'), name='unique_group'),
        ),
    ]
