# Generated by Django 2.2.27 on 2022-08-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0012_auto_20220225_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='tree_sort',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
