# Generated by Django 2.2.3 on 2019-07-30 05:38

from django.db import migrations


def forward(apps, schema_editor):
    Group = apps.get_model('bhs.group')
    gs = Group.objects.filter(kind__in=[
        1,
        11,
        12,
        13,
        30,
    ])
    gs.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0013_auto_20190729_2237'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
