# Generated by Django 2.2.3 on 2019-07-28 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0013_auto_20190728_1443'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='member',
            name='group',
        ),
        migrations.RemoveField(
            model_name='member',
            name='person',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='group',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='person',
        ),
        migrations.DeleteModel(
            name='Human',
        ),
        migrations.DeleteModel(
            name='Join',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Structure',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Officer',
        ),
    ]
