# Generated by Django 2.2.3 on 2019-07-29 00:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bhs', '0014_auto_20190728_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='owners',
            field=models.ManyToManyField(related_name='persons', to=settings.AUTH_USER_MODEL),
        ),
    ]
