# Generated by Django 2.2.3 on 2019-07-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0015_auto_20190729_2241'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='group',
            name='unique_group',
        ),
        migrations.RemoveField(
            model_name='group',
            name='email',
        ),
        migrations.RemoveField(
            model_name='group',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='group',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='group',
            name='fax_phone',
        ),
        migrations.RemoveField(
            model_name='group',
            name='flickr',
        ),
        migrations.RemoveField(
            model_name='group',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='group',
            name='is_divided',
        ),
        migrations.RemoveField(
            model_name='group',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='group',
            name='pinterest',
        ),
        migrations.RemoveField(
            model_name='group',
            name='soundcloud',
        ),
        migrations.RemoveField(
            model_name='group',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='group',
            name='tree_sort',
        ),
        migrations.RemoveField(
            model_name='group',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='group',
            name='visitor_information',
        ),
        migrations.RemoveField(
            model_name='group',
            name='youtube',
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(blank=True, help_text='\n            Legacy Short-form code (chapters only).', max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_senior',
            field=models.BooleanField(default=False, help_text='Qualifies as a Senior Group.  Must be set manually.'),
        ),
    ]
