# Generated by Django 2.2.27 on 2023-08-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0016_auto_20230225_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='district',
            field=models.IntegerField(choices=[(110, 'BHS'), (115, 'HI'), (200, 'CAR'), (205, 'CSD'), (210, 'DIX'), (215, 'EVG'), (220, 'FWD'), (225, 'ILL'), (230, 'JAD'), (235, 'LOL'), (240, 'MAD'), (345, 'NED'), (350, 'NSC'), (355, 'ONT'), (360, 'PIO'), (365, 'RMD'), (370, 'SLD'), (375, 'SUN'), (380, 'SWD')], null=True),
        ),
    ]
