# Generated by Django 2.2.3 on 2019-07-30 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0016_auto_20190729_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='mc_pk',
            new_name='source_id',
        ),
    ]
