# Generated by Django 2.2.3 on 2019-07-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0017_auto_20190729_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='persons',
            field=models.ManyToManyField(related_name='conventions', to='bhs.Person'),
        ),
    ]
