# Generated by Django 2.2.3 on 2019-07-30 17:36

from django.db import migrations

def forward(apps, schema_editor):
    Assignment = apps.get_model('smanager.assignment')
    Convention = apps.get_model('bhs.convention')
    Person = apps.get_model('bhs.person')

    ms = Assignment.objects.all()
    for m in ms:
        c = Convention.objects.get(id=m.session.convention_id)
        person = Person.objects.get(id=m.person_id)
        c.persons.add(person)

class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0018_convention_persons'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
