# Generated by Django 2.2.27 on 2023-08-26 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0019_auto_20230820_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='owners',
            field=models.ManyToManyField(related_name='conventions', to=settings.AUTH_USER_MODEL),
        ),
    ]
