# Generated by Django 2.2.3 on 2019-07-30 17:57

from django.db import migrations

def forward(apps, schema_editor):
    User = apps.get_model('rest_framework_jwt.user')
    Convention = apps.get_model('bhs.convention')
    us = User.objects.filter(
        email__in=[
            'dbinetti@gmail.com',
            'proclamation56@gmail.com',
            'buechler@alumni.princeton.edu',
        ]
    )
    cs = Convention.objects.all()
    for c in cs:
        for u in us:
            c.owners.add(u)



class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0019_auto_20190730_1036'),
        ('smanager', '0006_auto_20190730_0725'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
