# Generated by Django 2.2.3 on 2019-07-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0020_auto_20190730_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='charts',
            field=models.ManyToManyField(blank=True, related_name='groups', to='bhs.Chart'),
        ),
        migrations.AlterField(
            model_name='convention',
            name='persons',
            field=models.ManyToManyField(blank=True, related_name='conventions', to='bhs.Person'),
        ),
    ]
