# Generated by Django 2.2.4 on 2019-08-07 22:44

import apps.bhs.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0021_auto_20190730_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='composers',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='chart',
            name='description',
            field=models.TextField(blank=True, default='', help_text="\n            Fun or interesting facts to share about the chart (ie, 'from Disney's Lion King, first sung by Elton John'.)", max_length=1000),
        ),
        migrations.AddField(
            model_name='chart',
            name='holders',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.bhs.fields.ImageUploadPath('image')),
        ),
        migrations.AddField(
            model_name='chart',
            name='lyricists',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='chart',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='\n            Private Notes (for internal use only).'),
        ),
    ]
