# Generated by Django 2.2.4 on 2019-08-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0022_auto_20190807_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
