# Generated by Django 2.2.4 on 2019-08-08 19:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0023_auto_20190808_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='airports',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=3), blank=True, default=list, null=True, size=None),
        ),
    ]
