# Generated by Django 2.2.4 on 2019-08-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0024_auto_20190808_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
