# Generated by Django 2.2.4 on 2019-08-10 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0025_auto_20190808_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
