# Generated by Django 2.1.9 on 2019-06-30 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='award',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcomes', to='cmanager.Award'),
        ),
    ]
