# Generated by Django 2.1.8 on 2019-06-08 05:53

from django.db import migrations

def forward(apps, schema_editor):
    conversions = [
        ['api.round', 'rmanager.round'],
        ['api.outcome', 'rmanager.outcome'],
        ['api.contender', 'rmanager.contender'],
        ['api.panelist', 'rmanager.panelist'],
        ['api.appearance', 'rmanager.appearance'],
        ['api.song', 'rmanager.song'],
        ['api.score', 'rmanager.score'],
    ]

    for conversion in conversions:
        Old = apps.get_model(conversion[0])
        New = apps.get_model(conversion[1])

        items = Old.objects.values()
        for item in items:
            New.objects.create(**item)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20190607_2221'),
        ('rmanager', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
