# Generated by Django 2.2.3 on 2019-07-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='outcomes',
            field=models.ManyToManyField(blank=True, related_name='appearances', to='rmanager.Outcome'),
        ),
    ]
