# Generated by Django 2.2.3 on 2019-07-28 18:57

from django.db import migrations

def forward(apps, schema_editor):
    Appearance = apps.get_model('rmanager.appearance')
    ps = Appearance.objects.filter(
        contenders__isnull=False,
    )
    for p in ps:
        cs = p.contenders.all()
        for c in cs:
            p.outcomes.add(c.outcome)


class Migration(migrations.Migration):

    dependencies = [
        ('rmanager', '0002_appearance_outcomes'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
