# Generated by Django 2.2.3 on 2019-07-13 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rmanager', '0002_auto_20190630_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='owners',
            field=models.ManyToManyField(related_name='appearances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='round',
            name='owners',
            field=models.ManyToManyField(related_name='rounds', to=settings.AUTH_USER_MODEL),
        ),
    ]
