# Generated by Django 2.2.3 on 2019-07-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmanager', '0003_auto_20190713_0922'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appearance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='contender',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='outcome',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='panelist',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set(),
        ),
    ]
