# Generated by Django 2.2.3 on 2019-07-30 14:14

import apps.rmanager.fields
import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import phonenumber_field.modelfields
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rmanager', '0003_auto_20190728_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appearance',
            old_name='group_bhs_id',
            new_name='bhs_id',
        ),
        migrations.RenameField(
            model_name='appearance',
            old_name='group_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='appearance',
            old_name='group_division',
            new_name='division',
        ),
        migrations.RenameField(
            model_name='appearance',
            old_name='group_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='appearance',
            old_name='group_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='group_chapter',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='group_description',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='group_district',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='group_international',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='group_is_divided',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='group_is_senior',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='group_is_youth',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='group_kind',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='group_nomen',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='group_participants',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='group_status',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='group_tree_sort',
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='award_name',
        ),
        migrations.AddField(
            model_name='appearance',
            name='district',
            field=models.IntegerField(blank=True, choices=[(110, 'BHS'), (200, 'CAR'), (205, 'CSD'), (210, 'DIX'), (215, 'EVG'), (220, 'FWD'), (225, 'ILL'), (230, 'JAD'), (235, 'LOL'), (240, 'MAD'), (345, 'NED'), (350, 'NSC'), (355, 'ONT'), (360, 'PIO'), (365, 'RMD'), (370, 'SLD'), (375, 'SUN'), (380, 'SWD')], null=True),
        ),
        migrations.AddField(
            model_name='appearance',
            name='kind',
            field=models.IntegerField(blank=True, choices=[(32, 'Chorus'), (41, 'Quartet'), (46, 'VLQ')], help_text='\n            The kind of group.\n        ', null=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='age',
            field=models.IntegerField(blank=True, choices=[(10, 'Seniors'), (20, 'Novice'), (30, 'Youth')], null=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='description',
            field=models.TextField(blank=True, help_text='\n            The Public description of the award.', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='division',
            field=models.IntegerField(blank=True, choices=[(10, 'EVG Division I'), (20, 'EVG Division II'), (30, 'EVG Division III'), (40, 'EVG Division IV'), (50, 'EVG Division V'), (60, 'FWD Arizona'), (70, 'FWD Northeast'), (80, 'FWD Northwest'), (90, 'FWD Southeast'), (100, 'FWD Southwest'), (110, 'LOL 10000 Lakes'), (120, 'LOL Division One'), (130, 'LOL Northern Plains'), (140, 'LOL Packerland'), (150, 'LOL Southwest'), (170, 'MAD Central'), (180, 'MAD Northern'), (190, 'MAD Southern'), (210, 'NED Granite and Pine'), (220, 'NED Mountain'), (230, 'NED Patriot'), (240, 'NED Sunrise'), (250, 'NED Yankee'), (260, 'SWD Northeast'), (270, 'SWD Northwest'), (280, 'SWD Southeast'), (290, 'SWD Southwest')], null=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(10, 'Male'), (20, 'Female'), (30, 'Mixed')], help_text='\n            The gender to which the award is restricted.  If unselected, this award is open to all combinations.\n        ', null=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='is_novice',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='kind',
            field=models.IntegerField(blank=True, choices=[(32, 'Chorus'), (41, 'Quartet')], null=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='level',
            field=models.IntegerField(blank=True, choices=[(10, 'Championship'), (30, 'Qualifier'), (45, 'Representative'), (50, 'Deferred'), (60, 'Manual'), (70, 'Improved - Raw'), (80, 'Improved - Standard')], null=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='scope',
            field=models.IntegerField(blank=True, choices=[(100, 'Plateau 1'), (110, 'Plateau 2'), (120, 'Plateau 3'), (130, 'Plateau 4'), (140, 'Plateau A'), (150, 'Plateau AA'), (160, 'Plateau AAA'), (170, 'Plateau AAAA'), (175, 'Plateau AAAAA')], null=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='scope_range',
            field=django.contrib.postgres.fields.ranges.DecimalRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='season',
            field=models.IntegerField(blank=True, choices=[(1, 'Summer'), (2, 'Midwinter'), (3, 'Fall'), (4, 'Spring')], null=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='size',
            field=models.IntegerField(blank=True, choices=[(100, 'Plateau 1'), (110, 'Plateau 2'), (120, 'Plateau 3'), (130, 'Plateau 4'), (140, 'Plateau A'), (150, 'Plateau AA'), (160, 'Plateau AAA'), (170, 'Plateau AAAA'), (180, 'Plateau B'), (190, 'Plateau I'), (200, 'Plateau II'), (210, 'Plateau III'), (220, 'Plateau IV'), (230, 'Small')], null=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='size_range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='tree_sort',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='panelist',
            name='airports',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=3), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='panelist',
            name='bhs_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panelist',
            name='cell_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='\n            The cell phone number of the resource.  Include country code.', max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='panelist',
            name='district',
            field=models.IntegerField(blank=True, choices=[(110, 'BHS'), (200, 'CAR'), (205, 'CSD'), (210, 'DIX'), (215, 'EVG'), (220, 'FWD'), (225, 'ILL'), (230, 'JAD'), (235, 'LOL'), (240, 'MAD'), (345, 'NED'), (350, 'NSC'), (355, 'ONT'), (360, 'PIO'), (365, 'RMD'), (370, 'SLD'), (375, 'SUN'), (380, 'SWD')], null=True),
        ),
        migrations.AddField(
            model_name='panelist',
            name='email',
            field=apps.rmanager.fields.LowerEmailField(blank=True, help_text='\n            The contact email of the resource.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='panelist',
            name='first_name',
            field=models.CharField(blank=True, default='', help_text='\n            The first name of the person.', max_length=255),
        ),
        migrations.AddField(
            model_name='panelist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.rmanager.fields.UploadPath('image')),
        ),
        migrations.AddField(
            model_name='panelist',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text='\n            The last name of the person.', max_length=255),
        ),
        migrations.AddField(
            model_name='panelist',
            name='name',
            field=models.CharField(blank=True, default='', help_text='\n            The prefix of the person.', max_length=255),
        ),
        migrations.AddField(
            model_name='round',
            name='convention_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.rmanager.fields.UploadPath('image')),
        ),
        migrations.AddField(
            model_name='round',
            name='nomen',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='round',
            name='session_kind',
            field=models.IntegerField(blank=True, choices=[(32, 'Chorus'), (41, 'Quartet'), (42, 'Mixed'), (43, 'Senior'), (44, 'Youth'), (45, 'Unknown'), (46, 'VLQ')], help_text='\n            The kind of session.  Generally this will be either quartet or chorus.\n        ', null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, help_text='\n            The local timezone of the convention.', null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='arrangers',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='name',
            field=models.CharField(blank=True, help_text='Award Name.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='panelist',
            name='representing',
            field=models.CharField(blank=True, default='', help_text='\n            District', max_length=10),
        ),
    ]
