# Generated by Django 2.2.3 on 2019-07-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmanager', '0003_auto_20190728_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='award_name',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
