# Generated by Django 2.2.3 on 2019-07-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmanager', '0004_auto_20190713_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='group',
        ),
        migrations.RemoveField(
            model_name='panelist',
            name='person',
        ),
        migrations.RemoveField(
            model_name='song',
            name='chart',
        ),
        migrations.AddField(
            model_name='appearance',
            name='group_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panelist',
            name='person_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='chart_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
