# Generated by Django 2.2.3 on 2019-07-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmanager', '0004_auto_20190730_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='winner',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
