# Generated by Django 2.2.3 on 2019-07-13 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rmanager', '0005_auto_20190713_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panelists', to=settings.AUTH_USER_MODEL),
        ),
    ]
