# Generated by Django 2.2.3 on 2019-07-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmanager', '0005_auto_20190728_1210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contender',
        ),
    ]
