# Generated by Django 2.2.3 on 2019-07-13 18:29

from django.db import migrations

def forward(apps, schema_editor):
    Panelist = apps.get_model('rmanager.panelist')
    Person = apps.get_model('bhs.person')
    User = apps.get_model('rest_framework_jwt.user')
    ts = Panelist.objects.filter(
        person_id__isnull=False,
    )
    for t in ts:
        person = Person.objects.get(id=t.person_id)
        if not person.email:
            continue
        try:
            user = User.objects.get(
                email=person.email,
            )
        except User.DoesNotExist:
            continue
        t.user = user
        t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rmanager', '0006_panelist_user'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
