# Generated by Django 2.2.3 on 2019-07-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmanager', '0006_delete_contender'),
    ]

    database_operations = [
        migrations.AlterField(
            model_name='round',
            name='session',
            field=models.ForeignKey('smanager.session', db_constraint=False, db_index=True, null=False, on_delete=models.SET_NULL)
        ),
    ]
    state_operations = [
        migrations.AlterField(
            model_name='round',
            name='session',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='round',
            old_name='session',
            new_name='session_id'
        ),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        )
    ]



