# Generated by Django 2.2.3 on 2019-07-29 00:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rmanager', '0007_auto_20190728_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelist',
            name='user',
        ),
        migrations.AddField(
            model_name='panelist',
            name='owners',
            field=models.ManyToManyField(related_name='panelists', to=settings.AUTH_USER_MODEL),
        ),
    ]
