# Generated by Django 2.2.3 on 2019-07-13 19:05

from django.db import migrations

def forward(apps, schema_editor):
    Appearance = apps.get_model('rmanager.appearance')
    Group = apps.get_model('bhs.group')
    User = apps.get_model('rest_framework_jwt.user')

    ps = Appearance.objects.filter(
        group_id__isnull=False,
    )
    for p in ps:
        group = Group.objects.get(id=p.group_id)
        fs = group.officers.filter(
            status__gt=0,
        )
        for f in fs:
            person = f.person
            if not person.email:
                continue
            try:
                user = User.objects.get(
                    email=person.email,
                )
            except User.DoesNotExist:
                continue
            p.owners.add(user)

class Migration(migrations.Migration):

    dependencies = [
        ('rmanager', '0008_auto_20190713_1137'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
