# Generated by Django 2.2.3 on 2019-07-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmanager', '0009_auto_20190713_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appearance',
            options={'ordering': ['num']},
        ),
        migrations.AlterModelOptions(
            name='contender',
            options={},
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='legacy_group',
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='legacy_name',
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='legacy_num',
        ),
        migrations.RemoveField(
            model_name='panelist',
            name='legacy_person',
        ),
        migrations.RemoveField(
            model_name='song',
            name='legacy_chart',
        ),
    ]
