# Generated by Django 2.2.3 on 2019-07-16 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmanager', '0010_auto_20190715_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appearance',
            old_name='csa',
            new_name='csa_report',
        ),
    ]
