# Generated by Django 2.2.3 on 2019-07-16 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmanager', '0011_auto_20190715_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panelist',
            old_name='psa',
            new_name='psa_report',
        ),
    ]
