# Generated by Django 2.2.3 on 2019-07-16 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmanager', '0012_auto_20190715_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='oss',
            new_name='oss_report',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='sa',
            new_name='sa_report',
        ),
    ]
