# Generated by Django 2.2.3 on 2019-07-16 01:56

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('rmanager', '0013_auto_20190715_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'New')], default=0, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.'),
        ),
    ]
