# Generated by Django 2.2.3 on 2019-07-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmanager', '0015_auto_20190716_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcome',
            name='award',
        ),
        migrations.AddField(
            model_name='outcome',
            name='award_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
