# Generated by Django 2.0.3 on 2018-03-15 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='level',
            field=models.IntegerField(choices=[(10, 'Championship'), (20, 'Award'), (30, 'Qualifier')]),
        ),
        migrations.AlterField(
            model_name='award',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='If a qualifier, this is the award qualifying for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.Award'),
        ),
        migrations.AlterField(
            model_name='award',
            name='season',
            field=models.IntegerField(choices=[(1, 'Summer'), (2, 'Midwinter'), (3, 'Fall'), (4, 'Spring'), (9, 'Video')]),
        ),
    ]
