# Generated by Django 2.0.3 on 2018-03-12 16:35

import api.models.chart
from django.db import migrations, models
def upload_to(instance, filename):
    return 'foo/{0}'.format(instance.id)




class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='variance_report',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='csa_report',
        ),
        migrations.RemoveField(
            model_name='round',
            name='ors_report',
        ),
        migrations.RemoveField(
            model_name='session',
            name='admins_report',
        ),
        migrations.RemoveField(
            model_name='session',
            name='bbscores_report',
        ),
        migrations.RemoveField(
            model_name='session',
            name='drcj_report',
        ),
        migrations.RemoveField(
            model_name='session',
            name='oss_report',
        ),
        migrations.RemoveField(
            model_name='session',
            name='sa_report',
        ),
        migrations.AlterField(
            model_name='chart',
            name='image',
            field=models.ImageField(blank=True, upload_to=upload_to),
        ),
    ]
