# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='kind',
            field=models.IntegerField(choices=[('International', [(1, 'International')]), ('District', [(11, 'District'), (12, 'Noncompetitive'), (13, 'Affiliate')]), ('Division', [(21, 'Division')]), ('Group', [(31, 'Quartet'), (32, 'Chorus'), (33, 'Very Large Quartet'), (34, 'Mixed Group')])], help_text='\n            The kind of entity.'),
        ),
    ]
