# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='directors',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
