# Generated by Django 2.1.8 on 2019-05-14 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stage', '0001_initial'),
        ('bhs', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='venue',
            field=models.ForeignKey(blank=True, help_text='\n            The venue for the convention.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions', to='stage.Venue'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='api.Contest'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='api.Entry'),
        ),
        migrations.AddField(
            model_name='contest',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='api.Award'),
        ),
        migrations.AddField(
            model_name='contest',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The Winner of the Contest.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contests', to='bhs.Group'),
        ),
        migrations.AddField(
            model_name='contest',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='api.Session'),
        ),
        migrations.AddField(
            model_name='contender',
            name='appearance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenders', to='api.Appearance'),
        ),
        migrations.AddField(
            model_name='contender',
            name='outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenders', to='api.Outcome'),
        ),
        migrations.AddField(
            model_name='award',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='bhs.Group'),
        ),
        migrations.AddField(
            model_name='award',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='If a qualifier, this is the award qualifying for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.Award'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='convention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.Convention'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='bhs.Person'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appearances', to='api.Entry'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='bhs.Group'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='api.Round'),
        ),
        migrations.AddField(
            model_name='user',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='bhs.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('appearance', 'num')},
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('convention', 'kind')},
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('song', 'panelist')},
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('session', 'kind')},
        ),
        migrations.AlterUniqueTogether(
            name='panelist',
            unique_together={('round', 'person', 'category'), ('round', 'num')},
        ),
        migrations.AlterUniqueTogether(
            name='outcome',
            unique_together={('round', 'award')},
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('group', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='convention',
            unique_together={('year', 'season', 'name', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='contestant',
            unique_together={('entry', 'contest')},
        ),
        migrations.AlterUniqueTogether(
            name='contest',
            unique_together={('session', 'award')},
        ),
        migrations.AlterUniqueTogether(
            name='contender',
            unique_together={('appearance', 'outcome')},
        ),
        migrations.AlterUniqueTogether(
            name='appearance',
            unique_together={('round', 'num')},
        ),
    ]
