# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 00:10
from __future__ import unicode_literals

import api.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomen', models.CharField(editable=False, max_length=255)),
                ('status', django_fsm.FSMIntegerField(choices=[(0, 'New')], default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('img', api.fields.CloudinaryRenameField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('mus_points', models.IntegerField(blank=True, null=True)),
                ('per_points', models.IntegerField(blank=True, null=True)),
                ('sng_points', models.IntegerField(blank=True, null=True)),
                ('tot_points', models.IntegerField(blank=True, null=True)),
                ('mus_score', models.FloatField(blank=True, null=True)),
                ('per_score', models.FloatField(blank=True, null=True)),
                ('sng_score', models.FloatField(blank=True, null=True)),
                ('tot_score', models.FloatField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='api.Group')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='api.Session')),
            ],
            options={
                'verbose_name_plural': 'competitors',
            },
        ),
        migrations.AddField(
            model_name='appearance',
            name='competitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='api.Competitor'),
        ),
        migrations.AlterUniqueTogether(
            name='competitor',
            unique_together=set([('group', 'session')]),
        ),
    ]
