# Generated by Django 2.0.2 on 2018-02-24 21:22

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('lows', django.db.models.manager.Manager()),
            ],
        ),
    ]
