# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171121_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='num_rounds',
            field=models.IntegerField(),
        ),
    ]
