# Generated by Django 2.0.3 on 2018-03-12 16:52

import api.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180312_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.fields.UploadPath()),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.fields.UploadPath()),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.fields.UploadPath()),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.fields.UploadPath()),
        ),
    ]
