# Generated by Django 2.1.8 on 2019-05-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190514_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelist',
            name='representing',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
