# Generated by Django 2.1.5 on 2019-02-06 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190205_2216'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='panelist',
            unique_together={('round', 'person'), ('round', 'num')},
        ),
    ]
