# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170510_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='api.Entity'),
        ),
    ]
