# Generated by Django 2.0.3 on 2018-03-17 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180314_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='nomen',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='nomen',
        ),
        migrations.RemoveField(
            model_name='award',
            name='nomen',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='nomen',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='nomen',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='nomen',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='nomen',
        ),
        migrations.RemoveField(
            model_name='convention',
            name='nomen',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='nomen',
        ),
        migrations.RemoveField(
            model_name='grantor',
            name='nomen',
        ),
        migrations.RemoveField(
            model_name='grid',
            name='nomen',
        ),
        migrations.RemoveField(
            model_name='group',
            name='nomen',
        ),
        migrations.RemoveField(
            model_name='office',
            name='nomen',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='nomen',
        ),
        migrations.RemoveField(
            model_name='panelist',
            name='nomen',
        ),
        migrations.RemoveField(
            model_name='person',
            name='nomen',
        ),
        migrations.RemoveField(
            model_name='repertory',
            name='nomen',
        ),
        migrations.RemoveField(
            model_name='round',
            name='nomen',
        ),
        migrations.RemoveField(
            model_name='score',
            name='nomen',
        ),
        migrations.RemoveField(
            model_name='session',
            name='nomen',
        ),
        migrations.RemoveField(
            model_name='song',
            name='nomen',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='nomen',
        ),
    ]
