# Generated by Django 2.1.4 on 2019-01-11 14:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190111_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='penalties',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(10, 'One'), (20, 'Two')]), blank=True, default=list, size=None),
        ),
    ]
