# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_entry_directors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='bhs_pk',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='bhs_pk',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='bhs_pk',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
