# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170515_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomen', models.CharField(editable=False, max_length=500)),
                ('status', django_fsm.FSMIntegerField(choices=[(0, 'New')], default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.Entry')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.Member')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set([('entry', 'member')]),
        ),
    ]
