# Generated by Django 2.1.8 on 2019-05-16 16:58

from django.db import migrations

def forward(apps, schema_editor):
    Panelist = apps.get_model('api.panelist')

    ps = Panelist.objects.filter(person__isnull=False)
    for p in ps:
        p.representing = p.person.district
        p.save()



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_panelist_representing'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
