# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171122_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='district',
        ),
        migrations.RemoveField(
            model_name='group',
            name='division',
        ),
        migrations.RemoveField(
            model_name='group',
            name='international',
        ),
    ]
