# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170822_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='kind',
            field=models.IntegerField(choices=[(32, 'Chorus'), (41, 'Quartet')]),
        ),
        migrations.AlterField(
            model_name='group',
            name='kind',
            field=models.IntegerField(choices=[(32, 'Chorus'), (41, 'Quartet')], help_text='\n            The kind of group.\n        '),
        ),
        migrations.AlterField(
            model_name='office',
            name='kind',
            field=models.IntegerField(blank=True, choices=[('International', [(1, 'International')]), ('District', [(11, 'District'), (12, 'Noncompetitive'), (13, 'Affiliate')]), ('Division', [(21, 'Division')]), ('Group', [(32, 'Chapter'), (41, 'Quartet')])], help_text='\n            The kind of office.', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='kind',
            field=models.IntegerField(choices=[(32, 'Chorus'), (41, 'Quartet')], help_text='\n            The kind of session.  Generally this will be either quartet or chorus.\n        '),
        ),
    ]
