# Generated by Django 2.0.3 on 2018-03-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180316_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['tree_sort'], 'verbose_name_plural': 'groups'},
        ),
        migrations.RemoveField(
            model_name='venue',
            name='location',
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(default='(TBD)', help_text='\n            The name of the resource.', max_length=255),
        ),
    ]
