# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170515_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'New'), (10, 'Submitted'), (20, 'Accepted'), (30, 'Declined'), (40, 'Dropped'), (50, 'Validated'), (52, 'Scratched'), (55, 'Disqualified'), (57, 'Started'), (60, 'Finished'), (90, 'Published')], default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, help_text='\n            The contact email of the resource.', max_length=254, null=True),
        ),
    ]
