# Generated by Django 2.0.2 on 2018-02-11 20:03

from django.db import migrations

import logging
log = logging.getLogger('importer')


def data_migration(apps, schema_editor):
    Convention = apps.get_model('api', 'Convention')
    Convention.objects.filter(status=2).update(status=10)
    Convention.objects.filter(is_archived=True).update(status=-10)
    return


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180224_2148'),
    ]

    operations = [
        migrations.RunPython(data_migration),
    ]
