# Generated by Django 2.0.3 on 2018-03-17 20:08

from django.db import migrations


def forward(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    map = {
        "SCJC Chair": 100,
        "SCJC Chair Past": 110,
        "SCJC CA": 120,
        "SCJC MUS": 130,
        "SCJC PER": 140,
        "SCJC SNG": 150,
        "SCJC Chart": 160,
        "SCJC Admin": 170,
        "DRCJ": 210,
        "DRCJ Assistant": 220,
        "JUDGE CA": 230,
        "JUDGE MUS": 240,
        "JUDGE PER": 250,
        "JUDGE SNG": 260,
        "CPRES": 310,
        "CSEC": 320,
        "CDIR": 320,
        "CASS": 340,
        "CMAN": 350,
        "QADM": 410,
    }

    Office = apps.get_model('api', 'Office')

    offices = Office.objects.all()
    for office in offices:
        office.code = map[office.code]
        office.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180317_0945'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
