# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171126_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='chapter',
            field=models.TextField(blank=True, help_text='\n            The denormalized chapter organization.', max_length=255),
        ),
        migrations.AddField(
            model_name='group',
            name='district',
            field=models.TextField(blank=True, help_text='\n            The denormalized district organization.', max_length=255),
        ),
        migrations.AddField(
            model_name='group',
            name='division',
            field=models.TextField(blank=True, help_text='\n            The denormalized division organization.', max_length=255),
        ),
        migrations.AddField(
            model_name='group',
            name='international',
            field=models.TextField(blank=True, help_text='\n            The denormalized international organization.', max_length=255),
        ),
    ]
