# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170824_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_bhs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='is_bhs',
            field=models.BooleanField(default=False),
        ),
    ]
