# Generated by Django 2.1.5 on 2019-02-07 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190207_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelist',
            name='legacy_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complete',
            name='panelist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Panelist'),
        ),
    ]
