# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170517_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='part',
            field=models.IntegerField(blank=True, choices=[(1, 'Tenor'), (2, 'Lead'), (3, 'Baritone'), (4, 'Bass'), (5, 'Director')], null=True),
        ),
    ]
