# Generated by Django 2.0.2 on 2018-02-11 20:03

from django.db import migrations

import logging
log = logging.getLogger('importer')


def data_migration(apps, schema_editor):
    Award = apps.get_model('api', 'Award')
    Group = apps.get_model('api', 'Group')
    Entry = apps.get_model('api', 'Entry')
    Competitor = apps.get_model('api', 'Competitor')
    awards = Award.objects.filter(
        group=None,
        name__startswith='MAD Atlantic',
    )
    for award in awards:
        group = Group.objects.get(
            name='MAD Atlantic',
            kind=21,
        )
        award.group = group
        award.save()

    awards = Award.objects.filter(
        group=None,
        name__startswith='MAD Western',
    )
    for award in awards:
        group = Group.objects.get(
            name='MAD Western',
            kind=21,
        )
        award.group = group
        award.save()

    competitors = Competitor.objects.filter(
        entry=None,
    )
    for competitor in competitors:
        entry = Entry.objects.get(
            session=competitor.session,
            group=competitor.group,
        )
        competitor.entry = entry
        competitor.save()
    return


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180224_2200'),
    ]

    operations = [
        migrations.RunPython(data_migration),
    ]
