# Generated by Django 2.1.8 on 2019-05-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190516_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_reviewed',
            field=models.BooleanField(default=False, help_text='Reviewed for history app'),
        ),
    ]
