# Generated by Django 2.1.5 on 2019-02-11 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190207_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='api.Group'),
        ),
    ]
