# Generated by Django 2.0.2 on 2018-02-25 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180225_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='api.Group'),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Entry'),
        ),
        migrations.AlterField(
            model_name='convention',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conventions', to='api.Group'),
        ),
        migrations.AlterField(
            model_name='grantor',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grantors', to='api.Group'),
        ),
    ]
