# Generated by Django 2.1.5 on 2019-02-11 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190210_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='api.Group'),
        ),
    ]
