# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171126_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(10, 'Male'), (20, 'Female'), (30, 'Mixed')], help_text='\n            The gender of session.\n        ', null=True),
        ),
    ]
