# Generated by Django 2.1.4 on 2019-01-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190120_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_youth',
            field=models.BooleanField(default=False, help_text='Qualifies as a Youth Group.  Must be set manually.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_senior',
            field=models.BooleanField(default=False, help_text='Qualifies as a Senior Group.  This can be set manually, but is denormlized nightly for quartets.'),
        ),
    ]
