# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170524_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='submission',
        ),
    ]
