# Generated by Django 2.1.8 on 2019-05-16 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190516_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelist',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panelists', to='bhs.Person'),
        ),
    ]
