# Generated by Django 2.1.5 on 2019-02-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190210_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='legacy_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
