# Generated by Django 2.0.3 on 2018-03-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180319_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='level',
            field=models.IntegerField(choices=[(10, 'Championship'), (30, 'Qualifier'), (40, 'Award')]),
        ),
    ]
