# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_person_dues_thru'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
