# Generated by Django 2.1.5 on 2019-02-11 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_outcome_legacy_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete',
            name='panelist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Panelist'),
        ),
        migrations.AlterUniqueTogether(
            name='complete',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='complete',
            name='convention',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='person',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='round',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='session',
        ),
    ]
