# Generated by Django 2.0.2 on 2018-02-25 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180225_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Entry'),
        ),
    ]
