# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_song_submission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='submission',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='repertory',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
