# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_award_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='round',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'New'), (20, 'Started'), (25, 'Reviewed'), (30, 'Finished')], default=0),
        ),
    ]
