# Generated by Django 2.0.3 on 2018-03-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180319_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='age',
            field=models.IntegerField(blank=True, choices=[(10, 'Seniors'), (30, 'Youth')], null=True),
        ),
    ]
