# Generated by Django 2.1.5 on 2019-01-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190128_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='legacy_venue',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
