# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 17:08
from __future__ import unicode_literals

import api.fields
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='admin_email_csv',
            field=models.FileField(blank=True, max_length=255, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=api.fields.PathAndRename(prefix='admin')),
        ),
    ]
