# Generated by Django 2.1.5 on 2019-01-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_convention_legacy_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='legacy_venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
