# Generated by Django 2.0.2 on 2018-02-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180225_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='level',
            field=models.IntegerField(blank=True, choices=[(10, 'Championship'), (20, 'Award'), (30, 'Qualifier')], null=True),
        ),
    ]
