# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171127_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='entry',
        ),
    ]
