# Generated by Django 2.0.3 on 2018-03-22 19:48

import api.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180320_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.fields.UploadPath()),
        ),
    ]
