# Generated by Django 2.1.5 on 2019-02-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_competitor_legacy_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='legacy_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
