# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_participant_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='arrangers',
            field=models.TextField(default='(Unknown Arrangers)'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='composers',
            field=models.TextField(default='(Unknown Composers)'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='holders',
            field=models.TextField(default='(Unknown Copyright Holders)'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='lyricists',
            field=models.TextField(default='(Unknown Lyricists)'),
        ),
    ]
