# Generated by Django 2.1.5 on 2019-02-04 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190129_1057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='officer',
            unique_together={('group', 'person', 'office')},
        ),
    ]
