# Generated by Django 2.0.3 on 2018-03-23 04:21

from django.db import migrations, models
import django.utils.timezone
import django_fsm
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_convention_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=0, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.')),
                ('kind', models.IntegerField(blank=True, choices=[('International', [(1, 'International')]), ('District', [(11, 'District'), (12, 'Noncompetitive'), (13, 'Affiliate')]), ('Division', [(21, 'Division')]), ('Group', [(32, 'Chapter'), (41, 'Quartet')])], help_text='\n            The kind of office.', null=True)),
                ('code', models.IntegerField(blank=True, choices=[(110, 'AS'), (120, 'L5'), (130, 'LF'), (140, 'LS'), (150, 'LY'), (160, 'R5'), (170, 'RG'), (180, 'S5'), (190, 'SL'), (200, 'SN'), (210, 'SNA'), (220, 'Y1'), (230, 'Y2'), (240, 'YA1'), (250, 'YA2')], help_text='\n            The subscription code.', null=True)),
                ('mc_pk', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
