# Generated by Django 2.1.5 on 2019-02-06 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190129_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='competitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='api.Competitor'),
        ),
    ]
