# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_appearance_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomen', models.CharField(editable=False, max_length=255)),
                ('status', django_fsm.FSMIntegerField(choices=[(0, 'New')], default=0)),
                ('num', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('photo', models.DateTimeField(blank=True, null=True)),
                ('arrive', models.DateTimeField(blank=True, null=True)),
                ('depart', models.DateTimeField(blank=True, null=True)),
                ('backstage', models.DateTimeField(blank=True, null=True)),
                ('onstage', models.DateTimeField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grids', to='api.Entry')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grids', to='api.Round')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='grid',
            unique_together=set([('round', 'entry')]),
        ),
    ]
