# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_session_admin_email_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='valid_through',
            field=models.DateField(blank=True, null=True),
        ),
    ]
