# Generated by Django 2.1.5 on 2019-02-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_song_legacy_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='legacy_group',
        ),
        migrations.AddField(
            model_name='appearance',
            name='legacy_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
