# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 05:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20171128_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='renditions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None),
        ),
    ]
