# Generated by Django 2.0.2 on 2018-02-27 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180226_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='img',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='img',
        ),
        migrations.RemoveField(
            model_name='group',
            name='img',
        ),
        migrations.RemoveField(
            model_name='person',
            name='img',
        ),
    ]
