# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_person_valid_through'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='admin_email_csv',
            new_name='admin_emails',
        ),
    ]
