# Generated by Django 2.0.2 on 2018-02-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180227_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='short_name',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='group',
            name='short_name',
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(blank=True, help_text='\n            Short-form code.', max_length=255),
        ),
    ]
