# Generated by Django 2.1.5 on 2019-02-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190211_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='legacy_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
