# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_office_is_drcj'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='is_rep',
            field=models.BooleanField(default=False),
        ),
    ]
