# Generated by Django 2.0.3 on 2018-03-23 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180322_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.Subscription'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='code',
            field=models.IntegerField(blank=True, choices=[(10, 'RG Regular'), (20, 'R5 Regular 50 Year'), (30, 'SN Senior'), (40, 'S5 Senior 50 Year'), (50, 'SL Senior Legacy'), (60, 'Y1 Youth Initial'), (70, 'Y2 Youth Subsequent'), (80, 'LF Lifetime Regular'), (90, 'L5 Lifetime 50 Year'), (100, 'LY Lifetime Youth'), (110, 'LS Lifetime Senior'), (120, 'AS Associate')], help_text='\n            The subscription code.', null=True),
        ),
    ]
