# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_grid_renditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='competitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='api.Competitor'),
        ),
    ]
