# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 22:25
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20171010_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=0),
        ),
    ]
