# Generated by Django 2.0.3 on 2018-03-23 04:22

from django.db import migrations


def forward(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    subs = {
        'RG Regular': 10,
        'R5 Regular 50 Year': 20,
        'SN Senior': 30,
        'S5 Senior 50 Year': 40,
        'SL Senior Legacy': 50,
        'Y1 Youth Initial': 60,
        'Y2 Youth Subsequent': 70,
        'LF Lifetime Regular': 80,
        'L5 Lifetime 50 Year': 90,
        'LY Lifetime Youth': 100,
        'LS Lifetime Senior': 110,
        'AS Associate': 120,
    }

    Member = apps.get_model('api', 'Member')
    Subscription = apps.get_model('api.subscription')
    Member.objects.count()
    for m in members:
        try:
            s = Subscription.objects.get(
                code=subs.get(m.mem_code)
            )
        except Subscription.DoesNotExist:
            continue
        m.subscription = s
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180322_2144'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
