# Generated by Django 2.1.8 on 2019-05-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190517_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
