# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20171014_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='bhs_pk',
        ),
    ]
