# Generated by Django 2.1.5 on 2019-02-12 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_song_legacy_total'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appearance',
            unique_together={('round', 'num', 'competitor')},
        ),
    ]
