# Generated by Django 2.0.2 on 2018-02-28 18:22

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180228_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'New'), (2, 'Built'), (4, 'Opened'), (8, 'Closed'), (10, 'Verified'), (20, 'Started'), (30, 'Finished')], default=0, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.'),
        ),
    ]
