# Generated by Django 2.1.8 on 2019-05-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190517_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelist',
            name='legacy_row_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
