# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_office_is_ca'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='is_jc',
            field=models.BooleanField(default=False),
        ),
    ]
