# Generated by Django 2.0.3 on 2018-03-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180323_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='mem_status',
            field=models.IntegerField(blank=True, choices=[(10, 'Active'), (20, 'Active Internal'), (30, 'Active Licensed'), (40, 'Cancelled'), (50, 'Closed'), (60, 'Closed Merged'), (70, 'Closed Revoked'), (80, 'Closed Voluntary'), (90, 'Expelled'), (100, 'Expired'), (105, 'Expired Licensed'), (110, 'Lapsed'), (120, 'Not Approved'), (130, 'Pending'), (140, 'Pending Voluntary'), (150, 'Suspended'), (160, 'Suspended Membership'), (170, 'Awaiting Payment')], null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mem_status',
            field=models.IntegerField(blank=True, choices=[(10, 'Active'), (20, 'Active Internal'), (30, 'Active Licensed'), (40, 'Cancelled'), (50, 'Closed'), (60, 'Closed Merged'), (70, 'Closed Revoked'), (80, 'Closed Voluntary'), (90, 'Expelled'), (100, 'Expired'), (105, 'Expired Licensed'), (110, 'Lapsed'), (120, 'Not Approved'), (130, 'Pending'), (140, 'Pending Voluntary'), (150, 'Suspended'), (160, 'Suspended Membership'), (170, 'Awaiting Payment')], null=True),
        ),
    ]
