# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 20:10
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_member_bhs_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Alum'), (0, 'New'), (5, 'Provisional'), (10, 'Active')], default=0),
        ),
    ]
