# Generated by Django 2.1.5 on 2019-02-12 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190211_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='competitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections', to='api.Competitor'),
        ),
    ]
