# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_grid_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='img',
        ),
        migrations.RemoveField(
            model_name='group',
            name='org_sort',
        ),
    ]
