# Generated by Django 2.1.8 on 2019-05-28 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190528_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appearances', to='bhs.Group'),
        ),
    ]
