# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_office_is_jc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='baritone',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='bass',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='tenor',
        ),
    ]
