# Generated by Django 2.1.5 on 2019-02-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_selection_competitor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appearance',
            unique_together={('round', 'competitor'), ('round', 'num')},
        ),
    ]
