# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20171024_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_current',
        ),
    ]
