# Generated by Django 2.0.3 on 2018-03-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180328_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='code',
            field=models.IntegerField(blank=True, choices=[('International', [(100, 'SCJC Chair'), (110, 'SCJC Chair Past'), (120, 'SCJC CA'), (130, 'SCJC MUS'), (140, 'SCJC PER'), (150, 'SCJC SNG'), (160, 'SCJC Chart'), (170, 'SCJC Admin')]), ('District', [(210, 'DRCJ'), (220, 'DRCJ Assistant'), (230, 'JUDGE CA'), (240, 'JUDGE MUS'), (250, 'JUDGE PER'), (260, 'JUDGE SNG'), (270, 'CANDIDATE CA'), (280, 'CANDIDATE MUS'), (290, 'CANDIDATE PER'), (295, 'CANDIDATE SNG')]), ('Group', [(310, 'CPRES'), (320, 'CSEC'), (320, 'CDIR'), (340, 'CASS'), (350, 'CMAN'), (410, 'QADM')])], help_text='\n            The short-form office code.', null=True),
        ),
    ]
