# Generated by Django 2.0.3 on 2018-03-07 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180305_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='variance_report',
        ),
    ]
