# Generated by Django 2.1.5 on 2019-02-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190213_1052'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selection',
            unique_together=set(),
        ),
    ]
