# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20170602_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='is_ml',
            field=models.BooleanField(default=False),
        ),
    ]
