# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20171130_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='kind',
            field=models.IntegerField(choices=[(10, 'Official'), (20, 'Practice'), (30, 'Observer')]),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (10, 'Active'), (10, 'Active'), (10, 'Active'), (10, 'Active'), (10, 'Active'), (10, 'Active'), (10, 'Active'), (10, 'Active')], default=0, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.'),
        ),
    ]
