# Generated by Django 2.0.3 on 2018-03-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_appearance_variance_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='current_through',
            field=models.DateField(blank=True, null=True),
        ),
    ]
