# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20171211_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'withdrawn'), (0, 'New'), (10, 'Confirmed')], default=0, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth0_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
