# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 17:14
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20171026_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'New'), (4, 'Opened'), (8, 'Closed'), (10, 'Verified'), (20, 'Started'), (30, 'Finished'), (95, 'Archived')], default=0),
        ),
    ]
