# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_office_is_ml'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panelist',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomen', models.CharField(editable=False, max_length=255)),
                ('status', models.IntegerField(choices=[(-10, 'Archived'), (0, 'New'), (10, 'Scheduled'), (20, 'Confirmed'), (25, 'Validated'), (30, 'Final')], default=0)),
                ('kind', models.IntegerField(choices=[(10, 'Official'), (20, 'Practice'), (30, 'Composite')])),
                ('category', models.IntegerField(blank=True, choices=[(5, 'DRCJ'), (10, 'CA'), (20, 'ACA'), (30, 'Music'), (40, 'Performance'), (50, 'Singing')], null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panelists', to='api.Person')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panelists', to='api.Round')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='panelist',
            unique_together=set([('round', 'person')]),
        ),
    ]
