# Generated by Django 2.1.5 on 2019-02-13 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190213_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='song',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Song'),
        ),
    ]
