# Generated by Django 2.1.5 on 2019-02-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190213_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='appearance',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='competitor',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='convention',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='group',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='round',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='session',
        ),
    ]
