# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20171211_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='representing',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
