# Generated by Django 2.0.3 on 2018-03-10 21:16

import api.models.appearance
import api.models.chart
import api.models.competitor
import api.models.group
import api.models.person
import api.models.round
import api.models.session
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180309_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='variance_report_new',
            field=models.FileField(blank=True, max_length=255, upload_to=api.models.appearance.upload_to_variance),
        ),
        migrations.AlterField(
            model_name='chart',
            name='image',
            field=models.FileField(blank=True, upload_to=api.models.chart.upload_to),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='csa_report_new',
            field=models.FileField(blank=True, max_length=255, upload_to=api.models.competitor.upload_to_csa),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='image',
            field=models.ImageField(blank=True, upload_to=api.models.competitor.upload_to),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, upload_to=api.models.group.upload_to),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, upload_to=api.models.person.upload_to),
        ),
        migrations.AlterField(
            model_name='round',
            name='ors_report_new',
            field=models.FileField(blank=True, max_length=255, upload_to=api.models.round.upload_to_ors),
        ),
        migrations.AlterField(
            model_name='session',
            name='admins_report_new',
            field=models.FileField(blank=True, max_length=255, upload_to=api.models.session.upload_to_admins),
        ),
        migrations.AlterField(
            model_name='session',
            name='bbscores_report_new',
            field=models.FileField(blank=True, max_length=255, upload_to=api.models.session.upload_to_bbscores),
        ),
        migrations.AlterField(
            model_name='session',
            name='drcj_report_new',
            field=models.FileField(blank=True, max_length=255, upload_to=api.models.session.upload_to_drcj),
        ),
        migrations.AlterField(
            model_name='session',
            name='oss_report_new',
            field=models.FileField(blank=True, max_length=255, upload_to=api.models.session.upload_to_oss),
        ),
        migrations.AlterField(
            model_name='session',
            name='sa_report_new',
            field=models.FileField(blank=True, max_length=255, upload_to=api.models.session.upload_to_sa),
        ),
    ]
