# Generated by Django 2.1.8 on 2019-05-30 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmanager', '0006_auto_20190526_1455'),
        ('api', '0019_remove_score_legacy_panelist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='outcome',
            unique_together={('round', 'num'), ('round', 'award')},
        ),
    ]
