# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20171026_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
