# Generated by Django 2.1.8 on 2019-05-29 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_outcome_is_primary'),
        ('api', '0019_remove_score_legacy_panelist'),
    ]

    operations = [
    ]
