# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20170608_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='panelist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='api.Panelist'),
        ),
    ]
