# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_entry_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
