# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 16:54
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_score_panelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'New'), (5, 'Invited'), (10, 'Submitted'), (20, 'Accepted'), (30, 'Rejected'), (40, 'Withdrew'), (50, 'Validated'), (52, 'Scratched'), (55, 'Disqualified'), (57, 'Started'), (60, 'Finished'), (90, 'Published')], default=0),
        ),
    ]
