# Generated by Django 2.1.5 on 2019-02-14 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190213_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete',
            name='panelist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Panelist'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='song',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Song'),
        ),
    ]
