# Generated by Django 2.0.3 on 2018-03-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180310_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='csa_report',
        ),
        migrations.RemoveField(
            model_name='round',
            name='ors_report',
        ),
        migrations.RemoveField(
            model_name='session',
            name='admins_report',
        ),
        migrations.RemoveField(
            model_name='session',
            name='bbscores_report',
        ),
        migrations.RemoveField(
            model_name='session',
            name='drcj_report',
        ),
        migrations.RemoveField(
            model_name='session',
            name='oss_report',
        ),
        migrations.RemoveField(
            model_name='session',
            name='sa_report',
        ),
    ]
