# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_entry_representing'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='competitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grids', to='api.Competitor'),
        ),
    ]
