# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_grid_competitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='competitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grids', to='api.Competitor'),
        ),
        migrations.AlterUniqueTogether(
            name='grid',
            unique_together=set([]),
        ),
    ]
