# Generated by Django 2.1.5 on 2019-02-14 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190213_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='panelist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.Panelist'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('song', 'panelist'), ('song', 'num')},
        ),
    ]
