# Generated by Django 2.0.3 on 2018-03-10 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20180310_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appearance',
            old_name='variance_report_new',
            new_name='variance_report',
        ),
        migrations.RenameField(
            model_name='competitor',
            old_name='csa_report_new',
            new_name='csa_report',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='ors_report_new',
            new_name='ors_report',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='admins_report_new',
            new_name='admins_report',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='bbscores_report_new',
            new_name='bbscores_report',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='drcj_report_new',
            new_name='drcj_report',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='oss_report_new',
            new_name='oss_report',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='sa_report_new',
            new_name='sa_report',
        ),
    ]
