# Generated by Django 2.1.5 on 2019-02-14 17:39

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190214_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, help_text='\n            The local timezone of the convention.', null=True),
        ),
        migrations.AlterField(
            model_name='convention',
            name='location',
            field=models.CharField(blank=True, help_text='\n            The location in the form "City, State".', max_length=255),
        ),
    ]
