# Generated by Django 2.0.5 on 2018-06-01 16:15

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20180531_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-20, 'Protected'), (-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=0, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.'),
        ),
    ]
