# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20171027_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, editable=False, help_text='\n            The contact email of the resource.', max_length=254, null=True, unique=True),
        ),
    ]
