# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 16:40
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20171028_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-40, 'Sentinel'), (-30, 'Expired'), (-20, 'Legacy'), (-10, 'Inactive'), (0, 'New'), (10, 'Active'), (20, 'Affiliate')], default=0),
        ),
    ]
