# Generated by Django 2.1.5 on 2019-02-14 19:10

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190214_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='location',
            field=models.CharField(help_text='\n            The location in the form "City, State".', max_length=255),
        ),
        migrations.AlterField(
            model_name='convention',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(help_text='\n            The local timezone of the convention.'),
        ),
    ]
