# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20170611_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='entity',
        ),
    ]
