# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_grid_entry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grid',
            unique_together=set([('round', 'competitor')]),
        ),
    ]
