# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20171213_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Entry'),
        ),
        migrations.AddField(
            model_name='grid',
            name='appearance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Grid'),
        ),
    ]
