# Generated by Django 2.0.5 on 2018-06-01 22:04

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20180601_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='email',
            field=api.fields.LowerEmailField(blank=True, help_text='\n            The contact email of the resource.', max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=api.fields.LowerEmailField(blank=True, help_text='\n            The contact email of the resource.', max_length=254, null=True, unique=True),
        ),
    ]
