# Generated by Django 2.1.5 on 2019-02-14 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20190214_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complete',
            old_name='category',
            new_name='category_raw',
        ),
    ]
