# Generated by Django 2.1.8 on 2019-06-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_session_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='onstage',
            field=models.DateTimeField(blank=True, help_text='\n            The actual appearance datetime.', null=True),
        ),
    ]
