# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20171028_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_valid',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='valid_through',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
