# Generated by Django 2.1.5 on 2019-02-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20190214_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete',
            name='category_kind',
            field=models.IntegerField(blank=True, choices=[(30, 'Music'), (40, 'Performance'), (50, 'Singing')], null=True),
        ),
    ]
