# Generated by Django 2.0.6 on 2018-06-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20180601_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='Unknown', help_text='\n            The first name of the person.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='Unknown', help_text='\n            The last name of the person.', max_length=255),
        ),
    ]
