# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20170613_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='arrangers',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chart',
            name='composers',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chart',
            name='holders',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='lyricists',
            field=models.CharField(max_length=255),
        ),
    ]
