# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20171028_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, help_text='\n            The name of the resource.', max_length=255),
        ),
    ]
