# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 18:01
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20170613_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repertory',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=0),
        ),
    ]
