# Generated by Django 2.1.7 on 2019-02-22 19:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_complete_category_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete',
            name='slips',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None), blank=True, null=True, size=None),
        ),
    ]
