# Generated by Django 2.1.8 on 2019-06-08 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_appearance_onstage'),
        ('smanager', '0003_auto_20190607_2221'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contest',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contest',
            name='award',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='group',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='session',
        ),
        migrations.AlterUniqueTogether(
            name='contestant',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='entry',
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='entry',
            name='group',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='session',
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='session',
            name='convention',
        ),
        migrations.RemoveField(
            model_name='session',
            name='target',
        ),
        migrations.AlterField(
            model_name='appearance',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appearances', to='smanager.Entry'),
        ),
        migrations.AlterField(
            model_name='round',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='smanager.Session'),
        ),
        migrations.DeleteModel(
            name='Contest',
        ),
        migrations.DeleteModel(
            name='Contestant',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
