# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_appearance_slot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='slot',
            name='round',
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
