# Generated by Django 2.1.8 on 2019-06-08 17:36

import apps.rmanager.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20190607_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='csa',
            field=models.FileField(blank=True, default='', upload_to=apps.rmanager.fields.FileUploadPath()),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appearances_oldapi', to='smanager.Entry'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appearances_oldapi', to='bhs.Group'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances_oldapi', to='api.Round'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='variance_report',
            field=models.FileField(blank=True, default='', upload_to=apps.rmanager.fields.FileUploadPath()),
        ),
        migrations.AlterField(
            model_name='contender',
            name='appearance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenders_oldapi', to='api.Appearance'),
        ),
        migrations.AlterField(
            model_name='contender',
            name='outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenders_oldapi', to='api.Outcome'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes_oldapi', to='cmanager.Award'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes_oldapi', to='api.Round'),
        ),
        migrations.AlterField(
            model_name='panelist',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panelists_oldapi', to='bhs.Person'),
        ),
        migrations.AlterField(
            model_name='panelist',
            name='psa',
            field=models.FileField(blank=True, default='', upload_to=apps.rmanager.fields.FileUploadPath()),
        ),
        migrations.AlterField(
            model_name='panelist',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panelists_oldapi', to='api.Round'),
        ),
        migrations.AlterField(
            model_name='round',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds_oldapi', to='smanager.Session'),
        ),
        migrations.AlterField(
            model_name='score',
            name='panelist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_oldapi', to='api.Panelist'),
        ),
        migrations.AlterField(
            model_name='score',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_oldapi', to='api.Song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='appearance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs_oldapi', to='api.Appearance'),
        ),
        migrations.AlterField(
            model_name='song',
            name='chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs_oldapi', to='bhs.Chart'),
        ),
    ]
