# Generated by Django 2.1.7 on 2019-02-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_complete_slips'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='legacy_event',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
