# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20171028_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='valid_through',
            new_name='current_through',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='valid_through',
            new_name='current_through',
        ),
    ]
