# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20171213_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='appearance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Appearance'),
        ),
    ]
