# Generated by Django 2.0.5 on 2018-06-08 18:13

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180607_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Finished'), (0, 'New'), (10, 'Started')], default=0, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.'),
        ),
    ]
