# Generated by Django 2.1.9 on 2019-06-18 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20190608_1036'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appearance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='group',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='round',
        ),
        migrations.AlterUniqueTogether(
            name='contender',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contender',
            name='appearance',
        ),
        migrations.RemoveField(
            model_name='contender',
            name='outcome',
        ),
        migrations.AlterUniqueTogether(
            name='outcome',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='award',
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='round',
        ),
        migrations.AlterUniqueTogether(
            name='panelist',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='panelist',
            name='person',
        ),
        migrations.RemoveField(
            model_name='panelist',
            name='round',
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='round',
            name='session',
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='score',
            name='panelist',
        ),
        migrations.RemoveField(
            model_name='score',
            name='song',
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='song',
            name='appearance',
        ),
        migrations.RemoveField(
            model_name='song',
            name='chart',
        ),
        migrations.DeleteModel(
            name='Appearance',
        ),
        migrations.DeleteModel(
            name='Contender',
        ),
        migrations.DeleteModel(
            name='Outcome',
        ),
        migrations.DeleteModel(
            name='Panelist',
        ),
        migrations.DeleteModel(
            name='Round',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
