# Generated by Django 2.1.7 on 2019-02-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_convention_legacy_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convention',
            name='legacy_event',
        ),
        migrations.AddField(
            model_name='convention',
            name='legacy_complete',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='convention',
            name='legacy_selection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
