# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20170614_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='person',
        ),
    ]
