# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20171103_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='is_valid',
            new_name='is_current',
        ),
    ]
