# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20171213_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, help_text='\n            The contact email of the resource.', max_length=254),
        ),
    ]
