# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 04:19
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20171103_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='current_through',
        ),
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Excluded'), (0, 'New'), (10, 'Included')], default=0),
        ),
    ]
