# Generated by Django 2.1.7 on 2019-02-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20190223_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='variance_report',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='csa',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='round',
            name='legacy_oss',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='round',
            name='legacy_sa',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='round',
            name='oss',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='round',
            name='sa',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='oss',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='sa',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
