# Generated by Django 2.0.6 on 2018-06-09 18:54

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20180609_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'New'), (2, 'Published'), (5, 'Verified'), (7, 'Built'), (10, 'Started'), (20, 'Finished'), (30, 'Confirmed'), (40, 'Flagged'), (50, 'Scratched'), (60, 'Cleared'), (90, 'Announced'), (95, 'Archived')], default=0, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.'),
        ),
    ]
