# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 14:16
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_score_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'New'), (2, 'Scheduled'), (4, 'Opened'), (8, 'Closed'), (10, 'Verified'), (20, 'Started'), (30, 'Finished'), (45, 'Published')], default=0),
        ),
    ]
