# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20171219_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='airport',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
