# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 20:52
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20171103_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Excluded'), (0, 'New'), (10, 'Included')], default=0),
        ),
    ]
