# Generated by Django 2.1.7 on 2019-02-25 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20190225_1145'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('song', 'panelist')},
        ),
    ]
