# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20170615_0716'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chart',
            unique_together=set([('title', 'arrangers')]),
        ),
    ]
