# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20170615_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='', help_text='\n            The name of the resource.', max_length=200),
        ),
    ]
