# Generated by Django 2.0.6 on 2018-06-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20180612_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='spots',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
