# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 21:08
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20180109_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='actives_report',
            field=cloudinary.models.CloudinaryField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
