# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20171104_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.Person'),
        ),
    ]
