# Generated by Django 2.1.7 on 2019-02-25 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20190225_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='category',
        ),
        migrations.RemoveField(
            model_name='score',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='score',
            name='num',
        ),
    ]
