# Generated by Django 2.0.6 on 2018-06-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_round_spots'),
        ('api', '0031_auto_20180612_0707'),
    ]

    operations = [
    ]
