# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_participant_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.Person'),
        ),
    ]
