# Generated by Django 2.1.7 on 2019-02-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20190225_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='old_oss',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
