# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 04:27
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_session_is_invitational'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'New'), (2, 'Scheduled'), (4, 'Opened'), (8, 'Closed'), (10, 'Verified'), (15, 'Prepared'), (20, 'Started'), (30, 'Finished'), (45, 'Published')], default=0),
        ),
    ]
