# Generated by Django 2.1.7 on 2019-02-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_session_old_oss'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='old_oss',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
