# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20171104_1829'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set([('entry', 'person')]),
        ),
    ]
