# Generated by Django 2.0.6 on 2018-06-16 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20180616_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='champ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Group'),
        ),
    ]
