# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20170617_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_mt',
            field=models.BooleanField(default=False, help_text='\n            Scheduled mic tester.'),
        ),
    ]
