# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20180118_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelist',
            name='kind',
            field=models.IntegerField(choices=[(10, 'Official'), (20, 'Practice'), (30, 'Observer')]),
        ),
    ]
