# Generated by Django 2.1.7 on 2019-02-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_round_old_oss'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='run_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
