# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20171104_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.Member'),
        ),
    ]
