# Generated by Django 2.0.6 on 2018-06-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_contest_champ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='champion',
        ),
    ]
