# Generated by Django 2.1.7 on 2019-03-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_appearance_run_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='kind',
            field=models.IntegerField(blank=True, choices=[('International', [(1, 'International')]), ('District', [(11, 'District'), (12, 'Noncompetitive'), (13, 'Affiliate')]), ('Chapter', [(30, 'Chapter')]), ('Group', [(32, 'Chorus'), (41, 'Quartet'), (46, 'VLQ')])], help_text='\n            The kind of office.', null=True),
        ),
    ]
