# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20171104_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='member',
        ),
    ]
