# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_appearance_variance_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_senior',
            field=models.BooleanField(default=False, help_text="Qualifies as a Senior Group.  This is set once, at creation.  If the group 'ages' into Senior status that needs to be edited manually here."),
        ),
    ]
