# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20170619_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='kind',
            field=models.IntegerField(choices=[('International', [(1, 'International')]), ('District', [(11, 'District'), (12, 'Noncompetitive'), (13, 'Affiliate')]), ('Division', [(21, 'Division')]), ('Group', [(32, 'Chorus'), (33, 'Very Large Quartet'), (34, 'Mixed Group'), (41, 'Quartet')])], help_text='\n            The kind of entity.'),
        ),
    ]
