# Generated by Django 2.1.7 on 2019-03-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20190301_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='district',
            field=models.CharField(blank=True, help_text='\n            District (used primarily for judges.)', max_length=10),
        ),
    ]
