# Generated by Django 2.0.6 on 2018-06-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20180616_1124'),
    ]

    operations = [
        migrations.RenameField('Contest', 'champion', 'group'),
    ]
