# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 23:54
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_group_is_senior'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='oss_report',
            field=cloudinary.models.CloudinaryField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
