# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-28 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_round_oss_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='is_ranked',
            field=models.BooleanField(default=False),
        ),
    ]
