# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 14:10
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_entity_org_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'New'), (5, 'Verified'), (10, 'Started'), (20, 'Finished'), (30, 'Entered'), (40, 'Flagged'), (50, 'Scratched'), (60, 'Cleared'), (90, 'Published')], default=0),
        ),
    ]
