# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20171106_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantor',
            name='convention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grantors', to='api.Convention'),
        ),
        migrations.AlterUniqueTogether(
            name='grantor',
            unique_together=set([('convention', 'organization')]),
        ),
    ]
