# Generated by Django 2.0.6 on 2018-06-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20180619_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='variance_report',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
