# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 23:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20171106_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantor',
            name='session',
        ),
    ]
