# Generated by Django 2.0.6 on 2018-06-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_appearance_variance_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
