# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-29 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20180128_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='oss_report',
            new_name='ors_report',
        ),
    ]
