# Generated by Django 2.1.7 on 2019-03-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20190304_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='contact_report',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='session',
            name='drcj_report',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='session',
            name='legacy_report',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
