# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20170621_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='age',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='is_novice',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='long_name',
        ),
        migrations.RemoveField(
            model_name='session',
            name='age',
        ),
        migrations.RemoveField(
            model_name='session',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='is_invitational',
        ),
        migrations.RemoveField(
            model_name='session',
            name='is_prelims',
        ),
        migrations.RemoveField(
            model_name='session',
            name='num_rounds',
        ),
        migrations.RemoveField(
            model_name='session',
            name='num_songs',
        ),
        migrations.RemoveField(
            model_name='session',
            name='panel_size',
        ),
        migrations.RemoveField(
            model_name='session',
            name='primary',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.TextField(blank=True, help_text='\n            A description of the entity.  Max 1000 characters.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='entity',
            name='kind',
            field=models.IntegerField(choices=[('International', [(1, 'International')]), ('District', [(11, 'District'), (12, 'Noncompetitive'), (13, 'Affiliate')]), ('Division', [(21, 'Division')]), ('Group', [(32, 'Chorus'), (33, 'Very Large Quartet'), (34, 'Mixed Group'), (41, 'Quartet')])], help_text='\n            The kind of entity.\n        '),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(help_text='\n            The name of the resource.\n        ', max_length=255),
        ),
        migrations.AlterField(
            model_name='entity',
            name='org_sort',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='kind',
            field=models.IntegerField(choices=[(32, 'Chorus'), (33, 'Very Large Quartet'), (34, 'Mixed Group'), (41, 'Quartet')], help_text='\n            The kind of session.  Generally this will be either quartet or chorus.\n        '),
        ),
    ]
