# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20171106_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='is_qualifier',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='kind',
        ),
    ]
