# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20170621_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='current',
        ),
        migrations.RemoveField(
            model_name='session',
            name='cursor',
        ),
    ]
