# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 22:45
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20180128_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='csa_report',
            field=cloudinary.models.CloudinaryField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
