# Generated by Django 2.1.7 on 2019-03-07 21:08

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20190307_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='contact_report',
            field=models.FileField(blank=True, max_length=255, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='drcj_report',
            field=models.FileField(blank=True, max_length=255, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='legacy_report',
            field=models.FileField(blank=True, max_length=255, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=''),
        ),
    ]
