# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20171107_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, help_text='\n            The name of the resource.', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, help_text='\n            The name of the resource.', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='nick_name',
            field=models.CharField(blank=True, help_text='\n            The name of the resource.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(help_text='\n            The name of the resource.', max_length=255),
        ),
    ]
