# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 23:35
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_competitor_csa_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='oss_report',
            field=cloudinary.models.CloudinaryField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='sa_report',
            field=cloudinary.models.CloudinaryField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
