# Generated by Django 2.0.6 on 2018-06-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20180624_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appearance',
            options={'ordering': ['round__kind', 'num']},
        ),
        migrations.AddField(
            model_name='appearance',
            name='app_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
