# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20170621_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='bhs_fee',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='is_learning',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='is_medley',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='published',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='tempo',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='voicing',
        ),
    ]
