# Generated by Django 2.1.7 on 2019-03-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20190311_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='level',
            field=models.IntegerField(choices=[(10, 'Championship'), (30, 'Qualifier'), (45, 'Representative'), (50, 'Deferred'), (60, 'Manual'), (70, 'Improved - Raw'), (80, 'Improved - Standard')]),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='num_rounds',
            field=models.IntegerField(help_text='Number of rounds to determine the championship'),
        ),
    ]
