# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20180129_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='is_multi',
            field=models.BooleanField(default=False, help_text='If the competitor is contesting a multi-round award.'),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='is_ranked',
            field=models.BooleanField(default=False, help_text='If the competitor will be ranked in OSS.'),
        ),
    ]
