# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20170621_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='bhs_status',
        ),
        migrations.RemoveField(
            model_name='person',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='person',
            name='mon',
        ),
        migrations.RemoveField(
            model_name='person',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, help_text='\n            A bio of the person.  Max 1000 characters.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='\n            The name of the person.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=0),
        ),
    ]
