# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20171109_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(help_text='\n            The first name of the person.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(help_text='\n            The last name of the person.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, help_text='\n            The middle name of the person.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='nick_name',
            field=models.CharField(blank=True, help_text='\n            The nickname of the person.', max_length=255),
        ),
    ]
