# Generated by Django 2.0.6 on 2018-06-25 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20180625_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appearance',
            old_name='app_points',
            new_name='all_points',
        ),
    ]
