# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20180130_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='draw',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
