# Generated by Django 2.1.7 on 2019-03-11 21:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20190311_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='contesting_migrate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, help_text='Award numbers contestanting', null=True, size=None),
        ),
    ]
