# Generated by Django 2.0.6 on 2018-06-26 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20180625_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='period',
            field=models.IntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], null=True),
        ),
        migrations.AlterField(
            model_name='grid',
            name='appearance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grids', to='api.Appearance'),
        ),
        migrations.AlterUniqueTogether(
            name='grid',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='grid',
            name='competitor',
        ),
    ]
