# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20171109_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, help_text='\n            The name of the person.', max_length=255, null=True),
        ),
    ]
