# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20171109_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
    ]
