# Generated by Django 2.0.6 on 2018-06-26 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20180626_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grids', to='api.Venue'),
        ),
        migrations.AlterField(
            model_name='grid',
            name='appearance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Appearance'),
        ),
    ]
