# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20170621_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='round',
            name='num_songs',
        ),
        migrations.RemoveField(
            model_name='round',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='award',
            name='kind',
            field=models.IntegerField(choices=[(32, 'Chorus'), (33, 'Very Large Quartet'), (34, 'Mixed Group'), (41, 'Quartet')]),
        ),
    ]
