# Generated by Django 2.0.1 on 2018-01-31 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_competitor_draw'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'get_latest_by': ['num']},
        ),
    ]
