# Generated by Django 2.1.7 on 2019-03-11 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_competitor_contesting_migrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='contesting',
        ),
    ]
