# Generated by Django 2.1.7 on 2019-03-11 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_remove_competitor_contesting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitor',
            old_name='contesting_migrate',
            new_name='contesting',
        ),
    ]
