# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_remove_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bhs_pk',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='code',
            field=models.IntegerField(blank=True, choices=[(10, 'RG Regular'), (20, 'R5 Regular 50 Year'), (30, 'SN Senior'), (40, 'S5 Senior 50 Year'), (50, 'SL Senior Legacy'), (60, 'Y1 Youth Initial'), (70, 'Y2 Youth Subsequent'), (80, 'LF Lifetime Regular'), (90, 'L5 Lifetime 50 Year'), (100, 'LY Lifetime Youth'), (110, 'LS Lifetime Senior'), (120, 'AS Associate')], null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='mem_status',
            field=models.IntegerField(blank=True, choices=[(10, 'Active'), (20, 'Active Internal'), (30, 'Active Licensed'), (40, 'Cancelled'), (50, 'Closed'), (60, 'Closed Merged'), (70, 'Closed Revoked'), (80, 'Closed Voluntary'), (90, 'Expelled'), (100, 'Expired'), (110, 'Lapsed'), (120, 'Not Approved'), (130, 'Pending'), (140, 'Pending Voluntary'), (150, 'Suspended'), (160, 'Suspended Membership')], null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='sub_status',
            field=models.IntegerField(blank=True, choices=[(10, 'Active'), (20, 'Expired'), (30, 'Pending'), (40, 'Lapsed'), (50, 'Cancelled'), (60, 'Swapped')], null=True),
        ),
    ]
