# Generated by Django 2.0.6 on 2018-06-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20180626_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grid',
            name='onstage',
            field=models.DateTimeField(blank=True, help_text='\n            The scheduled stage time in the Local time of the Venue.', null=True),
        ),
    ]
