# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20170621_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='num_rounds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
