# Generated by Django 2.0.2 on 2018-02-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20180131_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='bhs_pk',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
