# Generated by Django 2.1.7 on 2019-03-11 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20190311_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='contesting',
        ),
    ]
