# Generated by Django 2.0.6 on 2018-06-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20180627_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestant',
            options={'ordering': ('contest__num',)},
        ),
        migrations.AddField(
            model_name='competitor',
            name='mos',
            field=models.IntegerField(blank=True, help_text='Actual Participants-on-Stage', null=True),
        ),
    ]
