# Generated by Django 2.0.2 on 2018-02-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_officer_bhs_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='description',
            field=models.TextField(blank=True, help_text='\n            Public Notes (usually from competitor).', max_length=1000),
        ),
        migrations.AddField(
            model_name='entry',
            name='notes',
            field=models.TextField(blank=True, help_text='\n            Private Notes (for internal use only).'),
        ),
    ]
