# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_office_long_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='part',
            field=models.IntegerField(blank=True, choices=[(-1, 'Director'), (1, 'Tenor'), (2, 'Lead'), (3, 'Baritone'), (4, 'Bass')], null=True),
        ),
    ]
