# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20170621_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convention',
            name='risers',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='bhs_id',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='codirector',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='director',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='men',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='risers',
        ),
        migrations.AlterField(
            model_name='member',
            name='part',
            field=models.IntegerField(blank=True, choices=[(-1, 'Director'), (1, 'Tenor'), (2, 'Lead'), (3, 'Baritone'), (4, 'Bass')], null=True),
        ),
    ]
