# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 05:12
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20171109_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-20, 'Barred'), (-10, 'Inactive'), (-5, 'AIC'), (0, 'New'), (2, 'Exempt'), (5, 'Pending'), (10, 'Active')], default=0),
        ),
    ]
