# Generated by Django 2.0.6 on 2018-06-29 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20180628_0728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appearance',
            options={'ordering': ['-round__num', 'num']},
        ),
    ]
