# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20170622_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appearance',
            old_name='prs_points',
            new_name='per_points',
        ),
        migrations.RenameField(
            model_name='appearance',
            old_name='prs_score',
            new_name='per_score',
        ),
        migrations.RenameField(
            model_name='contestant',
            old_name='prs_points',
            new_name='per_points',
        ),
        migrations.RenameField(
            model_name='contestant',
            old_name='prs_score',
            new_name='per_score',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='prs_points',
            new_name='per_points',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='prs_score',
            new_name='per_score',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='prs_points',
            new_name='per_points',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='prs_score',
            new_name='per_score',
        ),
    ]
