# Generated by Django 2.0.2 on 2018-02-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_entry_mos'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='inactive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='inactive_reason',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
