# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 20:19
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20171109_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='is_bhs',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_bhs',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_current',
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-20, 'Legacy'), (-10, 'Inactive'), (0, 'New'), (10, 'Active'), (20, 'Exempt')], default=0),
        ),
    ]
