# Generated by Django 2.0.7 on 2018-07-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20180628_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='oss_report',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='session',
            name='sa_report',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
