# Generated by Django 2.1.7 on 2019-03-18 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20190314_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='award',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='api.Award'),
        ),
    ]
