# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20170622_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='kind',
            field=models.IntegerField(blank=True, choices=[('International', [(1, 'International')]), ('District', [(11, 'District'), (12, 'Noncompetitive'), (13, 'Affiliate')]), ('Division', [(21, 'Division')]), ('Group', [(32, 'Chapter'), (33, 'Very Large Quartet'), (34, 'Mixed Group'), (41, 'Quartet')])], help_text='\n            The kind of office.', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='part',
            field=models.IntegerField(blank=True, choices=[(-1, 'Director'), (1, 'Tenor'), (2, 'Lead'), (3, 'Baritone'), (4, 'Bass')], null=True),
        ),
    ]
