# Generated by Django 2.1.7 on 2019-03-18 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_outcome_award'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='outcome',
            unique_together={('round', 'award'), ('round', 'contest')},
        ),
    ]
