# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 15:09
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20171111_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-20, 'Legacy'), (-10, 'Inactive'), (0, 'New'), (10, 'Active'), (20, 'Exempt')], default=0),
        ),
    ]
