# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20170622_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='draw',
            field=models.IntegerField(blank=True, help_text='\n            The draw for the initial round only.', null=True),
        ),
    ]
