# Generated by Django 2.0.7 on 2018-07-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_competitor_csa_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='oss_report',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
