# Generated by Django 2.0.2 on 2018-02-07 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20180206_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.Organization'),
        ),
    ]
