# Generated by Django 2.0.7 on 2018-07-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_round_oss_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='sa_report',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
