# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20171111_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='bhs_pk',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
