# Generated by Django 2.0.2 on 2018-02-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20180207_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mos',
            field=models.IntegerField(blank=True, help_text='Estimated Participants-on-Stage', null=True),
        ),
    ]
