# Generated by Django 2.1.7 on 2019-03-18 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20190318_0936'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='outcome',
            unique_together={('round', 'award')},
        ),
    ]
