# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_organization_bhs_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomen', models.CharField(editable=False, max_length=255)),
                ('status', django_fsm.FSMIntegerField(choices=[(-20, 'Legacy'), (-10, 'Inactive'), (0, 'New'), (10, 'Active'), (20, 'Exempt')], default=0)),
                ('mem_status', models.IntegerField(blank=True, choices=[(10, 'Active'), (20, 'Active Internal'), (30, 'Active Licensed'), (40, 'Cancelled'), (50, 'Closed'), (60, 'Closed Merged'), (70, 'Closed Revoked'), (80, 'Closed Voluntary'), (90, 'Expelled'), (100, 'Expired'), (105, 'Expired Licensed'), (110, 'Lapsed'), (120, 'Not Approved'), (130, 'Pending'), (140, 'Pending Voluntary'), (150, 'Suspended'), (160, 'Suspended Membership')], null=True)),
                ('sub_status', models.IntegerField(blank=True, choices=[(10, 'Active'), (20, 'Expired'), (30, 'Pending'), (40, 'Lapsed'), (50, 'Cancelled'), (60, 'Swapped')], null=True)),
                ('code', models.IntegerField(blank=True, choices=[(10, 'RG Regular'), (20, 'R5 Regular 50 Year'), (30, 'SN Senior'), (40, 'S5 Senior 50 Year'), (50, 'SL Senior Legacy'), (60, 'Y1 Youth Initial'), (70, 'Y2 Youth Subsequent'), (80, 'LF Lifetime Regular'), (90, 'L5 Lifetime 50 Year'), (100, 'LY Lifetime Youth'), (110, 'LS Lifetime Senior'), (120, 'AS Associate')], null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('bhs_pk', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
            ],
            options={
                'default_related_name': 'enrollments',
            },
        ),
        migrations.RenameField(
            model_name='member',
            old_name='code',
            new_name='mem_code',
        ),
        migrations.AddField(
            model_name='organization',
            name='mem_status',
            field=models.IntegerField(blank=True, choices=[(10, 'Active'), (20, 'Active Internal'), (30, 'Active Licensed'), (40, 'Cancelled'), (50, 'Closed'), (60, 'Closed Merged'), (70, 'Closed Revoked'), (80, 'Closed Voluntary'), (90, 'Expelled'), (100, 'Expired'), (105, 'Expired Licensed'), (110, 'Lapsed'), (120, 'Not Approved'), (130, 'Pending'), (140, 'Pending Voluntary'), (150, 'Suspended'), (160, 'Suspended Membership')], null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-20, 'Legacy'), (-10, 'Inactive'), (-5, 'AIC'), (0, 'New'), (10, 'Active'), (20, 'Exempt')], default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.Organization'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set([('organization', 'person')]),
        ),
    ]
