# Generated by Django 2.0.2 on 2018-02-09 17:36

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20180207_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=0, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.'),
        ),
    ]
