# Generated by Django 2.0.7 on 2018-07-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_round_sa_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='mos',
            field=models.IntegerField(blank=True, help_text='Actual Participants-on-Stage', null=True),
        ),
    ]
