# Generated by Django 2.1.7 on 2019-03-18 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_remove_outcome_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='api.Award'),
        ),
    ]
