# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20171112_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='short_name',
        ),
    ]
