# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 20:13
from __future__ import unicode_literals

import api.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20170624_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ss',
            field=models.ImageField(blank=True, null=True, upload_to=api.fields.PathAndRename()),
        ),
    ]
