# Generated by Django 2.0.7 on 2018-07-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_appearance_mos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='is_scoring_manager',
            new_name='is_round_manager',
        ),
    ]
