# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 20:19
from __future__ import unicode_literals

import api.fields
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_session_ss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='ss',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=api.fields.PathAndRename()),
        ),
    ]
