# Generated by Django 2.1.7 on 2019-03-18 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20190318_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='api.Group'),
        ),
    ]
