# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_remove_organization_short_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='code',
            new_name='mem_code',
        ),
    ]
