# Generated by Django 2.0.7 on 2018-07-18 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20180718_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='is_judge_manager',
            new_name='is_officer_manager',
        ),
    ]
