# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20171112_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='district',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_dis', to='api.Organization'),
        ),
        migrations.AddField(
            model_name='group',
            name='division',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_div', to='api.Organization'),
        ),
        migrations.AddField(
            model_name='group',
            name='international',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_int', to='api.Organization'),
        ),
    ]
