# Generated by Django 2.0.7 on 2018-07-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20180718_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='is_assignment_manager',
            field=models.BooleanField(default=False),
        ),
    ]
