# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20170625_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='ss',
            new_name='scoresheet',
        ),
    ]
