# Generated by Django 2.0.7 on 2018-07-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_office_is_assignment_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='is_scoring_manager',
            field=models.BooleanField(default=False),
        ),
    ]
