# Generated by Django 2.0.2 on 2018-02-11 05:07

from django.db import migrations


def copy_parent_organization(apps, schema_editor):
    Group = apps.get_model('api', 'Group')
    districts = Group.objects.filter(
        kind__in=[11, 12, 13],
    )
    for district in districts:
        parent = Group.objects.get(
            kind=1,
        )
        district.parent = parent
        district.save()
    divisions = Group.objects.filter(
        kind=21,
    )
    for division in divisions:
        organization = division.organization.parent
        parent = Group.objects.get(
            organization=organization,
            kind=11,
        )
        division.parent = parent
        division.save()
    chapters = Group.objects.filter(
        kind=30,
    )
    for chapter in chapters:
        organization = chapter.organization.parent
        try:
            parent = Group.objects.get(
                organization=organization,
                kind__in=[11, 21],
            )
        except Group.DoesNotExist:
            parent = None
        chapter.parent = parent
        chapter.save()
    return


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_create_groups_from_organizations'),
    ]

    operations = [
        migrations.RunPython(copy_parent_organization),
    ]
