# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20171113_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, help_text='\n            The contact email of the resource.', max_length=254, null=True, unique=True),
        ),
    ]
