# Generated by Django 2.0.7 on 2018-07-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_office_is_scoring_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
