# Generated by Django 2.1.7 on 2019-03-18 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20190318_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='api.Group'),
        ),
    ]
