# Generated by Django 2.0.2 on 2018-02-11 05:07

from django.db import migrations


def copy_parent_organization(apps, schema_editor):
    Group = apps.get_model('api', 'Group')
    choruses = Group.objects.filter(
        kind=32,
    )
    for chorus in choruses:
        organization = chorus.organization
        try:
            parent = Group.objects.get(
                organization=organization,
                kind__lte=30,
            )
        except Group.DoesNotExist:
            parent = None
        chorus.parent = parent
        chorus.save()
    quartets = Group.objects.filter(
        kind=41,
    )
    for quartet in quartets:
        organization = quartet.organization.parent
        try:
            parent = Group.objects.get(
                organization=organization,
                kind__lte=30,
            )
        except Group.DoesNotExist:
            parent = None
        quartet.parent = parent
        quartet.save()
    return


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_copy-parent'),
    ]

    operations = [
        migrations.RunPython(copy_parent_organization),
    ]
