# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20171114_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(help_text='\n            The contact email of the resource.', max_length=254, unique=True),
        ),
    ]
