# Generated by Django 2.1.7 on 2019-03-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20190318_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Copied from entry.'),
        ),
    ]
