# Generated by Django 2.0.7 on 2018-07-23 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20180722_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='legacy_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='competitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appearances', to='api.Competitor'),
        ),
    ]
