# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 17:57
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_auto_20171115_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=0),
        ),
    ]
