# Generated by Django 2.0.2 on 2018-02-11 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_find-parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='api.Group'),
        ),
        migrations.AddField(
            model_name='convention',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions', to='api.Group'),
        ),
        migrations.AddField(
            model_name='grantor',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grantors', to='api.Group'),
        ),
        migrations.AddField(
            model_name='officer',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='api.Group'),
        ),
    ]
