# Generated by Django 2.0.7 on 2018-07-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_auto_20180723_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='gender',
        ),
        migrations.AlterField(
            model_name='session',
            name='num_rounds',
            field=models.IntegerField(default=0),
        ),
    ]
