# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 12:34
from __future__ import unicode_literals

import api.fields
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_auto_20170625_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='bbscores',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=api.fields.PathAndRename(prefix='bbscores')),
        ),
    ]
