# Generated by Django 2.0.7 on 2018-07-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20180723_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
