# Generated by Django 2.0.2 on 2018-02-11 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20180211_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='api.Organization'),
        ),
        migrations.AlterField(
            model_name='convention',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='\n            The owning organization for the convention.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions', to='api.Organization'),
        ),
        migrations.AlterField(
            model_name='grantor',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grantors', to='api.Organization'),
        ),
        migrations.AlterField(
            model_name='group',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='api.Organization'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='api.Organization'),
        ),
    ]
