# Generated by Django 2.1.7 on 2019-03-18 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20190318_1142'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appearance',
            unique_together={('round', 'group'), ('round', 'num')},
        ),
    ]
