# Generated by Django 2.0.7 on 2018-07-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20180723_1027'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appearance',
            unique_together={('round', 'num')},
        ),
    ]
