# Generated by Django 2.0.2 on 2018-02-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20180211_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='tree_sort',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
