# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_person_user2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='person',
        ),
    ]
