# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 16:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_remove_user_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user2',
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL),
        ),
    ]
