# Generated by Django 2.0.2 on 2018-02-11 17:14

from django.db import migrations


def copy_parent_organization(apps, schema_editor):
    Enrollment = apps.get_model('api', 'Enrollment')
    Member = apps.get_model('api', 'Member')
    enrollments = Enrollment.objects.filter(
        organization__kind__in=[32, 41]
    )
    for enrollment in enrollments:
        Member.objects.create(
            status
        )
    return



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_group_tree_sort'),
    ]

    operations = [
        migrations.RunPython(copy_parent_organization),
    ]
