# Generated by Django 2.0.2 on 2018-02-11 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_group_tree_sort'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grantor',
            unique_together=set(),
        ),
    ]
