# Generated by Django 2.1.7 on 2019-03-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_remove_appearance_competitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='run_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
