# Generated by Django 2.0.7 on 2018-07-24 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20180723_1201'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('song', 'num')},
        ),
    ]
