# Generated by Django 2.1.7 on 2019-03-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20190322_0706'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='panelist',
            unique_together={('round', 'num'), ('round', 'person', 'category')},
        ),
    ]
