# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 01:10
from __future__ import unicode_literals

import api.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20170627_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=api.fields.PathAndRename(prefix='chart')),
        ),
    ]
