# Generated by Django 2.0.2 on 2018-02-11 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20180211_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='is_organization_manager',
        ),
        migrations.AlterField(
            model_name='convention',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions', to='api.Organization'),
        ),
        migrations.AlterField(
            model_name='group',
            name='chapter',
            field=models.TextField(blank=True, help_text='\n            The denormalized chapter group.', max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='district',
            field=models.TextField(blank=True, help_text='\n            The denormalized district group.', max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='division',
            field=models.TextField(blank=True, help_text='\n            The denormalized division group.', max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='international',
            field=models.TextField(blank=True, help_text='\n            The denormalized international group.', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
    ]
