# Generated by Django 2.0.2 on 2018-02-11 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20180211_1057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='participant',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='person',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
