# Generated by Django 2.0.7 on 2018-07-24 21:06

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20180724_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The Winner of the Contest.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contests', to='api.Group'),
        ),
        migrations.AlterField(
            model_name='convention',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-30, 'Test'), (-25, 'Manual'), (-20, 'Incomplete'), (-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=0, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.'),
        ),
    ]
