# Generated by Django 2.1.7 on 2019-03-23 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_merge_20190322_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='competitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appearances', to='api.Competitor'),
        ),
    ]
