# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 23:33
from __future__ import unicode_literals

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20171117_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='img',
            field=api.fields.CloudinaryRenameField(blank=True, max_length=255, null=True),
        ),
    ]
