# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 23:43
from __future__ import unicode_literals

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_chart_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='img',
            field=api.fields.CloudinaryRenameField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='img',
            field=api.fields.CloudinaryRenameField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='img',
            field=api.fields.CloudinaryRenameField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='img',
            field=api.fields.CloudinaryRenameField(blank=True, max_length=255, null=True),
        ),
    ]
