# Generated by Django 2.0.7 on 2018-07-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20180724_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='legacy_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
