# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 15:17
from __future__ import unicode_literals

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20171117_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='img',
            field=api.fields.CloudinaryRenameField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='img',
            field=api.fields.CloudinaryRenameField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='group',
            name='img',
            field=api.fields.CloudinaryRenameField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='img',
            field=api.fields.CloudinaryRenameField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='person',
            name='img',
            field=api.fields.CloudinaryRenameField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
