# Generated by Django 2.0.2 on 2018-02-11 20:03

from django.db import migrations

import logging
log = logging.getLogger('importer')


def data_migration(apps, schema_editor):
    Award = apps.get_model('api', 'Award')
    Group = apps.get_model('api', 'Group')
    awards = Award.objects.all()
    for award in awards:
        try:
            award.group = award.organization.groups.get(status__gt=0)
        except Group.DoesNotExist:
            award.group = None
        except Group.MultipleObjectsReturned:
            award.group = None
        award.save()
    return


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_officer_update'),
    ]

    operations = [
        migrations.RunPython(data_migration),
    ]
