# Generated by Django 2.1.7 on 2019-03-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20190324_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='is_multi',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='is_multi',
        ),
    ]
