# Generated by Django 2.0.2 on 2018-02-11 20:03

from django.db import migrations

import logging
log = logging.getLogger('importer')


def data_migration(apps, schema_editor):
    Convention = apps.get_model('api', 'Convention')
    Group = apps.get_model('api', 'Group')
    conventions = Convention.objects.all()
    for convention in conventions:
        try:
            convention.group = convention.organization.groups.get(status__gt=0)
        except Group.DoesNotExist as e:
            log.error("{} {}".format(e, convention.organization))
            convention.group = None
        except Group.MultipleObjectsReturned as e:
            log.error("{} {}".format(e, convention.organization))
        convention.save()
    return


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_award_update'),
    ]

    operations = [
        migrations.RunPython(data_migration),
    ]
