# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_appearance_draw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='is_mt',
        ),
    ]
