# Generated by Django 2.0.7 on 2018-07-25 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_convention_legacy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelist',
            name='legacy_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='panelist',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panelists', to='api.Person'),
        ),
    ]
