# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 17:52
from __future__ import unicode_literals

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20171118_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='admin_emailz',
            field=api.fields.CloudinaryXLSXField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
    ]
