# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 07:00
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_session_admin_emailz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='admin_emails',
        ),
        migrations.RemoveField(
            model_name='session',
            name='bbscores',
        ),
        migrations.AddField(
            model_name='session',
            name='admins_report',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.AddField(
            model_name='session',
            name='bbscores_report',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='session',
            name='drcj_report',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
    ]
