# Generated by Django 2.0.7 on 2018-07-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20180724_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelist',
            name='legacy_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
