# Generated by Django 2.1.7 on 2019-03-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20190324_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='num_rounds',
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='num_rounds',
        ),
        migrations.AddField(
            model_name='outcome',
            name='is_single',
            field=models.BooleanField(default=False, help_text='Single-round award'),
        ),
    ]
