# Generated by Django 2.0.2 on 2018-02-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_grantor_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='bhs_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='bhs_pk',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
