# Generated by Django 2.0.7 on 2018-07-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20180725_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='is_later',
            field=models.BooleanField(default=False, help_text='Deferred Award'),
        ),
    ]
