# Generated by Django 2.1.7 on 2019-03-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20190324_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='old_oss',
        ),
    ]
