# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 07:00
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20171118_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='admin_emailz',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
    ]
