# Generated by Django 2.1.7 on 2019-03-24 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_remove_session_old_oss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='is_single',
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='is_single',
        ),
    ]
