# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 22:14
from __future__ import unicode_literals

import api.fields
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_entry_csa_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='oss_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=api.fields.PathAndRename(prefix='oss')),
        ),
    ]
