# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20171118_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='admin_emailz',
        ),
    ]
