# Generated by Django 2.1.7 on 2019-03-24 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20190324_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='representing',
        ),
    ]
