# Generated by Django 2.0.2 on 2018-02-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_patch_chorus_officers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
