# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_session_oss_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelist',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
