# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 07:18
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_remove_session_admin_emailz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='admins_report',
            field=cloudinary.models.CloudinaryField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='bbscores_report',
            field=cloudinary.models.CloudinaryField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='drcj_report',
            field=cloudinary.models.CloudinaryField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
