# Generated by Django 2.0.7 on 2018-07-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20180727_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
