# Generated by Django 2.0.2 on 2018-02-13 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20180212_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='auth0_id',
            new_name='account_id',
        ),
    ]
