# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20171118_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='var_pdf',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='csa_pdf',
        ),
        migrations.RemoveField(
            model_name='round',
            name='ann_pdf',
        ),
        migrations.RemoveField(
            model_name='session',
            name='ann_pdf',
        ),
        migrations.RemoveField(
            model_name='session',
            name='oss_pdf',
        ),
        migrations.RemoveField(
            model_name='session',
            name='scoresheet',
        ),
    ]
