# Generated by Django 2.1.7 on 2019-03-24 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_remove_appearance_representing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='participants',
        ),
    ]
