# Generated by Django 2.0.7 on 2018-07-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_auto_20180727_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appearance',
            old_name='mos',
            new_name='pos',
        ),
        migrations.RenameField(
            model_name='competitor',
            old_name='mos',
            new_name='pos',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='mos',
            new_name='pos',
        ),
    ]
