# Generated by Django 2.1.7 on 2019-03-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_remove_appearance_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='participants',
            field=models.CharField(blank=True, default='', help_text='Director(s) or Members (listed TLBB)', max_length=255),
        ),
    ]
