# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_auto_20171119_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='image',
        ),
        migrations.RemoveField(
            model_name='group',
            name='image',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='image',
        ),
        migrations.RemoveField(
            model_name='person',
            name='image',
        ),
    ]
