# Generated by Django 2.0.2 on 2018-02-13 19:05

import api.models.appearance
import api.models.chart
import api.models.competitor
import api.models.group
import api.models.person
import api.models.round
import api.models.session
import api.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_auto_20180212_2133'),
    ]

    api.models.session.upload_to_actives = None

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='variance_report_new',
            field=models.FileField(blank=True, max_length=255, storage=api.storages.CustomPDFCloudinaryStorage(), upload_to=api.models.appearance.upload_to_variance),
        ),
        migrations.AddField(
            model_name='chart',
            name='image',
            field=models.ImageField(blank=True, storage=api.storages.CustomMediaCloudinaryStorage(), upload_to=api.models.chart.upload_to),
        ),
        migrations.AddField(
            model_name='competitor',
            name='csa_report_new',
            field=models.FileField(blank=True, max_length=255, storage=api.storages.CustomPDFCloudinaryStorage(), upload_to=api.models.competitor.upload_to_csa),
        ),
        migrations.AddField(
            model_name='competitor',
            name='image',
            field=models.ImageField(blank=True, storage=api.storages.CustomMediaCloudinaryStorage(), upload_to=api.models.competitor.upload_to),
        ),
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, storage=api.storages.CustomMediaCloudinaryStorage(), upload_to=api.models.group.upload_to),
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, storage=api.storages.CustomMediaCloudinaryStorage(), upload_to=api.models.person.upload_to),
        ),
        migrations.AddField(
            model_name='round',
            name='ors_report_new',
            field=models.FileField(blank=True, max_length=255, storage=api.storages.CustomPDFCloudinaryStorage(), upload_to=api.models.round.upload_to_ors),
        ),
        migrations.AddField(
            model_name='session',
            name='actives_report_new',
            field=models.FileField(blank=True, max_length=255, storage=api.storages.CustomExcelCloudinaryStorage(), upload_to=api.models.session.upload_to_actives),
        ),
        migrations.AddField(
            model_name='session',
            name='admins_report_new',
            field=models.FileField(blank=True, max_length=255, storage=api.storages.CustomExcelCloudinaryStorage(), upload_to=api.models.session.upload_to_admins),
        ),
        migrations.AddField(
            model_name='session',
            name='bbscores_report_new',
            field=models.FileField(blank=True, max_length=255, storage=api.storages.CustomExcelCloudinaryStorage(), upload_to=api.models.session.upload_to_bbscores),
        ),
        migrations.AddField(
            model_name='session',
            name='drcj_report_new',
            field=models.FileField(blank=True, max_length=255, storage=api.storages.CustomExcelCloudinaryStorage(), upload_to=api.models.session.upload_to_drcj),
        ),
        migrations.AddField(
            model_name='session',
            name='oss_report_new',
            field=models.FileField(blank=True, max_length=255, storage=api.storages.CustomPDFCloudinaryStorage(), upload_to=api.models.session.upload_to_oss),
        ),
        migrations.AddField(
            model_name='session',
            name='sa_report_new',
            field=models.FileField(blank=True, max_length=255, storage=api.storages.CustomPDFCloudinaryStorage(), upload_to=api.models.session.upload_to_sa),
        ),
    ]
