# Generated by Django 2.1.7 on 2019-03-25 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_group_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='pos',
        ),
    ]
