# Generated by Django 2.0.7 on 2018-07-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_auto_20180728_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='directors',
            new_name='participants',
        ),
    ]
