# Generated by Django 2.0.2 on 2018-02-13 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_auto_20180213_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='actives_report',
        ),
        migrations.RemoveField(
            model_name='session',
            name='actives_report_new',
        ),
    ]
