# Generated by Django 2.0.2 on 2018-02-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_auto_20180213_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='inactive_int',
            field=models.IntegerField(blank=True, choices=[(1, 'Non-Renewal'), (2, 'Renewed'), (3, 'Not Cancelled'), (4, 'Non-Payment'), (5, 'Expired'), (6, 'Deceased'), (7, 'changedOption'), (8, 'Other'), (9, 'cancelled'), (10, 'Transferred'), (11, 'swappedChapter'), (12, 'swapped')], null=True),
        ),
    ]
