# Generated by Django 2.1.7 on 2019-03-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_remove_competitor_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='draw',
            field=models.IntegerField(blank=True, help_text='The initial draw', null=True),
        ),
    ]
