# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_auto_20170708_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='is_jc',
            new_name='is_jm',
        ),
    ]
