# Generated by Django 2.1.7 on 2019-03-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_auto_20190324_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='actual_finish',
            field=models.DateTimeField(blank=True, help_text='\n            The actual appearance datetime.', null=True),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='actual_start',
            field=models.DateTimeField(blank=True, help_text='\n            The actual appearance datetime.', null=True),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='draw',
            field=models.IntegerField(blank=True, help_text='The draw for the next round.', null=True),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='num',
            field=models.IntegerField(help_text='The order of appearance for this round.'),
        ),
    ]
