# Generated by Django 2.0.2 on 2018-02-14 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_member_inactive_int'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='inactive_reason',
        ),
    ]
