# Generated by Django 2.0 on 2018-08-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_auto_20180806_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Copied from entry.'),
        ),
    ]
