# Generated by Django 2.0.2 on 2018-02-14 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_remove_member_inactive_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='inactive_int',
            new_name='inactive_reason',
        ),
    ]
