# Generated by Django 2.1.7 on 2019-03-25 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_remove_appearance_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='contesting',
        ),
    ]
