# Generated by Django 2.0.7 on 2018-08-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_auto_20180809_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='csa',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
