# Generated by Django 2.0.2 on 2018-02-15 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_auto_20180214_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='api.Group'),
        ),
        migrations.RemoveField(
            model_name='officer',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='officer',
            unique_together={('group', 'person', 'office')},
        ),
    ]
