# Generated by Django 2.0.7 on 2018-08-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_round_csa'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='spots',
            field=models.IntegerField(blank=True, help_text='Number of top spots which qualify', null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='level',
            field=models.IntegerField(choices=[(10, 'Championship'), (30, 'Qualifier'), (35, 'Top'), (40, 'Award'), (50, 'Deferred'), (60, 'Manual')]),
        ),
    ]
