# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_auto_20170710_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='is_ca',
            new_name='is_scoring_manager',
        ),
    ]
