# Generated by Django 2.0.7 on 2018-08-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_auto_20180810_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='level',
            field=models.IntegerField(choices=[(10, 'Championship'), (30, 'Qualifier'), (35, 'Top'), (40, 'Award'), (45, 'Representative'), (50, 'Deferred'), (60, 'Manual')]),
        ),
    ]
