# Generated by Django 2.0.2 on 2018-02-16 06:29

import api.models.chart
import api.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_auto_20180215_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='image',
            field=models.FileField(blank=True, storage=api.storages.CustomMediaCloudinaryStorage(), upload_to=api.models.chart.upload_to),
        ),
    ]
