# Generated by Django 2.0.7 on 2018-08-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_auto_20180820_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='mc_pk',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mc_pk',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='mc_pk',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='mc_pk',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='mc_pk',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='mc_pk',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, unique=True),
        ),
    ]
