# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_auto_20170710_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='is_district_representative',
            new_name='is_rep_qualifies',
        ),
    ]
