# Generated by Django 2.0.2 on 2018-02-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_auto_20180215_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='bhs_pk',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
