# Generated by Django 2.1.7 on 2019-03-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_auto_20190324_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='group',
        ),
    ]
