# Generated by Django 2.1.7 on 2019-03-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_remove_appearance_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelist',
            name='psa',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
