# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_auto_20170711_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='description',
            field=models.TextField(blank=True, help_text="\n            Fun or interesting facts to share about the chart (ie, 'from Disney's Lion King, first sung by Elton John'.)", max_length=1000),
        ),
        migrations.AddField(
            model_name='chart',
            name='notes',
            field=models.TextField(blank=True, help_text='\n            Private Notes (for internal use only).'),
        ),
    ]
