# Generated by Django 2.0.8 on 2018-08-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_auto_20180820_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_through',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
