# Generated by Django 2.0.2 on 2018-02-18 05:19

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_auto_20180216_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='nomen',
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=0, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.'),
        ),
    ]
