# Generated by Django 2.1.7 on 2019-03-28 05:03

import api.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_panelist_psa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.fields.ImageUploadPath()),
        ),
    ]
