# Generated by Django 2.0.8 on 2018-08-21 18:01

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_auto_20180821_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=api.fields.LowerEmailField(blank=True, help_text='\n            The contact email of the resource.', max_length=254, null=True, unique=True),
        ),
    ]
