# Generated by Django 2.0.2 on 2018-02-18 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_auto_20180217_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='end_date',
            new_name='current_through',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='start_date',
            new_name='established_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_admin',
        ),
    ]
