# Generated by Django 2.0.2 on 2018-02-20 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_auto_20180218_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='person',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='award',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='convention',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='grantor',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='group',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
