# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_auto_20170715_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.Organization'),
        ),
    ]
