# Generated by Django 2.1.7 on 2019-03-28 17:53

import api.fields
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_auto_20190327_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='variance_report',
            field=models.FileField(blank=True, upload_to=api.fields.FileUploadPath()),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='csa',
            field=models.FileField(blank=True, upload_to=api.fields.FileUploadPath()),
        ),
        migrations.AlterField(
            model_name='panelist',
            name='psa',
            field=models.FileField(blank=True, upload_to=api.fields.FileUploadPath()),
        ),
        migrations.AlterField(
            model_name='round',
            name='legacy_oss',
            field=models.FileField(blank=True, upload_to=api.fields.FileUploadPath()),
        ),
        migrations.AlterField(
            model_name='round',
            name='legacy_sa',
            field=models.FileField(blank=True, upload_to=api.fields.FileUploadPath()),
        ),
        migrations.AlterField(
            model_name='round',
            name='old_oss',
            field=models.FileField(blank=True, upload_to=api.fields.FileUploadPath()),
        ),
        migrations.AlterField(
            model_name='round',
            name='oss',
            field=models.FileField(blank=True, upload_to=api.fields.FileUploadPath()),
        ),
        migrations.AlterField(
            model_name='round',
            name='sa',
            field=models.FileField(blank=True, upload_to=api.fields.FileUploadPath()),
        ),
        migrations.AlterField(
            model_name='session',
            name='contact_report',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=api.fields.FileUploadPath()),
        ),
        migrations.AlterField(
            model_name='session',
            name='drcj_report',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=api.fields.FileUploadPath()),
        ),
        migrations.AlterField(
            model_name='session',
            name='legacy_report',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=api.fields.FileUploadPath()),
        ),
        migrations.AlterField(
            model_name='session',
            name='oss',
            field=models.FileField(blank=True, upload_to=api.fields.FileUploadPath()),
        ),
        migrations.AlterField(
            model_name='session',
            name='sa',
            field=models.FileField(blank=True, upload_to=api.fields.FileUploadPath()),
        ),
    ]
