# Generated by Django 2.0.8 on 2018-08-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_user_mc_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='current_through',
        ),
    ]
