# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_entry_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='\n            The owning organization for the convention.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conventions', to='api.Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('group', 'session')]),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([('group', 'person')]),
        ),
        migrations.AlterUniqueTogether(
            name='repertory',
            unique_together=set([('group', 'chart')]),
        ),
    ]
