# Generated by Django 2.0.7 on 2018-08-21 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_remove_person_current_through'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
