# Generated by Django 2.1.7 on 2019-03-28 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_auto_20190328_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='run_points',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='run_score',
        ),
    ]
