# Generated by Django 2.1.7 on 2019-03-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_auto_20190328_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='oss',
        ),
        migrations.RemoveField(
            model_name='session',
            name='sa',
        ),
    ]
