# Generated by Django 2.0.2 on 2018-02-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_auto_20180219_2236'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set(),
        ),
    ]
