# Generated by Django 2.0.8 on 2018-08-22 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_auto_20180821_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appearance',
            old_name='all_points',
            new_name='practice_points',
        ),
    ]
