# Generated by Django 2.0.2 on 2018-02-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_auto_20180220_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default='UNKNOWN', help_text='\n            The name of the resource.\n        ', max_length=255),
        ),
    ]
