# Generated by Django 2.1.7 on 2019-03-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_remove_competitor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='legacy_oss',
        ),
        migrations.RemoveField(
            model_name='round',
            name='legacy_sa',
        ),
    ]
