# Generated by Django 2.0.8 on 2018-08-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_auto_20180823_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
