# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_member_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='award',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='convention',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='representing',
        ),
        migrations.RemoveField(
            model_name='member',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='person',
            name='representing',
        ),
        migrations.RemoveField(
            model_name='repertory',
            name='entity',
        ),
        migrations.AlterField(
            model_name='award',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='api.Organization'),
        ),
        migrations.AlterField(
            model_name='convention',
            name='organization',
            field=models.ForeignKey(help_text='\n            The owning organization for the convention.', on_delete=django.db.models.deletion.CASCADE, related_name='conventions', to='api.Organization'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.Group'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.Organization'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, help_text='\n            A description of the group.  Max 1000 characters.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='member',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.Group'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='api.Organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, help_text='\n            A description of the organization.  Max 1000 characters.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='repertory',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repertories', to='api.Group'),
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
