# Generated by Django 2.0.8 on 2018-08-29 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_auto_20180826_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='current_through',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='established_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='inactive_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='inactive_reason',
        ),
        migrations.RemoveField(
            model_name='member',
            name='mem_code',
        ),
        migrations.RemoveField(
            model_name='member',
            name='mem_status',
        ),
        migrations.RemoveField(
            model_name='member',
            name='sub_status',
        ),
    ]
