# Generated by Django 2.1.7 on 2019-03-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_auto_20190328_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='old_oss',
            new_name='legacy_oss',
        ),
    ]
