# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_auto_20170718_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='is_novice',
        ),
        migrations.RemoveField(
            model_name='award',
            name='is_qualifier',
        ),
        migrations.AddField(
            model_name='award',
            name='is_invitational',
            field=models.BooleanField(default=False, help_text='Invite-only (v. Open).'),
        ),
        migrations.AlterField(
            model_name='award',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='Manual (v. Automatic).'),
        ),
        migrations.AlterField(
            model_name='award',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Primary (v. Secondary).'),
        ),
    ]
