# Generated by Django 2.0.8 on 2018-08-29 05:20

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_auto_20180828_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='email',
            field=api.fields.LowerEmailField(blank=True, help_text='\n            The contact email of the resource.', max_length=254, null=True),
        ),
    ]
