# Generated by Django 2.1.7 on 2019-03-29 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_auto_20190328_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appearances', to='api.Group'),
        ),
    ]
