# Generated by Django 2.1.7 on 2019-03-29 17:56

from django.db import migrations

def copy_groups(apps, schema_editor):
    Appearance = apps.get_model('api.appearance')
    appearances = Appearance.objects.filter(
        competitor__isnull=False,
    ).select_related(
        'competitor',
        'competitor__group',
    )
    for appearance in appearances:
        appearance.group = appearance.competitor.group
        appearance.save()



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_appearance_group'),
    ]

    operations = [
        migrations.RunPython(copy_groups),
    ]
