# Generated by Django 2.0.8 on 2018-08-29 16:54

import api.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_auto_20180828_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=api.fields.LowerEmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
