# Generated by Django 2.0.2 on 2018-02-11 20:03

from django.db import migrations

import logging
log = logging.getLogger('importer')


def data_migration(apps, schema_editor):
    User = apps.get_model('api', 'User')
    Person = apps.get_model('api', 'Person')
    users = User.objects.all()
    for user in users:
        try:
            person = Person.objects.get(user=user)
        except Person.DoesNotExist:
            user.delete()
            continue
        user.person = person
        user.save()
    return


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_user_person'),
    ]

    operations = [
        migrations.RunPython(data_migration),
    ]
