# Generated by Django 2.0.8 on 2018-08-29 17:27

import api.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_auto_20180829_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=api.fields.LowerEmailField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
