# Generated by Django 2.0.2 on 2018-02-20 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_auto_20180220_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
    ]
