# Generated by Django 2.0.8 on 2018-08-29 22:24

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_auto_20180829_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=api.fields.LowerEmailField(max_length=100, unique=True),
        ),
    ]
