# Generated by Django 2.1.7 on 2019-03-29 18:28

from django.db import migrations

def complete_verified_appearances(apps, schema_editor):
    Appearance = apps.get_model('api.appearance')
    appearances = Appearance.objects.filter(
        status=30, # Verified
    )
    appearances.update(status=-10) # Completed



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_auto_20190329_1128'),
    ]

    operations = [
        migrations.RunPython(complete_verified_appearances),
    ]
