# Generated by Django 2.0.8 on 2018-09-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_auto_20180829_1524'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('bhs_id', 'kind')},
        ),
    ]
