# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 20:26
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_auto_20170720_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (5, 'Provisional'), (10, 'Active')], default=0),
        ),
    ]
