# Generated by Django 2.1.7 on 2019-03-29 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_auto_20190329_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appearances', to='api.Entry'),
        ),
    ]
