# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_auto_20170720_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='description',
            field=models.TextField(blank=True, help_text='\n            The Public description of the award.', max_length=1000),
        ),
        migrations.AddField(
            model_name='award',
            name='footnote',
            field=models.CharField(blank=True, help_text='\n            The text to present on the OSS', max_length=255),
        ),
        migrations.AddField(
            model_name='award',
            name='notes',
            field=models.TextField(blank=True, help_text='\n            Private Notes (for internal use only).'),
        ),
    ]
