# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_auto_20170722_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='is_cj',
        ),
    ]
