# Generated by Django 2.1.7 on 2019-03-29 19:16

import api.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_appearance_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='contesting',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, help_text='Award numbers contestanting', null=True, size=None),
        ),
        migrations.AddField(
            model_name='appearance',
            name='csa',
            field=models.FileField(blank=True, upload_to=api.fields.FileUploadPath()),
        ),
        migrations.AddField(
            model_name='appearance',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Copied from entry.'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='is_single',
            field=models.BooleanField(default=False, help_text='Single-round competitor'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='participants',
            field=models.CharField(blank=True, default='', help_text='Director(s) or Members (listed TLBB)', max_length=255),
        ),
        migrations.AddField(
            model_name='appearance',
            name='representing',
            field=models.CharField(blank=True, default='', help_text='Representing entity', max_length=255),
        ),
    ]
