# Generated by Django 2.0.2 on 2018-02-21 18:47

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_auto_20180220_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repertory',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=10, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.'),
        ),
    ]
