# Generated by Django 2.0.2 on 2018-02-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_auto_20180221_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='bhs_pk',
            new_name='mc_pk',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='bhs_pk',
            new_name='mc_pk',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='bhs_pk',
            new_name='mc_pk',
        ),
        migrations.RenameField(
            model_name='officer',
            old_name='bhs_pk',
            new_name='mc_pk',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='bhs_pk',
            new_name='mc_pk',
        ),
    ]
