# Generated by Django 2.1.7 on 2019-03-29 19:16

from django.db import migrations

def forward(apps, schema_editor):
    Appearance = apps.get_model('api.appearance')
    Entry = apps.get_model('api.entry')
    appearances = Appearance.objects.select_related(
        'group',
        'round__session',
    )
    for appearance in appearances:
        try:
            entry = Entry.objects.get(
                group=appearance.group,
                session=appearance.round.session,
            )
        except Entry.DoesNotExist:
            continue
        is_single = not bool(
            entry.contestants.filter(
                status__gt=0,
                contest__award__is_single=False,
            )
        )
        # Create the contesting legend
        contestants = entry.contestants.filter(
            status=10, # Included
        ).order_by(
            'contest__num',
        ).values_list(
            'contest__num',
            flat=True,
        )
        contesting = list(contestants)
        appearance.entry = entry
        appearance.is_private = entry.is_private
        appearance.is_single = is_single
        appearance.participants = entry.participants
        appearance.representing = entry.representing
        appearance.contesting = contesting
        appearance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_auto_20190329_1216'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
