# Generated by Django 2.0.8 on 2018-09-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_auto_20180904_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='kind',
            field=models.IntegerField(choices=[(32, 'Chorus'), (41, 'Quartet'), (42, 'Mixed')], help_text='\n            The kind of session.  Generally this will be either quartet or chorus.\n        '),
        ),
    ]
