# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_remove_office_is_cj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='level',
            field=models.IntegerField(blank=True, choices=[(10, 'Championship'), (20, 'Award'), (30, 'Qualifier'), (40, 'Sentinel')], null=True),
        ),
    ]
