# Generated by Django 2.1.7 on 2019-03-29 22:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_auto_20190329_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contender',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', django_fsm.FSMIntegerField(choices=[(-10, 'Excluded'), (0, 'New'), (10, 'Included')], default=0, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.')),
                ('appearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenders', to='api.Appearance')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenders', to='api.Outcome')),
            ],
            options={
                'ordering': ('contest__num',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='contender',
            unique_together={('appearance', 'outcome')},
        ),
    ]
