# Generated by Django 2.0.8 on 2018-09-06 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_auto_20180906_1240'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='panelist',
            unique_together={('round', 'num'), ('round', 'person')},
        ),
    ]
