# Generated by Django 2.1.7 on 2019-03-29 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_auto_20190329_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grid',
            name='appearance',
        ),
    ]
