# Generated by Django 2.0.8 on 2018-09-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_auto_20180906_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='legacy_chart',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
