# Generated by Django 2.1.7 on 2019-03-30 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_remove_grid_appearance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contender',
            options={'ordering': ('outcome__num',)},
        ),
    ]
