# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_auto_20170724_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=0),
        ),
        migrations.AlterField(
            model_name='panelist',
            name='status',
            field=models.IntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=0),
        ),
    ]
