# Generated by Django 2.0.8 on 2018-09-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_song_legacy_chart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='panelist',
            unique_together={('round', 'num')},
        ),
    ]
