# Generated by Django 2.1.7 on 2019-03-31 04:49

from django.db import migrations

def forward(apps, schema_editor):
    Appearance = apps.get_model('api.appearance')
    appearances = Appearance.objects.filter(
        round__session__convention__status=10,
    )

    for a in appearances:
        outcomes = a.round.outcomes.filter(
            num__in=a.contesting,
        )
        for outcome in outcomes:
            outcome.contenders.create(
                appearance=a,
            )



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_auto_20190329_1712'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
