# Generated by Django 2.0.8 on 2018-09-10 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_auto_20180910_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelist',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panelists', to='api.Person'),
        ),
    ]
