# Generated by Django 2.0.8 on 2018-09-10 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_auto_20180910_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='competitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='api.Competitor'),
        ),
    ]
