# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 05:44
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_auto_20170726_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'New'), (4, 'Opened'), (6, 'Restricted'), (8, 'Closed'), (10, 'Verified'), (20, 'Started'), (30, 'Finished'), (45, 'Announced'), (95, 'Archived')], default=0),
        ),
    ]
