# Generated by Django 2.1.7 on 2019-04-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_auto_20190331_1038'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competitor',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='group',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='session',
        ),
        migrations.AlterField(
            model_name='appearance',
            name='is_single',
            field=models.BooleanField(default=False, help_text='Single-round group'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.TextField(blank=True, help_text='\n            Public Notes (usually from group).', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Competitor',
        ),
    ]
