# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_auto_20170726_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_invitational',
            field=models.BooleanField(default=False, help_text='Invite-only (v. Open).'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'New'), (4, 'Opened'), (8, 'Closed'), (10, 'Verified'), (20, 'Started'), (30, 'Finished'), (45, 'Announced'), (95, 'Archived')], default=0),
        ),
    ]
