# Generated by Django 2.1.7 on 2019-04-01 21:15

import api.fields
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_auto_20190401_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='csa',
            field=models.FileField(blank=True, default='', upload_to=api.fields.FileUploadPath()),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='variance_report',
            field=models.FileField(blank=True, default='', upload_to=api.fields.FileUploadPath()),
        ),
        migrations.AlterField(
            model_name='panelist',
            name='psa',
            field=models.FileField(blank=True, default='', upload_to=api.fields.FileUploadPath()),
        ),
        migrations.AlterField(
            model_name='round',
            name='legacy_oss',
            field=models.FileField(blank=True, default='', upload_to=api.fields.FileUploadPath()),
        ),
        migrations.AlterField(
            model_name='round',
            name='oss',
            field=models.FileField(blank=True, default='', upload_to=api.fields.FileUploadPath()),
        ),
        migrations.AlterField(
            model_name='round',
            name='sa',
            field=models.FileField(blank=True, default='', upload_to=api.fields.FileUploadPath()),
        ),
        migrations.AlterField(
            model_name='session',
            name='contact_report',
            field=models.FileField(blank=True, default='', storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=api.fields.FileUploadPath()),
        ),
        migrations.AlterField(
            model_name='session',
            name='drcj_report',
            field=models.FileField(blank=True, default='', storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=api.fields.FileUploadPath()),
        ),
        migrations.AlterField(
            model_name='session',
            name='legacy_report',
            field=models.FileField(blank=True, default='', storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=api.fields.FileUploadPath()),
        ),
    ]
