# Generated by Django 2.0.8 on 2018-09-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_auto_20180910_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='legacy_oss',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
