# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 17:47
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_auto_20170727_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (-5, 'AIC'), (0, 'New'), (10, 'Active')], default=0),
        ),
    ]
