# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 17:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_auto_20170801_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(editable=False, max_length=254, unique=True),
        ),
    ]
