# Generated by Django 2.1.7 on 2019-04-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_auto_20190402_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestant',
            options={'ordering': ('contest__award__tree_sort',)},
        ),
    ]
