# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_auto_20170802_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grantor',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomen', models.CharField(editable=False, max_length=255)),
                ('status', django_fsm.FSMIntegerField(choices=[(0, 'New')], default=0)),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grantors', to='api.Convention')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grantors', to='api.Organization')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='grantor',
            unique_together=set([('convention', 'organization')]),
        ),
    ]
