# Generated by Django 2.1.7 on 2019-04-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_remove_session_contact_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelist',
            name='status',
            field=models.IntegerField(choices=[(-10, 'Inactive'), (-5, 'Completed'), (0, 'New'), (10, 'Active')], default=0),
        ),
    ]
