# Generated by Django 2.1.1 on 2018-09-20 16:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_auto_20180918_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='practice_points',
        ),
        migrations.RemoveField(
            model_name='score',
            name='is_flagged',
        ),
        migrations.AddField(
            model_name='song',
            name='asterisks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(30, 'Music'), (40, 'Performance'), (50, 'Singing')]), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='song',
            name='dixons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(30, 'Music'), (40, 'Performance'), (50, 'Singing')]), blank=True, default=list, size=None),
        ),
    ]
