# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_auto_20170802_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantor',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grantors', to='api.Session'),
        ),
        migrations.AlterUniqueTogether(
            name='grantor',
            unique_together=set([]),
        ),
    ]
