# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_auto_20170807_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantor',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grantors', to='api.Session'),
        ),
        migrations.RemoveField(
            model_name='grantor',
            name='convention',
        ),
        migrations.AlterUniqueTogether(
            name='grantor',
            unique_together=set([('session', 'organization')]),
        ),
    ]
