# Generated by Django 2.1.1 on 2018-09-24 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_auto_20180923_2104'),
        ('api', '0117_auto_20180922_2158'),
    ]

    operations = [
    ]
