# Generated by Django 2.1.1 on 2018-09-30 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_round_legacy_sa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='csa',
        ),
    ]
