# Generated by Django 2.1.8 on 2019-04-12 21:40

from django.db import migrations
from django.db.models import Avg


class Migration(migrations.Migration):
    def forward(apps, schema_editor):
        Appearance = apps.get_model('api.appearance')
        Entry = apps.get_model('api.entry')
        Score = apps.get_model('api.score')
        es = Entry.objects.filter(
            session__convention__status=10,
        )
        for e in es:
            try:
                appearance = Appearance.objects.filter(
                    group=e.group,
                    status=-10,
                ).latest(
                    'round__date',
                )
            except Appearance.DoesNotExist:
                appearance = None
            if appearance:
                base = Score.objects.filter(
                    panelist__kind=10,
                    song__appearance=appearance,
                ).aggregate(
                    avg=Avg(
                        'points',
                    )
                )['avg']
            else:
                base = None
            e.base = base
            e.save()
            ps = e.appearances.all()
            ps.update(base=None)



    dependencies = [
        ('api', '0120_auto_20190412_1405'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
