# Generated by Django 2.1.8 on 2019-04-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_auto_20190412_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mon',
            field=models.IntegerField(blank=True, help_text='\n            Men of Note.', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='prefix',
            field=models.CharField(blank=True, help_text='\n            The prefix of the person.', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='suffix',
            field=models.CharField(blank=True, help_text='\n            The suffix of the person.', max_length=255),
        ),
    ]
