# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_auto_20170816_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bhs_pk',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
