# Generated by Django 2.1.8 on 2019-04-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_auto_20190424_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='mem_status',
        ),
        migrations.AddField(
            model_name='group',
            name='flickr',
            field=models.URLField(blank=True, default='', help_text='\n            The flickr URL of the resource.'),
        ),
        migrations.AddField(
            model_name='group',
            name='instagram',
            field=models.URLField(blank=True, default='', help_text='\n            The instagram URL of the resource.'),
        ),
        migrations.AddField(
            model_name='group',
            name='pinterest',
            field=models.URLField(blank=True, default='', help_text='\n            The pinterest URL of the resource.'),
        ),
        migrations.AddField(
            model_name='group',
            name='soundcloud',
            field=models.URLField(blank=True, default='', help_text='\n            The soundcloud URL of the resource.'),
        ),
        migrations.AddField(
            model_name='group',
            name='visitor_information',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='group',
            name='youtube',
            field=models.URLField(blank=True, default='', help_text='\n            The youtube URL of the resource.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='twitter',
            field=models.URLField(blank=True, help_text='\n            The twitter URL of the resource.'),
        ),
    ]
