# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_person_bhs_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='bhs_pk',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='bhs_pk',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
