# Generated by Django 2.1.8 on 2019-04-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_auto_20190425_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='fax_phone',
            field=models.CharField(blank=True, help_text='\n            The fax number of the resource.  Include country code.', max_length=25),
        ),
    ]
