# Generated by Django 2.1.1 on 2018-10-02 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_auto_20181001_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='api.Contest'),
        ),
    ]
