# Generated by Django 2.1.8 on 2019-05-01 23:38

import api.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_group_fax_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='person',
            name='twitter',
        ),
        migrations.AlterField(
            model_name='person',
            name='bhs_id',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='cell_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(editable=False, help_text='\n            The cell phone number of the resource.  Include country code.', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='district',
            field=models.CharField(blank=True, default='', help_text='\n            District (used primarily for judges.)', max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=api.fields.LowerEmailField(editable=False, help_text='\n            The contact email of the resource.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(editable=False, help_text='\n            The first name of the person.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.IntegerField(choices=[(10, 'Male'), (20, 'Female')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='home_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(editable=False, help_text='\n            The home phone number of the resource.  Include country code.', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(editable=False, help_text='\n            The last name of the person.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(editable=False, help_text='\n            The middle name of the person.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='mon',
            field=models.IntegerField(editable=False, help_text='\n            Men of Note.', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='nick_name',
            field=models.CharField(editable=False, help_text='\n            The nickname of the person.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='part',
            field=models.IntegerField(choices=[(1, 'Tenor'), (2, 'Lead'), (3, 'Baritone'), (4, 'Bass')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='prefix',
            field=models.CharField(blank=True, default='', help_text='\n            The prefix of the person.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='suffix',
            field=models.CharField(blank=True, default='', help_text='\n            The suffix of the person.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(editable=False, help_text='\n            The work phone number of the resource.  Include country code.', max_length=128, region=None),
        ),
    ]
