# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_auto_20170817_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(10, 'Male'), (20, 'Female')], null=True),
        ),
    ]
