# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 03:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True, default='', help_text='\n            The complete address of the resource.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='person',
            name='cell_phone',
            field=models.CharField(blank=True, default='', help_text='\n            The cell phone number of the resource.  Include country code.', max_length=25),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, default='', help_text='\n            A bio of the person.  Max 1000 characters.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='person',
            name='facebook',
            field=models.URLField(blank=True, default='', help_text='\n            The facebook URL of the resource.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='home_phone',
            field=models.CharField(blank=True, default='', help_text='\n            The home phone number of the resource.  Include country code.', max_length=25),
        ),
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.CharField(blank=True, default='', help_text='\n            The geographical location of the resource.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='\n            Notes (for internal use only).'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='\n            The phone number of the resource.  Include country code.', max_length=25),
        ),
        migrations.AlterField(
            model_name='person',
            name='spouse',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='twitter',
            field=models.CharField(blank=True, default='', help_text='\n            The twitter handle (in form @twitter_handle) of the resource.', max_length=16, validators=[django.core.validators.RegexValidator(message='\n                    Must be a single Twitter handle\n                    in the form `@twitter_handle`.\n                ', regex='@([A-Za-z0-9_]+)')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='website',
            field=models.URLField(blank=True, default='', help_text='\n            The website URL of the resource.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_phone',
            field=models.CharField(blank=True, default='', help_text='\n            The work phone number of the resource.  Include country code.', max_length=25),
        ),
    ]
