# Generated by Django 2.1.2 on 2018-10-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_auto_20181002_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='age',
            field=models.IntegerField(blank=True, choices=[(10, 'Seniors'), (20, 'Novice'), (30, 'Youth')], null=True),
        ),
    ]
