# Generated by Django 2.1.8 on 2019-05-06 03:57

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_auto_20190501_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=api.fields.LowerEmailField(blank=True, help_text='\n            The contact email of the resource.', max_length=254, null=True),
        ),
    ]
