# Generated by Django 2.1.2 on 2018-10-08 02:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_auto_20181005_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('session_name', models.CharField(blank=True, max_length=255)),
                ('round_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('judge', models.CharField(blank=True, max_length=255)),
                ('single', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
