# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_auto_20170817_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Person'),
        ),
    ]
