# Generated by Django 2.1.8 on 2019-05-07 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete',
            name='panelist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oldcompletes', to='api.Panelist'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oldflats', to='api.Score'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='song',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oldselections', to='api.Song'),
        ),
    ]
