# Generated by Django 2.1.2 on 2018-10-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete',
            name='draw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complete',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complete',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
