# Generated by Django 2.1.2 on 2018-10-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_auto_20181007_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complete',
            name='round_name',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='session_name',
        ),
        migrations.AddField(
            model_name='complete',
            name='round_kind',
            field=models.IntegerField(blank=True, choices=[(1, 'Finals'), (2, 'Semi-Finals'), (3, 'Quarter-Finals')], null=True),
        ),
        migrations.AddField(
            model_name='complete',
            name='session_kind',
            field=models.IntegerField(blank=True, choices=[(32, 'Chorus'), (41, 'Quartet'), (42, 'Mixed')], null=True),
        ),
        migrations.AlterField(
            model_name='complete',
            name='category',
            field=models.IntegerField(blank=True, choices=[(30, 'Music'), (40, 'Performance'), (50, 'Singing')], null=True),
        ),
    ]
