# Generated by Django 2.1.8 on 2019-05-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_auto_20190507_0950'),
        ('keller', '0002_auto_20190507_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complete',
            name='panelist',
        ),
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='flat',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='score',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='selection',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='song',
        ),
        migrations.DeleteModel(
            name='Complete',
        ),
        migrations.DeleteModel(
            name='Flat',
        ),
        migrations.DeleteModel(
            name='Selection',
        ),
    ]
