# Generated by Django 2.1.8 on 2019-05-07 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_auto_20190507_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_grids', to='api.Round'),
        ),
        migrations.AlterField(
            model_name='grid',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_grids', to='api.Venue'),
        ),
    ]
