# Generated by Django 2.1.8 on 2019-05-08 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_auto_20190507_1647'),
        ('stage', '0002_auto_20190507_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grid',
            name='round',
        ),
        migrations.RemoveField(
            model_name='grid',
            name='venue',
        ),
        migrations.DeleteModel(
            name='Grid',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
