# Generated by Django 2.1.2 on 2018-10-08 13:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='points',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='selection',
            name='totals',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
