# Generated by Django 2.1.8 on 2019-05-13 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0007_auto_20190513_1349'),
        ('api', '0132_auto_20190507_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='bhs.Group'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='bhs.Person'),
        ),
        migrations.AlterField(
            model_name='award',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='bhs.Group'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The Winner of the Contest.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contests', to='bhs.Group'),
        ),
        migrations.AlterField(
            model_name='convention',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conventions', to='bhs.Group'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='bhs.Group'),
        ),
        migrations.AlterField(
            model_name='member',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_old', to='bhs.Group'),
        ),
        migrations.AlterField(
            model_name='member',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_old', to='bhs.Person'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers_old', to='bhs.Group'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers_old', to='api.Office'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers_old', to='bhs.Person'),
        ),
        migrations.AlterField(
            model_name='panelist',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panelists', to='bhs.Person'),
        ),
        migrations.AlterField(
            model_name='repertory',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repertories_old', to='bhs.Chart'),
        ),
        migrations.AlterField(
            model_name='repertory',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repertories_old', to='bhs.Group'),
        ),
        migrations.AlterField(
            model_name='song',
            name='chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='bhs.Chart'),
        ),
        migrations.AlterField(
            model_name='user',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='bhs.Person'),
        ),
    ]
