
# Generated by Django 2.1.8 on 2019-05-13 22:22

from django.db import migrations

def forward(apps, schema_editor):
    Person = apps.get_model('bhs.person')
    User = apps.get_model('api.user')

    items = User.objects.filter(person__isnull=False)
    for item in items:
        item.is_convention_manager = bool(
            item.person.officers.filter(
                office__in=[
                    100,
                    170,
                ],
                status__gt=0,
            )
        )
        item.is_session_manager = bool(
            item.person.officers.filter(
                office__in=[
                    100,
                    170,
                    210,
                ],
                status__gt=0,
            )
        )
        item.is_round_manager = bool(
            item.person.officers.filter(
                office__in=[
                    100,
                    170,
                    210,
                    220,
                    230,
                    270,
                ],
                status__gt=0,
            )
        )
        item.is_scoring_manager = bool(
            item.person.officers.filter(
                office__in=[
                    100,
                    170,
                    210,
                    220,
                    230,
                    270,
                ],
                status__gt=0,
            )
        )
        item.is_group_manager = bool(
            item.person.officers.filter(
                office__in=[
                    100,
                    170,
                    310,
                    320,
                    330,
                    340,
                    350,
                    410,
                ],
                status__gt=0,
            )
        )
        item.is_person_manager = bool(
            item.person.officers.filter(
                office__in=[
                    100,
                    170,
                ],
                status__gt=0,
            )
        )
        item.is_award_manager = bool(
            item.person.officers.filter(
                office__in=[
                    100,
                    170,
                ],
                status__gt=0,
            )
        )
        item.is_officer_manager = bool(
            item.person.officers.filter(
                office__in=[
                    100,
                    170,
                ],
                status__gt=0,
            )
        )
        item.is_chart_manager = bool(
            item.person.officers.filter(
                office__in=[
                    100,
                    160,
                    170,
                ],
                status__gt=0,
            )
        )
        item.is_assignment_manager = bool(
            item.person.officers.filter(
                office__in=[
                    100,
                    170,
                ],
                status__gt=0,
            )
        )
        item.save()



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_auto_20190513_1521'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
