# Generated by Django 2.1.2 on 2018-10-09 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_auto_20181008_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete',
            name='competitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Competitor'),
        ),
        migrations.AddField(
            model_name='complete',
            name='panelist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Panelist'),
        ),
        migrations.AddField(
            model_name='complete',
            name='panelist_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complete',
            name='song_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
