# Generated by Django 2.1.8 on 2019-05-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0135_auto_20190513_1522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chart',
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='group',
            name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='member',
            name='group',
        ),
        migrations.RemoveField(
            model_name='member',
            name='person',
        ),
        migrations.AlterUniqueTogether(
            name='officer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='officer',
            name='group',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='office',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='person',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterUniqueTogether(
            name='repertory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='repertory',
            name='chart',
        ),
        migrations.RemoveField(
            model_name='repertory',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
        migrations.DeleteModel(
            name='Officer',
        ),
        migrations.DeleteModel(
            name='Repertory',
        ),
    ]
