# Generated by Django 2.1.2 on 2018-10-09 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0136_complete_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Group'),
        ),
        migrations.AddField(
            model_name='complete',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Person'),
        ),
    ]
