# Generated by Django 2.1.2 on 2018-10-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0138_auto_20181009_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_mt',
            field=models.BooleanField(default=False, help_text='\n            Keep scores private.'),
        ),
    ]
