# Generated by Django 2.1.2 on 2018-10-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0140_auto_20181012_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='score',
        ),
    ]
