# Generated by Django 2.1.2 on 2018-10-12 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0141_remove_selection_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='song',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Song'),
        ),
    ]
