# Generated by Django 2.1.2 on 2018-10-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_auto_20181012_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='appearance',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='convention',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='round',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='session',
        ),
    ]
