# Generated by Django 2.1.2 on 2018-10-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_auto_20181012_1152'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='outcome',
            unique_together={('round', 'contest')},
        ),
    ]
