# Generated by Django 2.1.2 on 2018-10-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0145_auto_20181013_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='num',
            field=models.IntegerField(),
        ),
    ]
