# Generated by Django 2.1.2 on 2018-10-15 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0146_auto_20181014_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='competitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appearances', to='api.Competitor'),
        ),
    ]
