# Generated by Django 2.1.2 on 2018-10-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0147_auto_20181014_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='legacy_panelist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
