# Generated by Django 2.1.2 on 2018-10-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0148_score_legacy_panelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='num',
            field=models.IntegerField(),
        ),
    ]
