# Generated by Django 2.1.2 on 2018-10-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0149_auto_20181014_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complete',
            old_name='draw',
            new_name='appearance_num',
        ),
        migrations.RenameField(
            model_name='complete',
            old_name='judge',
            new_name='panelist_name',
        ),
        migrations.RenameField(
            model_name='complete',
            old_name='num',
            new_name='song_num',
        ),
        migrations.AddField(
            model_name='complete',
            name='mark',
            field=models.BooleanField(default=False),
        ),
    ]
