# Generated by Django 2.1.2 on 2018-10-16 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0151_auto_20181015_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='legacy_group',
            new_name='group_name',
        ),
    ]
