# Generated by Django 2.1.2 on 2018-10-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0153_flat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='single',
        ),
    ]
