# Generated by Django 2.1.2 on 2018-10-17 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0154_remove_flat_single'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelist',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panelists', to='api.Person'),
        ),
    ]
