# Generated by Django 2.1.2 on 2018-10-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0157_auto_20181017_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complete',
            name='appearance',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='competitor',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='convention',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='group',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='panelist',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='person',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='round',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='score',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='session',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='song',
        ),
        migrations.DeleteModel(
            name='Complete',
        ),
    ]
