# Generated by Django 2.1.2 on 2018-10-17 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0159_complete_flat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='convention',
            unique_together={('year', 'season', 'name', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='panelist',
            unique_together={('round', 'num'), ('round', 'legacy_name')},
        ),
    ]
