# Generated by Django 2.1.2 on 2018-10-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0160_auto_20181017_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete',
            name='panelist_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
