# Generated by Django 2.1.2 on 2018-10-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0161_auto_20181017_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='kind',
            field=models.IntegerField(choices=[(32, 'Chorus'), (41, 'Quartet'), (42, 'Mixed'), (43, 'Senior'), (44, 'Youth')], help_text='\n            The kind of session.  Generally this will be either quartet or chorus.\n        '),
        ),
    ]
