# Generated by Django 2.1.2 on 2018-10-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0162_auto_20181017_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='kind',
            field=models.IntegerField(choices=[(32, 'Chorus'), (41, 'Quartet'), (42, 'Mixed'), (43, 'Senior'), (44, 'Youth'), (45, 'Unknown')], help_text='\n            The kind of session.  Generally this will be either quartet or chorus.\n        '),
        ),
    ]
