# Generated by Django 2.1.2 on 2018-10-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0164_auto_20181018_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='session_kind',
            field=models.IntegerField(blank=True, choices=[(32, 'Chorus'), (41, 'Quartet'), (42, 'Mixed'), (43, 'Senior'), (44, 'Youth'), (45, 'Unknown')], null=True),
        ),
    ]
