# Generated by Django 2.1.2 on 2018-10-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0165_auto_20181018_0623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='name',
            new_name='convention_name',
        ),
        migrations.AddField(
            model_name='selection',
            name='event_raw',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='selection',
            name='season_kind',
            field=models.IntegerField(blank=True, choices=[(1, 'Summer'), (2, 'Midwinter'), (3, 'Fall'), (4, 'Spring'), (9, 'Video')], null=True),
        ),
        migrations.AddField(
            model_name='selection',
            name='session_raw',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='selection',
            name='season',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
