# Generated by Django 2.1.2 on 2018-10-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0167_auto_20181018_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complete',
            old_name='district',
            new_name='district_raw',
        ),
        migrations.RenameField(
            model_name='complete',
            old_name='season',
            new_name='season_raw',
        ),
        migrations.RenameField(
            model_name='selection',
            old_name='season',
            new_name='season_raw',
        ),
    ]
