# Generated by Django 2.1.2 on 2018-10-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0168_auto_20181018_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='season',
            field=models.IntegerField(choices=[(1, 'Summer'), (2, 'Midwinter'), (3, 'Fall'), (4, 'Spring')]),
        ),
        migrations.AlterField(
            model_name='convention',
            name='season',
            field=models.IntegerField(choices=[(1, 'Summer'), (2, 'Midwinter'), (3, 'Fall'), (4, 'Spring')]),
        ),
        migrations.AlterField(
            model_name='flat',
            name='season',
            field=models.IntegerField(blank=True, choices=[(1, 'Summer'), (2, 'Midwinter'), (3, 'Fall'), (4, 'Spring')], null=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='season_kind',
            field=models.IntegerField(blank=True, choices=[(1, 'Summer'), (2, 'Midwinter'), (3, 'Fall'), (4, 'Spring')], null=True),
        ),
    ]
