# Generated by Django 2.1.2 on 2018-10-18 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0169_auto_20181018_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='appearance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Appearance'),
        ),
        migrations.AddField(
            model_name='selection',
            name='convention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Convention'),
        ),
        migrations.AddField(
            model_name='selection',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Round'),
        ),
        migrations.AddField(
            model_name='selection',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Session'),
        ),
    ]
