# Generated by Django 2.1.2 on 2018-10-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0171_auto_20181018_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete',
            name='convention_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='complete',
            name='district_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='complete',
            name='round_kind',
            field=models.IntegerField(blank=True, choices=[(1, 'Finals'), (2, 'Semi-Finals'), (3, 'Quarter-Finals')], null=True),
        ),
        migrations.AddField(
            model_name='complete',
            name='season_kind',
            field=models.IntegerField(blank=True, choices=[(1, 'Summer'), (2, 'Midwinter'), (3, 'Fall'), (4, 'Spring')], null=True),
        ),
        migrations.AddField(
            model_name='complete',
            name='session_kind',
            field=models.IntegerField(blank=True, choices=[(32, 'Chorus'), (41, 'Quartet'), (42, 'Mixed'), (43, 'Senior'), (44, 'Youth'), (45, 'Unknown')], null=True),
        ),
    ]
