# Generated by Django 2.1.2 on 2018-10-20 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0175_auto_20181019_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='complete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections', to='api.Complete'),
        ),
        migrations.AlterField(
            model_name='complete',
            name='convention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completes', to='api.Convention'),
        ),
        migrations.AlterField(
            model_name='complete',
            name='panelist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completes', to='api.Panelist'),
        ),
        migrations.AlterField(
            model_name='complete',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completes', to='api.Round'),
        ),
        migrations.AlterField(
            model_name='complete',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completes', to='api.Session'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='appearance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections', to='api.Appearance'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='convention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections', to='api.Convention'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections', to='api.Round'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections', to='api.Session'),
        ),
    ]
