# Generated by Django 2.1.2 on 2018-10-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0176_auto_20181020_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='complete',
        ),
    ]
