# Generated by Django 2.1.2 on 2018-10-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0178_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='complete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='api.Complete'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='api.Selection'),
        ),
        migrations.AlterUniqueTogether(
            name='coin',
            unique_together={('selection', 'complete')},
        ),
    ]
