# Generated by Django 2.1.2 on 2018-10-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0179_auto_20181020_0838'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coin',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='coin',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='selection',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='convention_raw',
            new_name='convention_name',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='district',
            new_name='district_code',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='season',
            new_name='season_kind',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='competitor',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='round_raw',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='row',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='session_raw',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='single',
        ),
        migrations.AlterField(
            model_name='flat',
            name='session_kind',
            field=models.IntegerField(blank=True, choices=[(32, 'Chorus'), (41, 'Quartet'), (42, 'Mixed'), (43, 'Senior'), (44, 'Youth'), (45, 'Unknown'), (46, 'VLQ')], null=True),
        ),
        migrations.DeleteModel(
            name='Coin',
        ),
    ]
