# Generated by Django 2.1.2 on 2018-10-20 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0181_selection_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='complete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flats', to='api.Complete'),
        ),
        migrations.AddField(
            model_name='flat',
            name='selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flats', to='api.Selection'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='appearance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flats', to='api.Appearance'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='convention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flats', to='api.Convention'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flats', to='api.Group'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='panelist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flats', to='api.Panelist'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flats', to='api.Person'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flats', to='api.Round'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flats', to='api.Session'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flats', to='api.Song'),
        ),
    ]
