# Generated by Django 2.1.2 on 2018-10-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0182_auto_20181020_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='convention_name',
            new_name='complete_name',
        ),
        migrations.AddField(
            model_name='flat',
            name='selection_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
