# Generated by Django 2.1.2 on 2018-10-21 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0183_auto_20181020_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completes', to='api.Person'),
        ),
    ]
