# Generated by Django 2.1.2 on 2018-10-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0184_complete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='num_appearances',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selection',
            name='num_panelists',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selection',
            name='num_rounds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
