# Generated by Django 2.1.2 on 2018-10-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0186_auto_20181022_0521'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='complete',
            unique_together={('convention', 'session', 'round', 'panelist', 'person')},
        ),
    ]
