# Generated by Django 2.1.2 on 2018-10-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0187_auto_20181022_0522'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selection',
            unique_together={('convention', 'session', 'round', 'appearance', 'song')},
        ),
    ]
