# Generated by Django 2.1.2 on 2018-10-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0189_selection_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='appearance',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='appearance_num',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='category',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='complete_name',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='convention',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='district_code',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='group',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='panelist',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='panelist_name',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='panelist_num',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='person',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='round',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='round_kind',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='season_kind',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='selection_name',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='session',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='session_kind',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='song',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='song_num',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='song_title',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='year',
        ),
    ]
