# Generated by Django 2.1.2 on 2018-10-22 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0190_auto_20181022_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='points',
        ),
        migrations.AlterField(
            model_name='flat',
            name='complete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='api.Complete'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='api.Selection'),
        ),
    ]
