# Generated by Django 2.1.2 on 2018-10-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0192_selection_num_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete',
            name='num_sessions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
