# Generated by Django 2.1.2 on 2018-10-26 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0193_complete_num_sessions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together={('complete', 'selection', 'score')},
        ),
    ]
