# Generated by Django 2.1.2 on 2018-10-29 18:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0194_auto_20181025_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contender',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', django_fsm.FSMIntegerField(choices=[(0, 'New')], default=0, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.')),
                ('mus_points', models.IntegerField(blank=True, null=True)),
                ('per_points', models.IntegerField(blank=True, null=True)),
                ('sng_points', models.IntegerField(blank=True, null=True)),
                ('tot_points', models.IntegerField(blank=True, null=True)),
                ('mus_score', models.FloatField(blank=True, null=True)),
                ('per_score', models.FloatField(blank=True, null=True)),
                ('sng_score', models.FloatField(blank=True, null=True)),
                ('tot_score', models.FloatField(blank=True, null=True)),
                ('mus_rank', models.IntegerField(blank=True, null=True)),
                ('per_rank', models.IntegerField(blank=True, null=True)),
                ('sng_rank', models.IntegerField(blank=True, null=True)),
                ('tot_rank', models.IntegerField(blank=True, null=True)),
                ('appearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenders', to='api.Appearance')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenders', to='api.Round')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contender',
            unique_together={('appearance', 'round')},
        ),
    ]
