# Generated by Django 2.1.2 on 2018-10-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0195_auto_20181029_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='rounds',
            new_name='num_rounds',
        ),
    ]
