# Generated by Django 2.1.2 on 2018-10-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0197_auto_20181029_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contender',
            name='round',
        ),
    ]
