# Generated by Django 2.1.2 on 2018-10-29 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0198_remove_contender_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contender',
            name='outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenders', to='api.Outcome'),
        ),
    ]
