# Generated by Django 2.1.2 on 2018-11-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0199_auto_20181029_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='current_through',
            field=models.DateField(blank=True, null=True),
        ),
    ]
