# Generated by Django 2.1.3 on 2018-11-07 21:34

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0200_person_current_through'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='current_through',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=api.fields.LowerEmailField(max_length=100, null=True, unique=True),
        ),
    ]
