# Generated by Django 2.1.3 on 2018-11-07 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0201_auto_20181107_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bhs_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_through',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mc_pk',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
