# Generated by Django 2.1.3 on 2018-11-20 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0202_auto_20181107_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
