# Generated by Django 2.1.3 on 2018-11-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0204_auto_20181120_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='division',
        ),
        migrations.AlterField(
            model_name='group',
            name='kind',
            field=models.IntegerField(choices=[('International', [(1, 'International')]), ('District', [(11, 'District'), (12, 'Noncompetitive'), (13, 'Affiliate')]), ('Chapter', [(30, 'Chapter')]), ('Group', [(32, 'Chorus'), (41, 'Quartet')])], help_text='\n            The kind of group.\n        '),
        ),
        migrations.AlterField(
            model_name='office',
            name='kind',
            field=models.IntegerField(blank=True, choices=[('International', [(1, 'International')]), ('District', [(11, 'District'), (12, 'Noncompetitive'), (13, 'Affiliate')]), ('Group', [(32, 'Chapter'), (41, 'Quartet')])], help_text='\n            The kind of office.', null=True),
        ),
    ]
