# Generated by Django 2.1.3 on 2018-11-21 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0205_auto_20181120_1805'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grantor',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='grantor',
            name='convention',
        ),
        migrations.RemoveField(
            model_name='grantor',
            name='group',
        ),
        migrations.DeleteModel(
            name='Grantor',
        ),
    ]
