# Generated by Django 2.1.4 on 2018-12-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0207_auto_20181120_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='mc_pk',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='officer',
            unique_together=set(),
        ),
    ]
