
# Generated by Django 2.1.8 on 2019-05-17 17:29

from django.db import migrations

def forward(apps, schema_editor):
    StateLog = apps.get_model('django_fsm_log.statelog')
    logs = StateLog.objects.filter(
        content_type_id=8,
    )
    logs.update(content_type_id=69)

    logs = StateLog.objects.filter(
        content_type_id=9,
    )
    logs.update(content_type_id=70)

    logs = StateLog.objects.filter(
        content_type_id=13,
    )
    logs.update(content_type_id=71)

class Migration(migrations.Migration):

    dependencies = [
        ('cmanager', '0002_auto_20190517_1000'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
