# Generated by Django 2.1.9 on 2019-07-07 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmanager', '0002_auto_20190624_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='bhs.Group'),
        ),
        migrations.AlterField(
            model_name='convention',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions', to='bhs.Group'),
        ),
    ]
