# Generated by Django 2.2.3 on 2019-07-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmanager', '0003_auto_20190707_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='venue_name',
            field=models.CharField(default='(TBD)', help_text='\n            The venue name (when available).', max_length=255),
        ),
        migrations.AlterField(
            model_name='convention',
            name='location',
            field=models.CharField(default='(TBD)', help_text='\n            The general location in the form "City, State".', max_length=255),
        ),
    ]
