# Generated by Django 2.2.3 on 2019-07-08 04:23

from django.db import migrations

def forward(apps, schema_editor):
    Convention = apps.get_model('cmanager.convention')
    cs = Convention.objects.filter(
        venue__isnull=False,
    )
    for c in cs:
        c.venue_name = c.venue.name
        c.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cmanager', '0004_auto_20190707_2121'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
