# Generated by Django 2.2.3 on 2019-07-08 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmanager', '0005_auto_20190707_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convention',
            name='venue',
        ),
    ]
