# Generated by Django 2.2.3 on 2019-07-09 23:30

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmanager', '0006_remove_convention_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='scope_range',
            field=django.contrib.postgres.fields.ranges.DecimalRangeField(blank=True, null=True),
        ),
    ]
