# Generated by Django 2.2.3 on 2019-07-10 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmanager', '0007_auto_20190709_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='award',
            name='group_id_new',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convention',
            name='group_id_new',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
