# Generated by Django 2.2.3 on 2019-07-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmanager', '0008_auto_20190710_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
