# Generated by Django 2.1.8 on 2019-06-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmanager', '0008_auto_20190604_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='location',
            field=models.CharField(blank=True, default='', help_text='\n            The general location in the form "City, State".', max_length=255),
        ),
        migrations.AlterField(
            model_name='convention',
            name='name',
            field=models.CharField(default='Convention', max_length=255),
        ),
        migrations.AlterField(
            model_name='convention',
            name='venue',
            field=models.ForeignKey(blank=True, help_text='\n            The specific venue for the convention (if available.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions', to='stage.Venue'),
        ),
    ]
