# Generated by Django 2.2.3 on 2019-07-10 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmanager', '0008_auto_20190710_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='group_id_new',
        ),
        migrations.RemoveField(
            model_name='convention',
            name='group_id_new',
        ),
    ]
