# Generated by Django 2.2.3 on 2019-07-11 04:24

from django.db import migrations


def forward(apps, schema_editor):
    Assignment = apps.get_model('cmanager.assignment')
    Convention = apps.get_model('cmanager.convention')
    Award = apps.get_model('cmanager.award')

    ts = Assignment.objects.filter(
        person__user__isnull=False,
    )
    for t in ts:
        t.user = t.person.user
        t.save()

    cs = Convention.objects.filter(
        group__isnull=False,
    )
    for c in cs:
        c.district = c.group.code
        c.save()

    ws = Award.objects.filter(
        group__isnull=False,
    )
    for w in ws:
        w.district = w.group.code
        w.save()



class Migration(migrations.Migration):

    dependencies = [
        ('cmanager', '0009_award_district'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
