# Generated by Django 2.2.3 on 2019-07-10 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmanager', '0009_auto_20190710_1400'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='convention',
            unique_together=set(),
        ),
    ]
