# Generated by Django 2.2.3 on 2019-07-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmanager', '0010_auto_20190710_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='person',
        ),
        migrations.RemoveField(
            model_name='award',
            name='group',
        ),
        migrations.RemoveField(
            model_name='convention',
            name='group',
        ),
        migrations.AddField(
            model_name='assignment',
            name='person_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='group_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convention',
            name='group_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
