# Generated by Django 2.2.3 on 2019-07-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmanager', '0011_auto_20190710_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convention',
            name='legacy_complete',
        ),
        migrations.RemoveField(
            model_name='convention',
            name='legacy_name',
        ),
        migrations.RemoveField(
            model_name='convention',
            name='legacy_selection',
        ),
        migrations.RemoveField(
            model_name='convention',
            name='legacy_venue',
        ),
    ]
