# Generated by Django 2.2.3 on 2019-07-15 21:49

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('cmanager', '0012_auto_20190715_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (5, 'Built'), (10, 'Active')], default=0, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.'),
        ),
    ]
