# Generated by Django 2.2.3 on 2019-07-16 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmanager', '0013_auto_20190715_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='owners',
            field=models.ManyToManyField(related_name='conventions', to=settings.AUTH_USER_MODEL),
        ),
    ]
