# Generated by Django 2.2.3 on 2019-07-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmanager', '0015_auto_20190716_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='parent',
        ),
    ]
