# Generated by Django 2.2.3 on 2019-07-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmanager', '0016_remove_award_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Award',
        ),
    ]
