# Generated by Django 2.2.3 on 2019-07-19 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmanager', '0017_delete_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='convention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_old', to='cmanager.Convention'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_old', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='convention',
            name='owners',
            field=models.ManyToManyField(related_name='conventions_old', to=settings.AUTH_USER_MODEL),
        ),
    ]
