# Generated by Django 2.2.3 on 2019-07-19 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmanager', '0018_auto_20190719_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convention',
            name='owners',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Convention',
        ),
    ]
