# Generated by Django 2.2.5 on 2019-09-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjudication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='representing',
        ),
        migrations.RemoveField(
            model_name='panelist',
            name='representing',
        ),
        migrations.AlterField(
            model_name='panelist',
            name='district',
            field=models.CharField(blank=True, default='', help_text='\n            District', max_length=10),
        ),
    ]
