# Generated by Django 2.2.5 on 2019-09-17 15:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjudication', '0003_auto_20190917_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='image_id',
            field=models.CharField(blank=True, default='missing_image', max_length=255),
        ),
        migrations.AddField(
            model_name='round',
            name='registration',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='round',
            name='spots',
            field=models.IntegerField(default=10),
        ),
    ]
