# Generated by Django 2.2.5 on 2019-09-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjudication', '0004_auto_20190917_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelist',
            name='area',
            field=models.CharField(blank=True, default='', help_text='\n            District', max_length=10),
        ),
        migrations.AlterField(
            model_name='panelist',
            name='district',
            field=models.IntegerField(blank=True, choices=[(110, 'BHS'), (200, 'CAR'), (205, 'CSD'), (210, 'DIX'), (215, 'EVG'), (220, 'FWD'), (225, 'ILL'), (230, 'JAD'), (235, 'LOL'), (240, 'MAD'), (345, 'NED'), (350, 'NSC'), (355, 'ONT'), (360, 'PIO'), (365, 'RMD'), (370, 'SLD'), (375, 'SUN'), (380, 'SWD')], null=True),
        ),
    ]
