# Generated by Django 2.2.5 on 2019-09-20 23:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjudication', '0005_auto_20190918_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelist',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='panelists', to=settings.AUTH_USER_MODEL),
        ),
    ]
