# Generated by Django 2.2.5 on 2019-09-22 00:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjudication', '0006_auto_20190920_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='charts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
