# Generated by Django 2.2.5 on 2019-09-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjudication', '0007_auto_20190921_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='area',
            field=models.CharField(blank=True, default='', help_text='Area representing', max_length=255),
        ),
    ]
