# Generated by Django 2.2.5 on 2019-09-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjudication', '0008_appearance_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='image_id',
            field=models.CharField(blank=True, default='missing_image', help_text='\n            Image ID.', max_length=255),
        ),
    ]
