# Generated by Django 2.2.5 on 2019-09-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjudication', '0009_appearance_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='is_single',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
