# Generated by Django 2.2.20 on 2021-10-06 19:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjudication', '0014_auto_20211006_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='penalties',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(30, 'Repeating Substantial Portions of a Song (Article V.A.2)'), (32, 'Instrumental Accompaniment (Article IX.A.2.a)'), (34, 'Chorus Exceeding 4-Part Texture (Article IX.A.2.b)'), (36, 'Excessive Melody Not in Inner Part (Article IX.A.2.c)'), (38, 'Lack of Characteristic Chord Progression (Article IX.A.2.d)'), (39, 'Excessive Lyrics < 4 parts (Article IX.A.2.e)'), (40, 'Primarily Patriotic/Religious Intent (Article IX.A.3)'), (44, 'Not in Good Taste (Article IX.A.3.b)'), (48, 'Non-members Performing on Stage (Article XI.A.1)'), (50, 'Sound Equipment or Electronic Enhancement (Article X.B)')]), blank=True, default=list, size=None),
        ),
    ]
