# Generated by Django 2.2.27 on 2022-03-18 15:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adjudication', '0016_auto_20220225_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='round_stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
