# Generated by Django 2.2.27 on 2022-04-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjudication', '0020_auto_20220330_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='entry_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
