# Generated by Django 2.2.27 on 2022-04-07 15:15

from django.db import migrations

def get_entry_id(apps, session_id, group_id):
    Entry = apps.get_model('registration.entry')
    entry = Entry.objects.filter(
                group_id=group_id,
                session_id=session_id
            ).first()
    # if entry is None:
    #     raise ValueError("No entry for Group {0} in Session {1}".format(group_id, session_id))
    if entry is not None:
        return entry.id

def forward(apps, schema_editor):
    Appearance = apps.get_model('adjudication.appearance')

    for a in Appearance.objects.select_related(
            'round'
        ):

        entry_id = get_entry_id(apps, a.round.session_id, a.group_id)

        if entry_id:
            a.entry_id = entry_id
            a.save()

class Migration(migrations.Migration):

    dependencies = [
        ('adjudication', '0021_appearance_entry_id'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
