# Generated by Django 2.2.27 on 2022-05-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjudication', '0024_auto_20220530_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='printed',
            field=models.BooleanField(default=True, help_text='\n            Show this outcome on the OSS.'),
        ),
    ]
