# Generated by Django 2.2.27 on 2022-08-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjudication', '0026_auto_20220814_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='tree_sort',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
