# Generated by Django 2.2.27 on 2022-10-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjudication', '0028_outcome_print_on_finals_oss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='print_on_finals_oss',
            field=models.BooleanField(default=False, help_text='\n            Show this outcome on the Finals OSS.', verbose_name='Include on Finals OSS'),
        ),
    ]
