# Generated by Django 2.2.27 on 2023-04-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjudication', '0030_auto_20230225_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='revision_date',
            field=models.DateField(blank=True, help_text='\n            Date of this revision.\n        ', null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='revision_number',
            field=models.IntegerField(blank=True, default='0', help_text='\n            Manually updated when revisions are made.\n        '),
        ),
        migrations.AddField(
            model_name='round',
            name='revision_reason',
            field=models.CharField(blank=True, help_text='\n            Describe the reason for the revision.\n        ', max_length=255),
        ),
    ]
