# Generated by Django 2.2.3 on 2019-07-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='group_bhs_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='group_tree_sort',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
