# Generated by Django 2.2.3 on 2019-07-23 17:25

import apps.smanager.fields
import cloudinary_storage.storage
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='group_bhs_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='group_chapter',
            field=models.TextField(blank=True, default='', help_text='\n            The denormalized chapter group.', max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='group_charts',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='entry',
            name='group_code',
            field=models.CharField(blank=True, default='', help_text='\n            Short-form code.', max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='group_description',
            field=models.TextField(blank=True, default='', help_text='\n            A description of the group.  Max 1000 characters.', max_length=1000),
        ),
        migrations.AddField(
            model_name='entry',
            name='group_district',
            field=models.TextField(blank=True, default='', help_text='\n            The denormalized district group.', max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='group_division',
            field=models.IntegerField(blank=True, choices=[('EVG', [(10, 'EVG Division I'), (20, 'EVG Division II'), (30, 'EVG Division III'), (40, 'EVG Division IV'), (50, 'EVG Division V')]), ('FWD', [(60, 'FWD Arizona'), (70, 'FWD Northeast'), (80, 'FWD Northwest'), (90, 'FWD Southeast'), (100, 'FWD Southwest')]), ('LOL', [(110, 'LOL 10000 Lakes'), (120, 'LOL Division One'), (130, 'LOL Northern Plains'), (140, 'LOL Packerland'), (150, 'LOL Southwest')]), ('MAD', [(170, 'MAD Central'), (180, 'MAD Northern'), (190, 'MAD Southern')]), ('NED', [(210, 'NED Granite and Pine'), (220, 'NED Mountain'), (230, 'NED Patriot'), (240, 'NED Sunrise'), (250, 'NED Yankee')]), ('SWD', [(260, 'SWD Northeast'), (270, 'SWD Northwest'), (280, 'SWD Southeast'), (290, 'SWD Southwest')])], null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='group_gender',
            field=models.IntegerField(blank=True, choices=[(10, 'Male'), (20, 'Female'), (30, 'Mixed')], help_text='\n            The gender of group.\n        ', null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='group_international',
            field=models.TextField(blank=True, default='', help_text='\n            The denormalized international group.', max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='group_is_divided',
            field=models.BooleanField(default=False, help_text='This district has divisions.'),
        ),
        migrations.AddField(
            model_name='entry',
            name='group_is_senior',
            field=models.BooleanField(default=False, help_text='Qualifies as a Senior Group.  This can be set manually, but is denormlized nightly for quartets.'),
        ),
        migrations.AddField(
            model_name='entry',
            name='group_is_youth',
            field=models.BooleanField(default=False, help_text='Qualifies as a Youth Group.  Must be set manually.'),
        ),
        migrations.AddField(
            model_name='entry',
            name='group_kind',
            field=models.IntegerField(blank=True, choices=[('International', [(1, 'International')]), ('District', [(11, 'District'), (12, 'Noncompetitive'), (13, 'Affiliate')]), ('Chapter', [(30, 'Chapter')]), ('Group', [(32, 'Chorus'), (41, 'Quartet'), (46, 'VLQ')])], help_text='\n            The kind of group.\n        ', null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='group_name',
            field=models.CharField(blank=True, default='', help_text='\n            The name of the resource.\n        ', max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='group_nomen',
            field=models.CharField(blank=True, default='', help_text='\n            The combined name of the resource.\n        ', max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='group_participants',
            field=models.CharField(blank=True, default='', help_text='Director(s) or Members (listed TLBB)', max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='group_status',
            field=django_fsm.FSMIntegerField(blank=True, choices=[(-10, 'Inactive'), (-5, 'AIC'), (0, 'New'), (10, 'Active')], help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.', null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='group_tree_sort',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.smanager.fields.UploadPath('image')),
        ),
        migrations.AlterField(
            model_name='convention',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.smanager.fields.UploadPath('image')),
        ),
        migrations.AlterField(
            model_name='session',
            name='drcj_report',
            field=models.FileField(blank=True, default='', storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=apps.smanager.fields.UploadPath('drcj_report')),
        ),
        migrations.AlterField(
            model_name='session',
            name='legacy_report',
            field=models.FileField(blank=True, default='', storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=apps.smanager.fields.UploadPath('legacy_report')),
        ),
    ]
