# Generated by Django 2.1.9 on 2019-07-07 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='award',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contests', to='cmanager.Award'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='bhs.Group'),
        ),
        migrations.AlterField(
            model_name='session',
            name='convention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cmanager.Convention'),
        ),
    ]
