# Generated by Django 2.2.3 on 2019-07-30 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0002_assignment_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='award_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='award_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='award_district',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='award_division',
            new_name='division',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='award_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='award_is_novice',
            new_name='is_novice',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='award_kind',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='award_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='award_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='award_scope',
            new_name='scope',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='award_scope_range',
            new_name='scope_range',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='award_season',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='award_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='award_size_range',
            new_name='size_range',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='award_tree_sort',
            new_name='tree_sort',
        ),
    ]
