# Generated by Django 2.2.3 on 2019-07-10 21:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smanager', '0002_auto_20190707_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='owners',
            field=models.ManyToManyField(related_name='entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='owners',
            field=models.ManyToManyField(related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
