# Generated by Django 2.2.3 on 2019-07-24 15:13

from django.db import migrations

def forward(apps, schema_editor):
    Entry = apps.get_model('smanager.entry')

    es = Entry.objects.all()
    for e in es:
        ts = e.contestants.filter(
            status__gt=0,
        )
        for t in ts:
            e.contests.add(t.contest)


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0003_entry_contests'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
