# Generated by Django 2.2.3 on 2019-07-11 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0003_auto_20190710_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='group',
        ),
    ]
