# Generated by Django 2.2.3 on 2019-07-30 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0003_auto_20190729_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='representing',
            new_name='district',
        ),
    ]
