# Generated by Django 2.2.3 on 2019-07-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0004_auto_20190724_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='chapters',
            field=models.CharField(blank=True, default='', help_text='The Chapter(s) that the comprise the group members.', max_length=255),
        ),
    ]
