# Generated by Django 2.2.3 on 2019-07-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0004_remove_contest_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestant',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='contest',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='contestant',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set(),
        ),
    ]
