# Generated by Django 2.2.3 on 2019-07-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0004_auto_20190729_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='group_bhs_id',
            new_name='bhs_id',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='group_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='group_division',
            new_name='division',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='group_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='group_kind',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='group_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='group_chapter',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='group_charts',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='group_description',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='group_district',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='group_international',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='group_is_divided',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='group_nomen',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='group_participants',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='group_status',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='group_tree_sort',
        ),
        migrations.AddField(
            model_name='entry',
            name='district',
            field=models.IntegerField(blank=True, choices=[(110, 'BHS'), (200, 'CAR'), (205, 'CSD'), (210, 'DIX'), (215, 'EVG'), (220, 'FWD'), (225, 'ILL'), (230, 'JAD'), (235, 'LOL'), (240, 'MAD'), (345, 'NED'), (350, 'NSC'), (355, 'ONT'), (360, 'PIO'), (365, 'RMD'), (370, 'SLD'), (375, 'SUN'), (380, 'SWD')], null=True),
        ),
    ]
