# Generated by Django 2.2.3 on 2019-07-10 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smanager', '0004_entry_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='owner',
        ),
        migrations.AddField(
            model_name='session',
            name='owners',
            field=models.ManyToManyField(related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
