# Generated by Django 2.2.3 on 2019-07-24 19:23

from django.db import migrations

def forward(apps, schema_editor):
    Entry = apps.get_model('smanager.entry')
    Group = apps.get_model('bhs.group')

    es = Entry.objects.filter(group_id__isnull=False)
    for e in es:
        g = Group.objects.get(id=e.group_id)
        e.chapters = g.chapter
        e.save()

class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0005_entry_chapters'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
