# Generated by Django 2.2.3 on 2019-07-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0005_auto_20190730_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='group_is_senior',
            new_name='is_senior',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='group_is_youth',
            new_name='is_youth',
        ),
    ]
