# Generated by Django 2.2.3 on 2019-07-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0005_auto_20190712_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='group',
        ),
        migrations.AddField(
            model_name='entry',
            name='group_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
