# Generated by Django 2.2.3 on 2019-07-10 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smanager', '0005_auto_20190710_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='owner',
        ),
        migrations.AddField(
            model_name='entry',
            name='owners',
            field=models.ManyToManyField(related_name='entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
