# Generated by Django 2.2.3 on 2019-07-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0006_auto_20190730_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_single',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
