# Generated by Django 2.2.3 on 2019-07-25 01:34

import apps.smanager.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0006_auto_20190724_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='airports',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=3), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='assignment',
            name='bhs_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='cell_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='\n            The cell phone number of the resource.  Include country code.', max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='assignment',
            name='common_name',
            field=models.CharField(blank=True, default='', help_text='\n            The prefix of the person.', max_length=255),
        ),
        migrations.AddField(
            model_name='assignment',
            name='district',
            field=models.CharField(blank=True, default='', help_text='\n            District', max_length=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='email',
            field=apps.smanager.fields.LowerEmailField(blank=True, help_text='\n            The contact email of the resource.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='first_name',
            field=models.CharField(blank=True, default='', help_text='\n            The first name of the person.', max_length=255),
        ),
        migrations.AddField(
            model_name='assignment',
            name='home_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='\n            The home phone number of the resource.  Include country code.', max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='assignment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.smanager.fields.UploadPath('image')),
        ),
        migrations.AddField(
            model_name='assignment',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text='\n            The last name of the person.', max_length=255),
        ),
        migrations.AddField(
            model_name='assignment',
            name='middle_name',
            field=models.CharField(blank=True, default='', help_text='\n            The middle name of the person.', max_length=255),
        ),
        migrations.AddField(
            model_name='assignment',
            name='nick_name',
            field=models.CharField(blank=True, default='', help_text='\n            The nickname of the person.', max_length=255),
        ),
        migrations.AddField(
            model_name='assignment',
            name='work_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='\n            The work phone number of the resource.  Include country code.', max_length=128, null=True, region=None),
        ),
    ]
