# Generated by Django 2.2.3 on 2019-07-25 04:12

from django.db import migrations

def forward(apps, schema_editor):
    Session = apps.get_model('smanager.session')

    ss = Session.objects.filter(convention__status__gt=0)
    for s in ss:
        s.convention.owners.set(s.owners.all())


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0007_auto_20190724_1834'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
