# Generated by Django 2.2.3 on 2019-07-30 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0007_contest_is_single'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='repertory',
            name='status',
        ),
    ]
