# Generated by Django 2.2.3 on 2019-07-15 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0008_auto_20190713_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='is_primary',
        ),
    ]
