# Generated by Django 2.2.3 on 2019-07-31 00:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0008_auto_20190730_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='group_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None),
        ),
    ]
