# Generated by Django 2.2.3 on 2019-07-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0008_auto_20190724_2112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contestant',
        ),
    ]
