# Generated by Django 2.2.3 on 2019-07-31 01:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0009_session_group_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='group_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None),
        ),
    ]
