# Generated by Django 2.2.3 on 2019-07-31 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0010_auto_20190730_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='kind',
            field=models.IntegerField(blank=True, choices=[(32, 'Chorus'), (41, 'Quartet'), (46, 'VLQ')], help_text='\n            The kind of group.\n        ', null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='owners',
            field=models.ManyToManyField(blank=True, null=True, related_name='entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
