# Generated by Django 2.2.3 on 2019-07-28 15:05

from django.db import migrations

def forward(apps, schema_editor):
    Previous = apps.get_model('bhs.repertory')
    New = apps.get_model('smanager.repertory')
    Entry = apps.get_model('smanager.entry')

    ps = Previous.objects.all()
    for p in ps:
        entries = Entry.objects.filter(
            group_id=p.group_id,
        )
        for entry in entries:
            New.objects.create(
                status=p.status,
                title=p.chart.title,
                arrangers=p.chart.arrangers,
                chart_id=p.chart_id,
                entry=entry,
            )

class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0010_repertory'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
