# Generated by Django 2.2.3 on 2019-07-16 15:42

from django.db import migrations

def forward(apps, schema_editor):
    Session = apps.get_model('smanager.session')
    User = apps.get_model('rest_framework_jwt.user')

    sessions = Session.objects.all()

    for session in sessions:
        pks = [
            'a88991ba-20f0-4948-a713-811d8b5dcd8a',
            '88b20557-f13e-42e4-8037-ac930d9e6362',
            '8b916eae-e3dd-4bdf-9a39-85773b97f421',
        ]
        us = User.objects.filter(
            id__in=pks,
        )
        for u in us:
            session.owners.add(u)

class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0010_remove_contest_result'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
