# Generated by Django 2.2.3 on 2019-07-31 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0011_auto_20190731_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
