# Generated by Django 2.2.3 on 2019-07-28 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0011_auto_20190728_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='smanager.Session'),
        ),
    ]
