# Generated by Django 2.2.3 on 2019-07-28 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0012_assignment_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='convention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='smanager.Convention'),
        ),
    ]
