# Generated by Django 2.2.3 on 2019-07-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0013_auto_20190719_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='award_tree_sort',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
