# Generated by Django 2.2.3 on 2019-07-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0013_auto_20190728_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='common_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='district',
            new_name='representing',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='home_phone',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='nick_name',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='work_phone',
        ),
    ]
