# Generated by Django 2.2.3 on 2019-07-28 15:45

from django.db import migrations

def forward(apps, schema_editor):
    Assignment = apps.get_model('smanager.assignment')
    ms = Assignment.objects.all()
    for m in ms:
        ss = m.convention.sessions.all()
        for s in ss:
            new = Assignment(
                status=m.status,
                kind=m.kind,
                category=m.category,
                person_id=m.person_id,
                name=m.name,
                first_name=m.first_name,
                last_name=m.last_name,
                bhs_id=m.bhs_id,
                representing=m.representing,
                email=m.email,
                cell_phone=m.cell_phone,
                airports=m.airports,
                session=s,
            )
            new.image.name = m.image.name
            new.save()


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0014_auto_20190728_0845'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
