# Generated by Django 2.2.3 on 2019-07-19 16:39

from django.db import migrations

def forward(apps, schema_editor):
    Award = apps.get_model('bhs.award')
    Contest = apps.get_model('smanager.contest')

    awards = Award.objects.all()

    for award in awards:
        contests = Contest.objects.filter(award_id=award.id)
        for contest in contests:
            contest.award_age = award.age
            contest.award_description = award.description
            contest.award_district = award.district
            contest.award_division = award.division
            contest.award_gender = award.gender
            contest.award_is_novice = award.is_novice
            contest.award_kind = award.kind
            contest.award_level = award.level
            contest.award_name = award.name
            contest.award_scope = award.scope
            contest.award_scope_range = award.scope_range
            contest.award_season = award.season
            contest.award_size = award.size
            contest.award_size_range = award.size_range
            contest.award_tree_sort = award.tree_sort
            contest.save()



class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0014_auto_20190719_0939'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
