# Generated by Django 2.2.3 on 2019-07-28 15:48

from django.db import migrations

def forward(apps, schema_editor):
    Assignment = apps.get_model('smanager.assignment')
    ms = Assignment.objects.filter(
        convention__isnull=False,
    )
    ms.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0015_auto_20190728_0845'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
