# Generated by Django 2.2.3 on 2019-07-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0016_auto_20190728_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='convention',
        ),
    ]
