# Generated by Django 2.2.3 on 2019-07-19 18:20

from django.db import migrations

def forward(apps, schema_editor):
    Old = apps.get_model('cmanager.convention')
    New = apps.get_model('smanager.convention')

    olds = Old.objects.values()
    for old in olds:
        New.objects.create(**old)

    Old = apps.get_model('cmanager.assignment')
    New = apps.get_model('smanager.assignment')

    olds = Old.objects.values()
    for old in olds:
        New.objects.create(**old)



class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0016_assignment_convention'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
