# Generated by Django 2.2.3 on 2019-07-19 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0017_auto_20190719_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='convention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='smanager.Convention'),
        ),
    ]
