# Generated by Django 2.2.3 on 2019-07-28 16:38

from django.db import migrations

def forward(apps, schema_editor):
    Session = apps.get_model('smanager.session')
    ss = Session.objects.filter(
        convention__isnull=False,
    )

    REPRESENTING = {
        'BHS': 110,
        'CAR': 200,
        'CSD': 205,
        'DIX': 210,
        'EVG': 215,
        'FWD': 220,
        'ILL': 225,
        'JAD': 230,
        'LOL': 235,
        'MAD': 240,
        'NED': 345,
        'NSC': 350,
        'ONT': 355,
        'PIO': 360,
        'RMD': 365,
        'SLD': 370,
        'SUN': 375,
        'SWD': 380,
    }





    for s in ss:
        representing = REPRESENTING.get(s.convention.district)

        s.name = s.convention.name
        s.representing = representing
        s.season = s.convention.season
        s.panel = s.convention.panel
        s.year = s.convention.year
        s.open_date = s.convention.open_date
        s.close_date = s.convention.close_date
        s.start_date = s.convention.start_date
        s.end_date = s.convention.end_date
        s.venue_name = s.convention.venue_name
        s.location = s.convention.location
        s.timezone = s.convention.timezone
        s.image.name = s.convention.image.name
        s.divisions = s.convention.divisions
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0018_auto_20190728_0938'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
