# Generated by Django 2.2.3 on 2019-07-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0020_auto_20190728_1028'),
    ]

    database_operations = [
        migrations.AlterField(
            model_name='session',
            name='convention',
            field=models.ForeignKey('Convention', db_constraint=False, db_index=True, null=False, on_delete=models.SET_NULL)
        ),
    ]
    state_operations = [
        migrations.AlterField(
            model_name='session',
            name='convention',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='session',
            old_name='convention',
            new_name='convention_id'
        ),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        )
    ]
