# Generated by Django 2.2.3 on 2019-07-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0021_auto_20190728_1041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Convention',
        ),
    ]
