# Generated by Django 2.2.3 on 2019-07-29 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0022_delete_convention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='user',
        ),
    ]
