# Generated by Django 2.1.7 on 2019-03-15 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='primary_voice_part',
            new_name='part',
        ),
    ]
