# Generated by Django 2.1.7 on 2019-03-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0002_auto_20190315_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bhs_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
