# Generated by Django 2.1.7 on 2019-03-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0003_auto_20190315_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
