# Generated by Django 2.1.7 on 2019-03-15 19:50

import django.core.validators
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0004_auto_20190315_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bhs_id',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='person',
            name='mon',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-20, 'Expelled'), (-10, 'Suspended'), (0, 'New'), (10, 'Active')], default=0),
        ),
    ]
