# Generated by Django 2.1.7 on 2019-03-15 20:11

from django.db import migrations, models
import mem.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0005_auto_20190315_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bhs_id',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[mem.validators.validate_bhs_id]),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[mem.validators.validate_bhs_id]),
        ),
    ]
