# Generated by Django 2.1.7 on 2019-03-15 20:13

from django.db import migrations, models
import mem.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0006_auto_20190315_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[mem.validators.validate_birth_date]),
        ),
    ]
