# Generated by Django 2.1.8 on 2019-04-23 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0009_auto_20190423_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='deleted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('/[\\p{L}]/ui', message='\n        Must not use punctuation.\n    ')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('/[\\p{L}]/ui', message='\n        Must not use punctuation.\n    ')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=255, validators=[django.core.validators.RegexValidator('/[\\p{L}]/ui', message='\n        Must not use punctuation.\n    ')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='nick_name',
            field=models.CharField(blank=True, default='', max_length=255, validators=[django.core.validators.RegexValidator('/[\\p{L}]/ui', message='\n        Must not use punctuation.\n    ')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='prefix',
            field=models.CharField(blank=True, default='', max_length=255, validators=[django.core.validators.RegexValidator('/[\\p{L}]/ui', message='\n        Must not use punctuation.\n    ')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='suffix',
            field=models.CharField(blank=True, default='', max_length=255, validators=[django.core.validators.RegexValidator('/[\\p{L}]/ui', message='\n        Must not use punctuation.\n    ')]),
        ),
    ]
