# Generated by Django 2.1.8 on 2019-04-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0010_auto_20190423_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='established_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
