# Generated by Django 2.1.8 on 2019-04-23 22:45

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0011_group_established_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='email',
            field=api.fields.LowerEmailField(blank=True, help_text='\n            The contact email of the resource.', max_length=254, null=True),
        ),
    ]
