# Generated by Django 2.1.8 on 2019-04-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0013_auto_20190424_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='inactive',
            field=models.IntegerField(blank=True, choices=[(10, 'Non-Renewal'), (20, 'Renewed'), (30, 'Not Cancelled'), (40, 'Non-Payment'), (50, 'Expired'), (60, 'Deceased'), (70, 'Changed Option'), (80, 'Other'), (90, 'Cancelled'), (100, 'Transferred'), (110, 'Swapped Chapter'), (120, 'Swapped')], null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
