# Generated by Django 2.1.8 on 2019-04-24 19:04

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0015_auto_20190424_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='code',
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=0),
        ),
    ]
