# Generated by Django 2.1.8 on 2019-04-26 14:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import mem.fields
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0016_auto_20190424_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=0, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.')),
                ('office', models.IntegerField(choices=[(310, 'Chapter President'), (320, 'Chapter Secretary'), (320, 'Chorus Director'), (340, 'Chorus Associate or Assistant Director'), (350, 'Chorus Manager'), (410, 'Quartet Admin')], null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stream',
            name='group',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='person',
        ),
        migrations.AlterField(
            model_name='group',
            name='email',
            field=mem.fields.LowerEmailField(blank=True, help_text='\n            The contact email of the resource.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Active'), (-5, 'AIC'), (0, 'New'), (10, 'Active')], default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=mem.fields.LowerEmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Stream',
        ),
        migrations.AddField(
            model_name='officer',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='mem.Group'),
        ),
        migrations.AddField(
            model_name='officer',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='mem.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='officer',
            unique_together={('group', 'person', 'office')},
        ),
    ]
