# Generated by Django 2.1.8 on 2019-05-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='office',
            field=models.IntegerField(choices=[('International', [(100, 'SCJC Chair'), (110, 'SCJC Chair Past'), (120, 'SCJC CA'), (130, 'SCJC MUS'), (140, 'SCJC PER'), (150, 'SCJC SNG'), (160, 'SCJC Chart'), (170, 'SCJC Admin'), (230, 'JUDGE CA'), (240, 'JUDGE MUS'), (250, 'JUDGE PER'), (260, 'JUDGE SNG'), (270, 'CANDIDATE CA'), (280, 'CANDIDATE MUS'), (290, 'CANDIDATE PER'), (295, 'CANDIDATE SNG')]), ('District', [(210, 'DRCJ'), (220, 'DRCJ Assistant')]), ('Chapter', [(310, 'CPRES'), (320, 'CSEC')]), ('Chorus', [(330, 'KDIR'), (340, 'KASS'), (350, 'KMAN')]), ('Quartet', [(410, 'QADM')])]),
        ),
    ]
