# Generated by Django 2.1.2 on 2018-11-09 17:04

from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flatmembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=0, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flatmemberships', to='bhs.Human')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flatmemberships', to='bhs.Structure')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='flatmembership',
            unique_together={('structure', 'human')},
        ),
    ]
