# Generated by Django 2.1.4 on 2018-12-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(editable=False, max_length=255)),
                ('middle_name', models.CharField(db_column='middle_initial', editable=False, max_length=255)),
                ('last_name', models.CharField(editable=False, max_length=255)),
                ('nick_name', models.CharField(db_column='preferred_name', editable=False, max_length=255)),
                ('email', models.CharField(db_column='username', editable=False, max_length=255, unique=True)),
                ('birth_date', models.DateField(db_column='birthday', editable=False, null=True)),
                ('is_deceased', models.BooleanField(editable=False)),
                ('phone', models.CharField(editable=False, max_length=255)),
                ('cell_phone', models.CharField(editable=False, max_length=255)),
                ('work_phone', models.CharField(editable=False, max_length=255)),
                ('bhs_id', models.IntegerField(db_column='legacy_id', editable=False, unique=True)),
                ('sex', models.CharField(editable=False, max_length=255)),
                ('primary_voice_part', models.CharField(editable=False, max_length=255)),
                ('created', models.DateTimeField(db_column='created', editable=False)),
                ('modified', models.DateTimeField(db_column='updated', editable=False, null=True)),
            ],
            options={
                'db_table': 'vwMembers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('status', models.BooleanField(editable=False)),
                ('paid', models.BooleanField(editable=False)),
                ('vocal_part', models.CharField(editable=False, max_length=255)),
                ('established_date', models.DateField(db_column='created', editable=False)),
                ('inactive_date', models.DateField(db_column='inactive', editable=False, null=True)),
                ('inactive_reason', models.CharField(db_column='inactive_reason', editable=False, max_length=255)),
                ('created', models.DateTimeField(db_column='created_on', editable=False)),
                ('modified', models.DateTimeField(db_column='modified', editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Join',
                'verbose_name_plural': 'Joins',
                'db_table': 'vwSubscriptions_Memberships',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=255)),
                ('created', models.DateTimeField(db_column='created', editable=False)),
                ('modified', models.DateTimeField(db_column='modified', editable=False)),
            ],
            options={
                'db_table': 'vwMemberships',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=255)),
                ('abbv', models.CharField(editable=False, max_length=255)),
                ('officer_roles_id', models.CharField(editable=False, max_length=255)),
                ('start_date', models.DateField(editable=False, null=True)),
                ('end_date', models.DateField(editable=False, null=True)),
                ('created', models.DateTimeField(db_column='created', editable=False)),
                ('modified', models.DateTimeField(db_column='updated', editable=False, null=True)),
            ],
            options={
                'db_table': 'vwOfficers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'statuses',
                'db_table': 'vwStatuses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=255)),
                ('kind', models.CharField(choices=[('organization', 'Organization'), ('district', 'District'), ('group', 'Group'), ('chapter', 'Chapter'), ('quartet', 'Quartet')], db_column='object_type', editable=False, max_length=255)),
                ('category', models.CharField(editable=False, max_length=255)),
                ('bhs_id', models.IntegerField(db_column='legacy_id', editable=False, unique=True)),
                ('chapter_code', models.CharField(db_column='legacy_code', editable=False, max_length=255)),
                ('chorus_name', models.CharField(editable=False, max_length=255)),
                ('preferred_name', models.CharField(editable=False, max_length=255)),
                ('phone', models.CharField(editable=False, max_length=255)),
                ('email', models.CharField(editable=False, max_length=255)),
                ('website', models.CharField(editable=False, max_length=255)),
                ('facebook', models.CharField(editable=False, max_length=255)),
                ('twitter', models.CharField(editable=False, max_length=255)),
                ('established_date', models.DateField(editable=False)),
                ('created', models.DateTimeField(db_column='created', editable=False)),
                ('modified', models.DateTimeField(db_column='updated', editable=False)),
            ],
            options={
                'db_table': 'vwStructures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('current_through', models.DateField(db_column='valid_through', editable=False, null=True)),
                ('status', models.CharField(editable=False, max_length=255)),
                ('items_editable', models.BooleanField(editable=False)),
                ('created', models.DateTimeField(db_column='created', editable=False)),
                ('modified', models.DateTimeField(db_column='updated', editable=False, null=True)),
            ],
            options={
                'db_table': 'vwSubscriptions',
                'managed': False,
            },
        ),
    ]
