# Generated by Django 2.1.8 on 2019-05-11 16:01

from django.db import migrations

def forward(apps, schema_editor):
    Old = apps.get_model('api.person')
    New = apps.get_model('bhs.person')

    items = Old.objects.values()
    for item in items:
        New.objects.create(**item)

    Old = apps.get_model('api.group')
    New = apps.get_model('bhs.group')

    items = Old.objects.values()
    for item in items:
        New.objects.create(**item)

    Old = apps.get_model('api.member')
    New = apps.get_model('bhs.member')

    items = Old.objects.values()
    for item in items:
        New.objects.create(**item)

    Old = apps.get_model('api.officer')
    New = apps.get_model('bhs.officer')

    items = Old.objects.values(
        'id',
        'status',
        'start_date',
        'end_date',
        'mc_pk',
        'person_id',
        'group_id',
        'office__code',
    )
    for item in items:
        item['office'] = item.pop('office__code')
    for item in items:
        New.objects.create(**item)



class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0006_auto_20190511_0839'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
