# Generated by Django 2.1.8 on 2019-05-11 16:12

from django.db import migrations

def forward(apps, schema_editor):
    StateLog = apps.get_model('django_fsm_log.statelog')

    logs = StateLog.objects.filter(
        content_type_id=31
    )
    logs.update(content_type_id=36)

    logs = StateLog.objects.filter(
        content_type_id=19
    )
    logs.update(content_type_id=35)

    logs = StateLog.objects.filter(
        content_type_id=16
    )
    logs.update(content_type_id=60)

    logs = StateLog.objects.filter(
        content_type_id=18
    )
    logs.update(content_type_id=61)

class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0007_auto_20190511_0901'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
