# Generated by Django 2.1.8 on 2019-05-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0007_auto_20190513_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['tree_sort'], 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='officer',
            options={'verbose_name_plural': 'Officers'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'Persons'},
        ),
    ]
