# Generated by Django 2.1.8 on 2019-05-13 05:47

import bhs.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0008_auto_20190511_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', django_fsm.FSMIntegerField(choices=[(-20, 'Protected'), (-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=0, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.')),
                ('title', models.CharField(max_length=255)),
                ('arrangers', models.CharField(max_length=255)),
                ('composers', models.CharField(max_length=255)),
                ('lyricists', models.CharField(max_length=255)),
                ('holders', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, help_text="\n            Fun or interesting facts to share about the chart (ie, 'from Disney's Lion King, first sung by Elton John'.)", max_length=1000)),
                ('notes', models.TextField(blank=True, help_text='\n            Private Notes (for internal use only).')),
                ('image', models.ImageField(blank=True, null=True, upload_to=bhs.fields.ImageUploadPath())),
            ],
        ),
        migrations.CreateModel(
            name='Repertory',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=10, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repertories', to='bhs.Chart')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repertories', to='bhs.Group')),
            ],
            options={
                'verbose_name_plural': 'repertories',
            },
        ),
        migrations.AlterUniqueTogether(
            name='chart',
            unique_together={('title', 'arrangers')},
        ),
        migrations.AlterUniqueTogether(
            name='repertory',
            unique_together={('group', 'chart')},
        ),
    ]
