# Generated by Django 2.1.8 on 2019-05-11 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0008_auto_20190511_0912'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='officer',
            unique_together={('group', 'person', 'office')},
        ),
    ]
