# Generated by Django 2.1.8 on 2019-05-16 17:08

from django.db import migrations

def forward(apps, schema_editor):
    Round = apps.get_model('api.round')

    rs = Round.objects.filter(
        date__isnull=True,
    )
    for r in rs:
        r.date = r.session.convention.start_date
        r.save()



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190516_0958'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
