# Generated by Django 2.1.8 on 2019-05-16 20:38

from django.db import migrations

def forward(apps, schema_editor):
    Round = apps.get_model('api.round')

    rs = Round.objects.filter(
        session__convention__status__lte=0,
        session__convention__year__gte=1994,
    ).exclude(
        panelists__category=10,
    )
    for r in rs:
        cnt = r.panelists.filter(
            kind=10,
        ).count()
        if cnt <= 3:
            t = 1
        elif cnt < 15:
            t = 2
        else:
            t = 3
        i = 1
        while i <= t:
            r.panelists.create(
                category=10,
                kind=10,
            )
            i += 1

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190516_1338'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
