# Generated by Django 2.1.8 on 2019-05-17 17:19

from django.db import migrations, models
import django.db.models.deletion

def forward(apps, schema_editor):
    StateLog = apps.get_model('django_fsm_log.models.statelog')

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190517_0956'),
        ('cmanager', '0002_auto_20190517_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='cmanager.Award'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='cmanager.Award'),
        ),
        migrations.AlterField(
            model_name='session',
            name='convention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cmanager.Convention'),
        ),
    ]
