# Generated by Django 2.1.8 on 2019-05-17 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190517_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='convention',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='person',
        ),
        migrations.RemoveField(
            model_name='award',
            name='group',
        ),
        migrations.RemoveField(
            model_name='award',
            name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='convention',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='convention',
            name='group',
        ),
        migrations.RemoveField(
            model_name='convention',
            name='venue',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Award',
        ),
        migrations.DeleteModel(
            name='Convention',
        ),
    ]
