# Generated by Django 2.1.8 on 2019-05-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_panelist_legacy_row_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panelist',
            old_name='legacy_name',
            new_name='legacy_person',
        ),
        migrations.RemoveField(
            model_name='panelist',
            name='legacy_num',
        ),
        migrations.RemoveField(
            model_name='panelist',
            name='legacy_row_id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='legacy_num',
        ),
        migrations.RemoveField(
            model_name='song',
            name='legacy_total',
        ),
        migrations.AddField(
            model_name='song',
            name='legacy_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
