# Generated by Django 2.1.8 on 2019-05-28 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190528_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='legacy_panelist',
        ),
    ]
