# Generated by Django 2.1.8 on 2019-05-31 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190530_1509'),
        ('api', '0015_outcome_is_primary'),
    ]

    operations = [
    ]
