# Generated by Django 2.1.8 on 2019-06-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_merge_20190531_0950'),
        ('api', '0020_merge_20190528_2129'),
    ]

    operations = [
    ]
