# Generated by Django 2.1.8 on 2019-06-05 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20190602_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcome',
            name='is_primary',
        ),
    ]
