# Generated by Django 2.1.8 on 2019-05-14 16:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import timezone_field.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', django_fsm.FSMIntegerField(choices=[(0, 'New')], default=0, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.')),
                ('period', models.IntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('photo', models.DateTimeField(blank=True, null=True)),
                ('arrive', models.DateTimeField(blank=True, null=True)),
                ('depart', models.DateTimeField(blank=True, null=True)),
                ('backstage', models.DateTimeField(blank=True, null=True)),
                ('onstage', models.DateTimeField(blank=True, help_text='\n            The scheduled stage time in the Local time of the Venue.', null=True)),
                ('start', models.DateTimeField(blank=True, help_text='\n            The actual start time.', null=True)),
                ('renditions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grids', to='api.Round')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='(TBD)', help_text='\n            The name of the resource.', max_length=255)),
                ('status', django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=0, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.')),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('airport', models.CharField(blank=True, max_length=30)),
                ('timezone', timezone_field.fields.TimeZoneField(blank=True, help_text='\n            The local timezone of the venue.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='grid',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grids', to='stage.Venue'),
        ),
    ]
