# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repertory',
            options={'verbose_name_plural': 'repertories'},
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='bhs_catalog',
            new_name='bhs_id',
        ),
    ]
