# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organization',
            managers=[
            ],
        ),
    ]
