# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='entity',
        ),
        migrations.AddField(
            model_name='assignment',
            name='convention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='app.Convention'),
        ),
    ]
