# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='lyricists',
            field=models.CharField(default='(Unknown Lyricists)', max_length=200),
        ),
        migrations.AlterField(
            model_name='chart',
            name='arrangers',
            field=models.CharField(default='(Unknown Arrangers)', max_length=200),
        ),
        migrations.AlterField(
            model_name='chart',
            name='composers',
            field=models.CharField(default='(Unknown Composers)', max_length=200),
        ),
        migrations.AlterField(
            model_name='chart',
            name='holders',
            field=models.CharField(default='(Unknown Copyright Holders)', max_length=200),
        ),
    ]
