# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='judge',
            new_name='person',
        ),
    ]
