# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='group',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='group',
            name='district',
        ),
        migrations.RemoveField(
            model_name='group',
            name='division',
        ),
        migrations.AlterUniqueTogether(
            name='judge',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='judge',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='person',
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='member',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='member',
            name='person',
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='organization',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='representative',
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='role',
            name='group',
        ),
        migrations.RemoveField(
            model_name='role',
            name='person',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Judge',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
