# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170508_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='lyricists',
            field=models.TextField(blank=True, help_text='\n            Names of the Lyricist(s).\n        '),
        ),
        migrations.AlterField(
            model_name='submission',
            name='composers',
            field=models.TextField(blank=True, help_text='\n            Names of the Composer(s).\n        '),
        ),
    ]
