# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170103_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='nomen',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
