# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170311_0811'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([]),
        ),
    ]
