# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 00:08
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    User = apps.get_model("app", "User")
    us = User.objects.all()
    for u in us:
        u.email = u.username
        u.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_email'),
    ]

    operations = [
        migrations.RunPython(forward, reverse)
    ]
