# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170130_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='kind',
            field=models.IntegerField(choices=[(5, b'DRCJ'), (10, b'Official'), (20, b'Practice'), (30, b'Composite')]),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='session',
        ),
    ]
