# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161021_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bhs_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nomen',
        ),
    ]
