# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 16:23
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Award = apps.get_model('app', 'Award')
    ws = Award.objects.all()
    for w in ws:
        if w.kind == 1:
            w.kind = 31
            w.age = None
        elif w.kind == 2:
            w.kind = 32
            w.age = None
        elif w.kind == 10:
            w.kind = 31
            w.age = 10
        elif w.kind == 20:
            w.kind = 31
            w.age = 20
        elif w.kind == 30:
            w.kind = 31
            w.age = 30
        else:
            raise RuntimeError('Bad Kind')
        w.save()

    Session = apps.get_model('app', 'Session')
    ws = Session.objects.all()
    for w in ws:
        if w.kind == 1:
            w.kind = 31
            w.age = None
        elif w.kind == 2:
            w.kind = 32
            w.age = None
        elif w.kind == 10:
            w.kind = 31
            w.age = 10
        elif w.kind == 20:
            w.kind = 31
            w.age = 20
        elif w.kind == 30:
            w.kind = 31
            w.age = 30
        else:
            raise RuntimeError('Bad Kind')
        w.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170311_0837'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
