# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170103_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='nomen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='nomen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='catalog',
            name='nomen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='nomen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='nomen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='convention',
            name='nomen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='nomen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='judge',
            name='nomen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='nomen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='nomen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='nomen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='performer',
            name='nomen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='nomen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='nomen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='nomen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='nomen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='nomen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='nomen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='nomen',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
