# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170104_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='host',
            name='name',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='performer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='role',
            name='name',
        ),
        migrations.RemoveField(
            model_name='round',
            name='name',
        ),
        migrations.RemoveField(
            model_name='score',
            name='name',
        ),
        migrations.RemoveField(
            model_name='session',
            name='name',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='name',
        ),
        migrations.RemoveField(
            model_name='song',
            name='name',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='name',
        ),
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(editable=False, help_text=b'Award Name.', max_length=255, unique=True),
        ),
    ]
