# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20161021_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='kind',
            field=models.IntegerField(choices=[(10, b'Chair'), (15, b'Chair'), (30, b'Specialist'), (35, b'DRCJ'), (40, b'Certified'), (50, b'Candidate'), (60, b'Retired'), (70, b'Lapsed')]),
        ),
    ]
