# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170130_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='panel',
            field=models.IntegerField(choices=[(0, b'Unknown'), (1, b'Single'), (2, b'Double'), (3, b'Triple'), (4, b'Quadruple'), (5, b'Quintiple')], default=0),
        ),
    ]
