# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170311_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='kind',
            field=models.IntegerField(choices=[(31, 'Quartet'), (32, 'Chorus'), (33, 'Very Large Quartet')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='kind',
            field=models.IntegerField(choices=[(31, 'Quartet'), (32, 'Chorus'), (33, 'Very Large Quartet')], help_text='\n            The kind of session.  Generally this will be either quartet or chorus,\n            with the exception being International and Midwinter which hold exclusive\n            Youth and Senior sessions respectively.'),
        ),
    ]
