# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 18:57
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Office = apps.get_model("app", "Office")
    offices = Office.objects.all()
    map = {
        'Society': 1,
        'Board': 1,
        'Chapter': 32,
        'District': 11,
        'Harmony': 1,
        'Headquarters': 1,
        'Quartet': 31,
    }
    for office in offices:
        first = office.name.partition(" ")[0]
        try:
            kind = map[first]
        except KeyError:
            kind = None
        office.kind = kind
        office.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170428_1047'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
