# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 20:56
from __future__ import unicode_literals

import app.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestPrivate',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('contest', app.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Contest')),
                ('champion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Performer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
