# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170407_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app.Entity'),
        ),
        migrations.AlterField(
            model_name='member',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app.Person'),
        ),
    ]
