# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_convention_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
