# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 16:23
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Host = apps.get_model('app', 'Host')
    Convention = apps.get_model('app', 'Convention')
    conventions = Convention.objects.filter(
        entity=None,
    ).exclude(
        hosts__isnull=True,
    )
    for convention in conventions:
        try:
            entity = convention.hosts.get(
                entity__kind=1,
            ).entity
        except Host.DoesNotExist:
            entity = None
        if not entity:
            try:
                entity = convention.hosts.get(
                    entity__kind=11,
                ).entity
            except Host.DoesNotExist:
                entity = convention.hosts.filter(
                    entity__kind=21,
                ).first().entity.parent
                if entity.kind != 11:
                    raise RuntimeError('Not district')
        convention.entity = entity
        convention.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170311_0842'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
