# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 23:54
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    ContestPrivate = apps.get_model("app", "ContestPrivate")
    ContestScore = apps.get_model("app", "ContestScore")
    ps = ContestPrivate.objects.all()
    for p in ps:
        try:
            c = ContestScore.objects.get(
                contest_ptr_id=p.pk
            )
        except ContestScore.DoesNotExist:
            continue
        if c.champion:
            p.champion = c.champion
            p.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_contestprivate'),
    ]

    operations = [
        migrations.RunPython(forward, reverse)
    ]
