# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170104_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='cycle',
        ),
    ]
