# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170407_1353'),
    ]

    operations = [
        migrations.RenameModel('Performer', 'Entry')
    ]
