# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170130_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='nomen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
