# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_contest_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='advance',
            field=models.FloatField(blank=True, help_text=b'\n            The score threshold to advance to next round (if any) in\n            multi-round qualification.\n        ', null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='threshold',
            field=models.FloatField(blank=True, help_text=b'\n            The score threshold for automatic qualification (if any.)\n        ', null=True),
        ),
    ]
