# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 14:01
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170311_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='kind',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Qualifier'), (0, 'New'), (10, 'Championship')], default=0),
        ),
    ]
