# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170407_1420'),
    ]

    operations = [
        migrations.RenameModel('PerformerPrivate', 'EntryPrivate')
    ]
