# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170407_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.RenameField(
            model_name='contestant',
            old_name='performer',
            new_name='entry',
        ),
        migrations.RenameField(
            model_name='entryprivate',
            old_name='performer',
            new_name='entry',
        ),
        migrations.RenameField(
            model_name='performance',
            old_name='performer',
            new_name='entry',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='performer',
            new_name='entry',
        ),
        migrations.AlterField(
            model_name='entry',
            name='baritone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries_baritone', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='bass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries_bass', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='codirector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries_codirector', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries_director', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='app.Entity'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_evaluation',
            field=models.BooleanField(default=True, help_text='\n            Entry requests evaluation.'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries_lead', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='representing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries_representing', to='app.Entity'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='app.Session'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tenor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries_tenor', to='app.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='contestant',
            unique_together=set([('entry', 'contest')]),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set([('entry', 'title')]),
        ),
    ]
