# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170105_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='panel_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
