# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170131_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='kind',
            field=models.IntegerField(choices=[(5, b'DRCJ'), (10, b'CA'), (20, b'ACA'), (30, b'Music'), (40, b'Presentation'), (50, b'Singing')]),
        ),
    ]
