# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 15:14
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170428_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repertory',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Invalid'), (0, 'New'), (10, 'Valid')], default=0),
        ),
    ]
