# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170430_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charts', to='app.Entity'),
        ),
    ]
