# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170313_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='age',
            field=models.IntegerField(blank=True, choices=[(0, 'All'), (10, 'Seniors'), (20, 'Collegiate'), (30, 'Youth')], null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='age',
            field=models.IntegerField(blank=True, choices=[(0, 'All'), (10, 'Seniors'), (20, 'Collegiate'), (30, 'Youth')], null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='age',
            field=models.IntegerField(blank=True, choices=[(0, 'All'), (10, 'Seniors'), (20, 'Collegiate'), (30, 'Youth')], null=True),
        ),
    ]
