# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_contestantprivate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestantprivate',
            old_name='contest',
            new_name='contestant',
        ),
    ]
