# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170407_1427'),
    ]

    operations = [
        migrations.RenameModel('Performance', 'Appearance'),
        migrations.RenameModel('PerformancePrivate', 'AppearancePrivate')
    ]
