# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_session_panel_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convention',
            old_name='drcj',
            new_name='drcj_old',
        ),
    ]
