# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170115_0504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='representative',
            new_name='representative_old',
        ),
    ]
