# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 15:41
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Entity = apps.get_model('app', 'Entity')
    Session = apps.get_model('app', 'Session')
    Award = apps.get_model('app', 'Award')

    items = Entity.objects.filter(
        age=None,
    )
    for item in items:
        item.age = 0
        item.save()

    items = Session.objects.filter(
        age=None,
    )
    for item in items:
        item.age = 0
        item.save()

    items = Award.objects.filter(
        age=None,
    )
    for item in items:
        item.age = 0
        item.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170314_0840'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
