# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170131_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='nomen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
