# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170407_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appearanceprivate',
            old_name='performance',
            new_name='appearance',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='performance',
            new_name='appearance',
        ),
        migrations.AlterField(
            model_name='appearance',
            name='actual_finish',
            field=models.DateTimeField(blank=True, help_text='\n            The actual appearance window.', null=True),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='actual_start',
            field=models.DateTimeField(blank=True, help_text='\n            The actual appearance window.', null=True),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='app.Entry'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='app.Round'),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set([('appearance', 'num')]),
        ),
    ]
