# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 18:57
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Chart = apps.get_model("app", "Chart")
    Entity = apps.get_model("app", "Entity")
    bhs = Entity.objects.get(short_name='BHS')
    charts = Chart.objects.all()

    for chart in charts:
        chart.entity = bhs
        chart.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_chart_entity'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
