# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_assignment_person'),
    ]

    operations = [
        migrations.RenameField('Assignment', 'judge', 'judge'),
    ]
