# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170217_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestantscore',
            name='contestant_ptr',
        ),
        migrations.DeleteModel(
            name='ContestantScore',
        ),
    ]
