# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170314_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='age',
            field=models.IntegerField(choices=[(0, 'All'), (10, 'Seniors'), (20, 'Collegiate'), (30, 'Youth')], default=0),
        ),
    ]
