# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170407_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appearanceprivate',
            options={'verbose_name_plural': 'AppearancesPrivate'},
        ),
        migrations.AlterModelOptions(
            name='contestantprivate',
            options={'verbose_name_plural': 'ContestantsPrivate'},
        ),
        migrations.AlterModelOptions(
            name='contestprivate',
            options={'verbose_name_plural': 'ContestsPrivate'},
        ),
        migrations.AlterModelOptions(
            name='entryprivate',
            options={'verbose_name_plural': 'EntriesPrivate'},
        ),
        migrations.AlterModelOptions(
            name='songprivate',
            options={'verbose_name_plural': 'SongsPrivate'},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='kind',
            field=models.IntegerField(choices=[(5, 'DRCJ'), (10, 'CA'), (20, 'ACA'), (30, 'Music'), (40, 'Performance'), (50, 'Singing')]),
        ),
        migrations.AlterField(
            model_name='score',
            name='category',
            field=models.IntegerField(choices=[(1, 'Music'), (2, 'Performance'), (3, 'Singing')]),
        ),
    ]
