# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170131_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='arrangers',
            field=models.TextField(blank=True, help_text=b'\n            Names of the Arranger(s).\n        ', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='bhs_catalog',
            field=models.IntegerField(blank=True, help_text=b'\n            The BHS Catalog Number.\n        ', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='composers',
            field=models.TextField(blank=True, help_text=b'\n            Names of the Composer(s) and/or Lyricist(s).\n        ', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='holders',
            field=models.TextField(blank=True, help_text=b'\n            Names of the Copyright Holder(s).\n        ', null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='title',
            field=models.CharField(help_text=b'\n            Title of the composition.\n        ', max_length=200),
        ),
    ]
