# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170501_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='app.Entity'),
        ),
    ]
