# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170115_0609'),
    ]

    operations = [
        migrations.RenameField('Assignment', 'person', 'judge'),
    ]
