# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170115_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='app.Person'),
        ),
    ]
