# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170314_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='app.Session'),
        ),
        migrations.AlterField(
            model_name='host',
            name='convention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='app.Convention'),
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together=set([]),
        ),
    ]
