# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 20:30
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    Submission = apps.get_model("app", "Submission")
    ss = Submission.objects.exclude(arranger='')
    for s in ss:
        s.arrangers = s.arranger
        s.save()


def reverse(apps, schema_editor):
    Submission = apps.get_model("app", "Submission")
    ss = Submission.objects.exclude(arrangers='')
    for s in ss:
        s.arrangers = ''
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170131_1230'),
    ]

    operations = [
        migrations.RunPython(forward, reverse)
    ]
