# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import mptt.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20170127_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomen', models.CharField(max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(0, b'New'), (10, b'Active'), (20, b'Inactive')], default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('entity', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='app.Entity')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='app.Person')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([('entity', 'person')]),
        ),
    ]
