# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 18:57
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Appearance = apps.get_model("app", "Appearance")
    appearances = Appearance.objects.all()
    for appearance in appearances:
        songs = appearance.songs.all()
        for song in songs:
            i = 1
            scores = song.scores.order_by(
                'kind',
                'category',
                'person__name',
            )
            for score in scores:
                score.num = i
                score.save()
                i += 1


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_score_num'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
