# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 17:02
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Session = apps.get_model('app', 'Session')
    Host = apps.get_model('app', 'Host')

    sessions = Session.objects.all()
    for session in sessions:
        hosts = session.convention.hosts.all()
        for host in hosts:
            Host.objects.create(
                entity=host.entity,
                session=session,
            )


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20170314_1002'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
