# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 00:43
from __future__ import unicode_literals

from django.db import migrations

from app.models import (
    Entity,
    Member,
    Membership,
)


def copy_members(apps, schema_editor):
    ms = Member.objects.all()
    for m in ms:
        try:
            entity = Entity.objects.get(
                legacy_id=m.chapter.groups.filter(status=10).first().id.hex
            )
        except AttributeError:
            continue
        Membership.objects.create(
            status=m.status,
            start_date=m.start_date,
            end_date=m.end_date,
            entity=entity,
            person=m.person,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170127_1643'),
    ]

    operations = [
        migrations.RunPython(copy_members),
    ]
