# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170217_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancescore',
            name='performance_ptr',
        ),
        migrations.DeleteModel(
            name='PerformanceScore',
        ),
    ]
