# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 18:57
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Score = apps.get_model("app", "Score")
    scores = Score.objects.all()
    map = {
        1: 30,
        2: 40,
        3: 50,
    }
    for score in scores:
        score.category = map[score.category]
        score.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170408_1157'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
