# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 19:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170314_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='participants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
