# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20170201_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='chorus_prelims',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='convention',
            name='quartet_prelims',
            field=models.BooleanField(default=False),
        ),
    ]
