# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20170203_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_prelims',
            field=models.BooleanField(default=False),
        ),
    ]
