# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_session_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='app.Award'),
        ),
    ]
