# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_session_is_prelims'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='round',
            unique_together=set([]),
        ),
    ]
