# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20170316_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='qualifier_rounds',
        ),
        migrations.RemoveField(
            model_name='award',
            name='qualifier_season',
        ),
    ]
