# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20170205_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='convention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.Convention'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.Person'),
        ),
    ]
