# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20170316_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='championship_rounds',
            new_name='rounds',
        ),
        migrations.RenameField(
            model_name='award',
            old_name='championship_season',
            new_name='season',
        ),
    ]
