# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20170410_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='num_songs',
            field=models.IntegerField(default=2),
        ),
    ]
