# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 14:18
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    Assignment = apps.get_model("app", "Assignment")
    items = Assignment.objects.exclude(category=None)
    mapping = {
        0: 10,
        1: 30,
        2: 40,
        3: 50,
    }
    for i in items:
        i.kind = mapping[i.category]
        i.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20170205_0614'),
    ]

    operations = [
        migrations.RunPython(forward, reverse)
    ]
