# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 04:28
from __future__ import unicode_literals

import app.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_session_num_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='mus_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appearance',
            name='mus_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appearance',
            name='prs_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appearance',
            name='prs_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appearance',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appearance',
            name='sng_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appearance',
            name='sng_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appearance',
            name='total_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appearance',
            name='total_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Entry'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='mus_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='mus_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='prs_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='prs_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='sng_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='sng_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='total_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='total_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='csa_pdf',
            field=models.FileField(blank=True, help_text='\n            The historical PDF CSA.', null=True, upload_to=app.fields.PathAndRename()),
        ),
        migrations.AddField(
            model_name='entry',
            name='mus_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='mus_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='prs_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='prs_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='sng_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='sng_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='total_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='total_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='mus_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='mus_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='prs_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='prs_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='sng_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='sng_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='total_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='total_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
