# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import django_fsm
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20170128_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomen', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=200)),
                ('status', django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Active'), (20, b'Inactive')], default=0)),
                ('kind', django_fsm.FSMIntegerField(choices=[(0, b'New'), (1, b'One'), (10, b'Ten'), (20, b'Twenty')], default=0)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('long_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
