# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20170217_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestantprivate',
            name='contestant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Contestant'),
        ),
        migrations.AlterField(
            model_name='contestprivate',
            name='contest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Contest'),
        ),
        migrations.AlterField(
            model_name='performanceprivate',
            name='performance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Performance'),
        ),
        migrations.AlterField(
            model_name='performerprivate',
            name='performer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Performer'),
        ),
        migrations.AlterField(
            model_name='songprivate',
            name='song',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Song'),
        ),
    ]
