# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 14:49
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Count


def forward(apps, schema_editor):
    Assignment = apps.get_model("app", "Assignment")
    more = True
    while more:
        dups = (
            Assignment.objects.values('person', 'convention')
            .annotate(count=Count('id'))
            .values('person', 'convention')
            .order_by()
            .filter(count__gt=1)
        )
        for d in dups:
            i = Assignment.objects.filter(**d).first()
            i.delete()
        more = bool(dups)


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20170205_0618'),
    ]

    operations = [
        migrations.RunPython(forward, reverse)
    ]
