# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 15:41
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Session = apps.get_model('app', 'Session')
    items = Session.objects.filter(
        age=0,
    )
    for item in items:
        item.age = None
        item.save()

    Award = apps.get_model('app', 'Award')
    items = Award.objects.filter(
        age=0,
    )
    for item in items:
        item.age = None
        item.save()

    Entity = apps.get_model('app', 'Entity')
    items = Entity.objects.filter(
        age=0,
    )
    for item in items:
        item.age = None
        item.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20170317_0603'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
