# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20170205_0649'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set([('convention', 'person')]),
        ),
    ]
