# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 18:09
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    Convention = apps.get_model("app", "Convention")
    cs = Convention.objects.filter(hosts__isnull=True)
    for c in cs:
        c.hosts.create(
            entity=c.entity,
        )


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20170205_0654'),
    ]

    operations = [
        migrations.RunPython(forward, reverse)
    ]
