# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20170410_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearanceprivate',
            name='appearance',
        ),
        migrations.RemoveField(
            model_name='contestantprivate',
            name='contestant',
        ),
        migrations.RemoveField(
            model_name='contestprivate',
            name='champion',
        ),
        migrations.RemoveField(
            model_name='contestprivate',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='entryprivate',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='songprivate',
            name='song',
        ),
        migrations.DeleteModel(
            name='AppearancePrivate',
        ),
        migrations.DeleteModel(
            name='ContestantPrivate',
        ),
        migrations.DeleteModel(
            name='ContestPrivate',
        ),
        migrations.DeleteModel(
            name='EntryPrivate',
        ),
        migrations.DeleteModel(
            name='SongPrivate',
        ),
    ]
