# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20170410_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='is_cj',
            field=models.BooleanField(default=False),
        ),
    ]
