# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 15:41
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Q


def forwards(apps, schema_editor):
    Award = apps.get_model('app', 'Award')

    awards = Award.objects.filter(
        Q(
            status=10,
            is_primary=True,
            kind__in=[
                31,
                32
            ],
            age=None,
            entity__kind__in=[
                11,
            ],
            entity__short_name__in=[
                'EVG',
                'FWD',
                'LOL',
                'MAD',
            ],
        ) |
        Q(
            status=10,
            season__in=[
                1,
                2,
            ],
            is_primary=True,
        )
    )

    for award in awards:
        qr = 1 if award.kind == 32 else 2
        new = Award(
            name="{0} Qualifier".format(award.name),
            status=10,
            kind=award.kind,
            season=4,
            rounds=qr,
            is_primary=True,
            threshold=award.threshold,
            minimum=award.minimum,
            advance=award.advance,
            entity=award.entity,
            parent=award,
        )
        new.save()


def backwards(apps, schema_editor):
    Award = apps.get_model('app', 'Award')
    awards = Award.objects.exclude(parent=None)
    awards.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20170317_0717'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
