# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 18:15
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20170206_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='entity',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='app.Entity'),
        ),
    ]
