# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 23:29
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Membership = apps.get_model("app", "Membership")
    Office = apps.get_model("app", "Office")
    Person = apps.get_model("app", "Person")
    Entity = apps.get_model("app", "Entity")
    drcj = Office.objects.get(short_name='DRCJ')
    holders = [
        ['CAR', 'kakitzmiller@gmail.com', 265632],
        ['CSD', 'ctcombs10r@gmail.com', 200031],
        ['DIX', 'jimsamsca@bellsouth.net', 184423],
        ['EVG', 'jimbob.2@comcast.net', 181980],
        ['FWD', 'rlblack1@gmail.com', 157885],
        ['JAD', 'blcourts@gmail.com', 239603],
        ['LOL', 'stvjhnsn@att.net', 219172],
        ['MAD', 'gplaagbhs@gmail.com', 221145],
        ['NED', 'janlam314@cox.net', 186008],
        ['NSC', 'lgreinhart@aol.com', 220903],
        ['ONT', 'barry.towner@gmail.com', 154085],
        ['PIO', 'MSUDUNK@gmail.com', 258980],
        ['SLD', 'dstothard@aol.com', 131659],
        ['SUN', 'janesbari@outlook.com', 130107],
        ['SWD', 'randy.rensi@ieee.org', 234975],
    ]
    for holder in holders:
        entity = Entity.objects.get(
            kind=11,  # District, Hard-Coded
            short_name=holder[0],
        )
        person = Person.objects.get(
            bhs_id=holder[2]
        )
        member, _ = Membership.objects.get_or_create(
            entity=entity,
            person=person,
        )
        officer, _ = member.officers.get_or_create(
            office=drcj,
        )


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_convention_entity'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
