# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 23:29
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Convention = apps.get_model("app", "Convention")
    Entity = apps.get_model("app", "Entity")
    cs = Convention.objects.filter(
        year=2017,
    )
    for c in cs:
        try:
            entity = Entity.objects.get(
                short_name=c.name[:3],
                kind=11,
            )
        except Entity.DoesNotExist:
            continue
        c.entity = entity
        c.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20170304_1529'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
