# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 15:05
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20170128_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='kind',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (1, b'One'), (10, b'Ten'), (20, b'Twenty'), (30, b'Thirty')], default=0),
        ),
    ]
