# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20170206_1015'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='host',
            unique_together=set([('convention', 'entity')]),
        ),
    ]
