# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 18:57
from __future__ import unicode_literals
from django.db.models import Q
from django.db import migrations


def forwards(apps, schema_editor):
    Office = apps.get_model("app", "Office")
    js = Office.objects.filter(
        Q(name__icontains='C&J') |
        Q(name__icontains='Candidate') |
        Q(name__icontains='Certified') |
        Q(name__icontains='Specialist')
    )
    for j in js:
        j.is_cj = True
        j.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_office_is_cj'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
