# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 23:29
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Convention = apps.get_model("app", "Convention")
    cs = Convention.objects.filter(
        year=2017,
    ).exclude(
        entity=None,
    )
    for c in cs:
        person = c.entity.memberships.filter(
            officers__office__short_name='DRCJ',
        ).first().person
        c.assignments.get_or_create(
            person=person,
            kind=5,
        )


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20170304_1609'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
