# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 18:57
from __future__ import unicode_literals
from django.db import migrations
from django.utils import timezone


def forwards(apps, schema_editor):
    Member = apps.get_model("app", "Member")
    ms = Member.objects.filter(start_date='1998-11-25')
    for m in ms:
        m.status = -10
        m.end_date = timezone.now()
        m.save()

    Entity = apps.get_model("app", "Entity")
    es = Entity.objects.filter(status=-10)
    for e in es:
        ms = e.members.all()
        for m in ms:
            m.status = -10
            m.end_date = timezone.now()
            m.save()

    es = Entity.objects.filter(status=0)
    for e in es:
        e.status = 10
        e.save()
        ms = e.members.all()
        for m in ms:
            m.status = 10
            m.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20170414_2156'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
