# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20170206_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='bhs_id',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='award',
            name='idiom',
        ),
        migrations.RemoveField(
            model_name='award',
            name='is_qualification_required',
        ),
        migrations.RemoveField(
            model_name='award',
            name='stix_name',
        ),
        migrations.RemoveField(
            model_name='award',
            name='stix_num',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='num_rounds',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='stix_name',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='stix_num',
        ),
        migrations.RemoveField(
            model_name='convention',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='convention',
            name='stix_div',
        ),
        migrations.RemoveField(
            model_name='convention',
            name='stix_file',
        ),
        migrations.RemoveField(
            model_name='convention',
            name='stix_name',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='legacy_id',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='legacy_parent',
        ),
        migrations.RemoveField(
            model_name='round',
            name='stix_name',
        ),
        migrations.AlterField(
            model_name='award',
            name='entity',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='app.Entity'),
        ),
        migrations.AlterField(
            model_name='award',
            name='is_novice',
            field=models.BooleanField(default=False, help_text=b'Award for Novice groups.'),
        ),
        migrations.AlterField(
            model_name='award',
            name='is_primary',
            field=models.BooleanField(default=False, help_text=b'The primary award; requires qualification.'),
        ),
        migrations.AlterField(
            model_name='award',
            name='minimum',
            field=models.FloatField(blank=True, help_text=b'\n            The minimum score required for qualification (if any.)\n        ', null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='app.Membership'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='app.Office'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([('entity', 'person')]),
        ),
    ]
