# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 15:41
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Award = apps.get_model('app', 'Award')

    names = [
        'Dixie District Seniors Championship',
        'Evergreen District Seniors Championship',
        'Far Western District Seniors Championship',
        'Illinois District Seniors Championship',
        'Land O\' Lakes District Seniors Championship',
        'Northeastern District Seniors Championship',
        'Rocky Mountain District Seniors Championship',
        'Seneca Land District Seniors Championship',
        'Southwestern District Seniors Championship',
        'Mid-Atlantic District Seniors Championship',
    ]
    for name in names:
        award = Award.objects.get(
            is_primary=True,
            name=name,
        )
        award.is_primary = False
        award.save()


def backwards(apps, schema_editor):
    Award = apps.get_model('app', 'Award')
    awards = Award.objects.exclude(parent=None)
    awards.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20170317_1202'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
