# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 20:09
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20170206_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='entity',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performers', to='app.Entity'),
        ),
        migrations.AlterUniqueTogether(
            name='performer',
            unique_together=set([('entity', 'session')]),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together=set([('session', 'kind')]),
        ),
    ]
