# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20170304_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='award',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='app.Entity'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='app.Entity'),
        ),
        migrations.AlterField(
            model_name='host',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='app.Entity'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='app.Entity'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performers', to='app.Entity'),
        ),
    ]
