# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 18:57
from __future__ import unicode_literals
from django.db import migrations
from django.utils import timezone


def forwards(apps, schema_editor):
    Officer = apps.get_model("app", "Officer")
    ms = Officer.objects.filter(office__is_cj=True)
    for m in ms:
        m.status = 10
        m.save()

def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20170415_0757'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
