# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 15:41
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Q


def forwards(apps, schema_editor):
    Award = apps.get_model('app', 'Award')

    awards = Award.objects.filter(
        Q(
            is_primary=True,
            age__gt=0,
            entity__kind=11
        ) |
        Q(
            is_primary=True,
            entity__kind=11,
            parent__isnull=False,
        )
    )

    for award in awards:
        award.is_primary = False
        award.save()


def backwards(apps, schema_editor):
    Award = apps.get_model('app', 'Award')
    awards = Award.objects.exclude(parent=None)
    awards.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20170317_1244'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
