# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20170317_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='is_qualifier',
            field=models.BooleanField(default=False, help_text='Qualificationn award.'),
        ),
    ]
