# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 15:23
from __future__ import unicode_literals

from django.db import migrations

from app.models import (
    Entity,
    Judge,
    Office,
    Officer,
    Organization,
    Membership,
)


def add_judges(apps, schema_editor):
    judges = Judge.objects.filter(
        kind__in=[30, 40, 50]
    )
    for judge in judges:
        if judge.kind == 30:  # specialist
            first = 'Specialist'
        elif judge.kind == 40:  # certified
            first = 'Certified'
        elif judge.kind == 50:   # active
            first = 'Candidate'
        else:
            continue
        if judge.category == 0:
            second = 'Admin'
        elif judge.category == 1:
            second = 'Music'
        elif judge.category == 2:
            second = 'Presentation'
        elif judge.category == 3:
            second = 'Singing'
        else:
            continue
        name = "{0} {1}".format(first, second)
        office = Office.objects.get(name=name)
        bhs = Entity.objects.get(kind=1)
        membership = Membership.objects.get(
            person=judge.person,
            entity=bhs,
        )
        Officer.objects.create(
            office=office,
            membership=membership,
        )


def add_drcj(apps, schema_editor):
    organizations = Organization.objects.filter(
        kind=10,
    ).exclude(
        representative=None,
    )
    for organization in organizations:
        office = Office.objects.get(short_name='DRCJ')
        entity = Entity.objects.get(name=organization.name)
        person = organization.representative
        print person, office, entity
        membership = Membership.objects.create(
            person=person,
            entity=entity,
        )
        Officer.objects.create(
            office=office,
            membership=membership,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20170128_0708'),
    ]

    operations = [
        migrations.RunPython(add_judges)
    ]
