# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 20:17
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Count


def forward(apps, schema_editor):
    Submission = apps.get_model("app", "Submission")
    more = True
    while more:
        dups = (
            Submission.objects.values('performer', 'title')
            .annotate(count=Count('id'))
            .values('performer', 'title')
            .order_by()
            .filter(count__gt=1)
        )
        for d in dups:
            i = Submission.objects.filter(**d).first()
            i.delete()
        more = bool(dups)


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20170206_1209'),
    ]

    operations = [
        migrations.RunPython(forward, reverse)
    ]
