# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 17:40
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Person = apps.get_model("app", "Person")
    ps = Person.objects.all()
    for p in ps:
        first = p.name.partition(' ')[0]
        parts = p.name.rpartition(' ')
        last = parts[2]
        reduced = parts[0]
        if first == last:
            p.name = reduced
            p.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20170308_0821'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
