# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 18:57
from __future__ import unicode_literals
from django.db import migrations


def forwards(apps, schema_editor):
    Officer = apps.get_model("app", "Officer")
    js = Officer.objects.filter(
        office__short_name='DRCJ'
    ).exclude(
        entity__kind=11
    )
    js.delete()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20170415_0827'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
