# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20170206_1217'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set([('performer', 'title')]),
        ),
    ]
