# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20170415_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='status',
            field=models.IntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=10),
        ),
    ]
