# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20170308_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='common_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='formal_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='full_name',
        ),
    ]
