# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20170128_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, b'Inactive'), (0, b'New'), (10, b'Active')], default=0),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, b'Inactive'), (0, b'New'), (10, b'Active')], default=0),
        ),
        migrations.AlterField(
            model_name='entity',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, b'Inactive'), (0, b'New'), (10, b'Active')], default=0),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.IntegerField(choices=[(-10, b'Inactive'), (0, b'New'), (10, b'Active')], default=0),
        ),
        migrations.AlterField(
            model_name='judge',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, b'Inactive'), (0, b'New'), (1, b'Active')], default=0),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.IntegerField(choices=[(-10, b'Inactive'), (0, b'New'), (10, b'Active')], default=0),
        ),
        migrations.AlterField(
            model_name='office',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, b'Inactive'), (0, b'New'), (10, b'Active')], default=0),
        ),
        migrations.AlterField(
            model_name='officer',
            name='status',
            field=models.IntegerField(choices=[(-10, b'Inactive'), (0, b'New'), (10, b'Active')], default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(-10, b'Inactive'), (0, b'New'), (1, b'Active'), (3, b'Retired'), (5, b'Deceased'), (6, b'(Six)'), (9, b'(Nine)')], default=0),
        ),
        migrations.AlterField(
            model_name='venue',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, b'Inactive'), (0, b'New'), (10, b'Active')], default=0),
        ),
    ]
