# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 16:08
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20170415_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='airports',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=3, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='person',
            name='cell_phone',
            field=models.CharField(blank=True, help_text='\n            The cell phone number of the resource.  Include country code.', max_length=25),
        ),
        migrations.AddField(
            model_name='person',
            name='home_phone',
            field=models.CharField(blank=True, help_text='\n            The home phone number of the resource.  Include country code.', max_length=25),
        ),
        migrations.AddField(
            model_name='person',
            name='work_phone',
            field=models.CharField(blank=True, help_text='\n            The work phone number of the resource.  Include country code.', max_length=25),
        ),
    ]
