# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20170206_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='nomen',
            field=models.CharField(editable=False, max_length=500, null=True),
        ),
    ]
