# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20170308_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='level',
        ),
    ]
