# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 16:37
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20170421_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True, help_text='\n            The complete address of the resource.', max_length=1000),
        ),
        migrations.AddField(
            model_name='person',
            name='so',
            field=models.CharField(blank=True, help_text="\n            Name of the person's Significant Other.", max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='airports',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=3), blank=True, null=True, size=None),
        ),
    ]
