# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 18:15
from __future__ import unicode_literals

from django.db import migrations

from app.models import (
    Entity,
)

def convert_entity(apps, schema_editor):
    items = Entity.objects.filter(status=20)
    for i in items:
        i.status = -10
        i.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20170128_1005'),
    ]

    operations = [
        migrations.RunPython(convert_entity),
    ]
