# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20170421_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='so',
        ),
    ]
