# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 15:41
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Convention = apps.get_model('app', 'Convention')

    conventions = Convention.objects.filter(
        panel=0
    )

    for convention in conventions:
        conventions.panel = None
        convention.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20170321_1301'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
