# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 18:57
from __future__ import unicode_literals
from django.db import migrations


def forwards(apps, schema_editor):
    Office = apps.get_model("app", "Office")
    offices = Office.objects.filter(
        name__in=[
            'Specialist Admin',
            'Specialist Music',
            'Specialist Presentation',
            'Specialist Singing',
            'Certified Admin',
            'Certified Music',
            'Certified Presentation',
            'Certified Singing',
            'Candidate Admin',
            'Candidate Music',
            'Candidate Presentation',
            'Candidate Singing',
        ]
    )
    offices.delete()
    new = [
        {'name': 'Society C&J Administrator Specialist', 'kind': 1, 'status': 10, 'is_cj': True},
        {'name': 'Society C&J Music Specialist', 'kind': 1, 'status': 10, 'is_cj': True},
        {'name': 'Society C&J Performance Specialist', 'kind': 1, 'status': 10, 'is_cj': True},
        {'name': 'Society C&J Singing Specialist', 'kind': 1, 'status': 10, 'is_cj': True},
    ]
    for n in new:
        Office.objects.create(**n)
    update = Office.objects.get(name='Society C&J Presentation Judge')
    update.name = 'Society C&J Performance Judge'
    update.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_person_so'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
