# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:29
from __future__ import unicode_literals

from django.db import migrations

models = [
    'Assignment',
    'Award',
    'Catalog',
    'Contest',
    'ContestScore',
    'Contestant',
    'ContestantScore',
    'Convention',
    'Entity',
    'Host',
    'Membership',
    'Office',
    'Officer',
    'Performance',
    'PerformanceScore',
    'Performer',
    'PerformerScore',
    'Person',
    'Round',
    'Score',
    'Session',
    'Slot',
    'Song',
    'SongScore',
    'Submission',
    'Venue',
]

converts = {}

def forward(apps, schema_editor):
    for m in models:
        converts[m] = apps.get_model("app", m)

    xs = converts['Convention'].objects.filter(location=None)
    for x in xs:
        x.location = ''
        x.save()

    xs = converts['Entity'].objects.filter(code=None)
    for x in xs:
        x.code = ''
        x.save()

    xs = converts['Entity'].objects.filter(phone=None)
    for x in xs:
        x.phone = ''
        x.save()

    xs = converts['Office'].objects.filter(long_name=None)
    for x in xs:
        x.long_name = ''
        x.save()

    xs = converts['Office'].objects.filter(short_name=None)
    for x in xs:
        x.short_name = ''
        x.save()

    xs = converts['Person'].objects.filter(common_name=None)
    for x in xs:
        x.common_name = ''
        x.save()

    xs = converts['Person'].objects.filter(email=None)
    for x in xs:
        x.email = ''
        x.save()

    xs = converts['Person'].objects.filter(facebook=None)
    for x in xs:
        x.facebook = ''
        x.save()

    xs = converts['Person'].objects.filter(formal_name=None)
    for x in xs:
        x.formal_name = ''
        x.save()

    xs = converts['Person'].objects.filter(full_name=None)
    for x in xs:
        x.full_name = ''
        x.save()

    xs = converts['Person'].objects.filter(location=None)
    for x in xs:
        x.location = ''
        x.save()

    xs = converts['Person'].objects.filter(phone=None)
    for x in xs:
        x.phone = ''
        x.save()

    xs = converts['Person'].objects.filter(spouse=None)
    for x in xs:
        x.spouse = ''
        x.save()

    xs = converts['Person'].objects.filter(twitter=None)
    for x in xs:
        x.twitter = ''
        x.save()

    xs = converts['Person'].objects.filter(website=None)
    for x in xs:
        x.website = ''
        x.save()

    xs = converts['Slot'].objects.filter(location=None)
    for x in xs:
        x.location = ''
        x.save()

    xs = converts['Submission'].objects.filter(arrangers=None)
    for x in xs:
        x.arrangers = ''
        x.save()

    xs = converts['Submission'].objects.filter(composers=None)
    for x in xs:
        x.composers = ''
        x.save()

    xs = converts['Submission'].objects.filter(holders=None)
    for x in xs:
        x.holders = ''
        x.save()

    xs = converts['Venue'].objects.filter(airport=None)
    for x in xs:
        x.airport = ''
        x.save()

    xs = converts['Venue'].objects.filter(city=None)
    for x in xs:
        x.city = ''
        x.save()

    xs = converts['Venue'].objects.filter(location=None)
    for x in xs:
        x.location = ''
        x.save()

    xs = converts['Venue'].objects.filter(state=None)
    for x in xs:
        x.state = ''
        x.save()

    xs = converts['Venue'].objects.filter(timezone=None)
    for x in xs:
        x.timezone = ''
        x.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20170206_1933'),
    ]

    operations = [
        migrations.RunPython(forward, reverse)
    ]
