# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 16:49
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20170421_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=10),
        ),
    ]
