# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20170209_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='nomen',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='award',
            name='nomen',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='nomen',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='contest',
            name='nomen',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='nomen',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='convention',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='convention',
            name='nomen',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='entity',
            name='code',
            field=models.CharField(blank=True, help_text=b'\n            The chapter code.', max_length=200),
        ),
        migrations.AlterField(
            model_name='entity',
            name='nomen',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='entity',
            name='phone',
            field=models.CharField(blank=True, help_text=b'\n            The phone number of the resource.  Include country code.', max_length=25),
        ),
        migrations.AlterField(
            model_name='host',
            name='nomen',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='membership',
            name='nomen',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='office',
            name='long_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='office',
            name='nomen',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='office',
            name='short_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='officer',
            name='nomen',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='performance',
            name='nomen',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='performer',
            name='nomen',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='person',
            name='common_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, help_text=b'\n            The contact email of the resource.', max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='facebook',
            field=models.URLField(blank=True, help_text=b'\n            The facebook URL of the resource.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='formal_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.CharField(blank=True, help_text=b'\n            The geographical location of the resource.', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='nomen',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, help_text=b'\n            The phone number of the resource.  Include country code.', max_length=25),
        ),
        migrations.AlterField(
            model_name='person',
            name='spouse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='twitter',
            field=models.CharField(blank=True, help_text=b'\n            The twitter handle (in form @twitter_handle) of the resource.', max_length=16, validators=[django.core.validators.RegexValidator(message=b'\n                    Must be a single Twitter handle\n                    in the form `@twitter_handle`.\n                ', regex=b'@([A-Za-z0-9_]+)')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='website',
            field=models.URLField(blank=True, help_text=b'\n            The website URL of the resource.'),
        ),
        migrations.AlterField(
            model_name='round',
            name='nomen',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='score',
            name='nomen',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='session',
            name='nomen',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='slot',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='slot',
            name='nomen',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='song',
            name='nomen',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='submission',
            name='arrangers',
            field=models.TextField(blank=True, help_text=b'\n            Names of the Arranger(s).\n        '),
        ),
        migrations.AlterField(
            model_name='submission',
            name='composers',
            field=models.TextField(blank=True, help_text=b'\n            Names of the Composer(s) and/or Lyricist(s).\n        '),
        ),
        migrations.AlterField(
            model_name='submission',
            name='holders',
            field=models.TextField(blank=True, help_text=b'\n            Names of the Copyright Holder(s).\n        '),
        ),
        migrations.AlterField(
            model_name='submission',
            name='nomen',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='venue',
            name='airport',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='venue',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='venue',
            name='nomen',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='venue',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='venue',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, help_text=b'\n            The local timezone of the venue.'),
        ),
    ]
