# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 15:15
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20170424_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
