# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20170209_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='kind',
            field=models.IntegerField(blank=True, choices=[(10, b'International'), (20, b'District'), (30, b'Division'), (40, b'District/Division')], null=True),
        ),
    ]
