# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 15:41
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Officer = apps.get_model('app', 'Officer')

    officers = Officer.objects.all()

    for officer in officers:
        officer.person = officer.membership.person
        officer.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_officer_person'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
