# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20170324_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='app.Person'),
        ),
    ]
