# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 15:37
from __future__ import unicode_literals

import app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=app.fields.CloudinaryRename(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
