# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 22:28
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    Convention = apps.get_model("app", "Convention")
    mapping = {
        0: 10,
        1: 20,
        2: 30,
        3: 30,
    }
    cs = Convention.objects.all()
    for c in cs:
        c.kind = mapping[c.level]
        c.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_convention_kind'),
    ]

    operations = [
        migrations.RunPython(forward, reverse)
    ]
