# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20170324_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='membership',
        ),
    ]
