# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 15:27
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20170425_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='kind',
            field=django_fsm.FSMIntegerField(blank=True, choices=[('Contest and Judging', [(11, 'SCJC'), (12, 'DRCJ'), (13, 'CA'), (14, 'Judge')]), ('Representative', [(21, 'Representative')])], null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
