# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20170210_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='kind',
            field=models.IntegerField(choices=[(b'Organization', [(1, b'Organization')]), (b'District', [(11, b'District'), (12, b'Noncompetitive'), (13, b'Affiliate')]), (b'Division', [(21, b'Division')]), (b'Group', [(31, b'Quartet'), (32, b'Chorus'), (33, b'Very Large Quartet')])], help_text=b'\n            The kind of organization.'),
        ),
    ]
