# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 18:57
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Office = apps.get_model("app", "Office")
    offices = Office.objects.all()

    for office in offices:
        office.kind = None
        office.save()

    offices = Office.objects.filter(
        short_name__startswith='SCJC',
    )
    for office in offices:
        office.kind = 11
        office.save()

    offices = Office.objects.filter(
        short_name='DRCJ',
    )
    for office in offices:
        office.kind = 12
        office.save()

    offices = Office.objects.filter(
        short_name='CA',
    )
    for office in offices:
        office.kind = 13
        office.save()

    offices = Office.objects.filter(
        short_name__in=[
            'MUS',
            'PER',
            'SNG',
        ],
    )
    for office in offices:
        office.kind = 14
        office.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20170426_0827'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
