# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20170210_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='persun',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='userpersun', to='app.Person'),
        ),
    ]
