# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 17:17
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_remove_officer_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='kind',
            field=django_fsm.FSMIntegerField(choices=[('Organization', [(1, 'Organization')]), ('District', [(11, 'District'), (12, 'Noncompetitive'), (13, 'Affiliate')]), ('Division', [(21, 'Division')]), ('Group', [(31, 'Quartet'), (32, 'Chorus'), (33, 'Very Large Quartet')])]),
        ),
    ]
