# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 15:39
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20170426_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='kind',
            field=django_fsm.FSMIntegerField(blank=True, choices=[('Contest and Judging', [(11, 'SCJC'), (12, 'DRCJ'), (13, 'CA'), (14, 'Judge')]), ('Representative', [(21, 'Representative')]), ('Administrative', [(31, 'Staff'), (32, 'Admin')])], null=True),
        ),
    ]
