# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 15:41
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Office = apps.get_model('app', 'Office')

    offices = Office.objects.all()

    mapping = {
        1: 1,
        10: 11,
        20: 32,
        30: 1,
    }

    for office in offices:
        office.kind = mapping[office.kind]
        office.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20170325_1017'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
