# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 20:30
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    User = apps.get_model("app", "User")
    users = User.objects.all()
    for user in users:
        try:
            user.persun = user.person
        except User.person.RelatedObjectDoesNotExist:
            user.persun = None
        user.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_user_persun'),
    ]

    operations = [
        migrations.RunPython(forward, reverse)
    ]
