# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20170327_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='app.Entity'),
        ),
    ]
