# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20170213_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='persun',
            new_name='person',
        ),
    ]
