# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 19:26
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20170427_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='scoresheet',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
