# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 23:15
from __future__ import unicode_literals

import app.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20170213_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='person',
            field=app.models.OneToOneOrNoneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app.Person'),
        ),
    ]
