# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_session_scoresheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='csa_pdf',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='person',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='round',
            name='ann_pdf',
        ),
        migrations.RemoveField(
            model_name='session',
            name='scoresheet_pdf',
        ),
    ]
