# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 15:41
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Entity = apps.get_model('app', 'Entity')

    items = Entity.objects.filter(
        kind=11,
    )

    map = {
        'MAD': 400011,
        'ONT': 400013,
        'NED': 400012,
        'DIX': 400003,
        'PIO': 400010,
        'NSC': 400019,
        'JAD': 400008,
        'FHT': 400018,
        'LOL': 400009,
        'ILL': 400006,
        'CSD': 400002,
        'SLD': 400014,
        'CAR': 400007,
        'SUN': 400016,
        'EVG': 400004,
        'FWD': 400005,
        'RMD': 400017,
    }

    for item in items:
        if item.short_name == 'SWD':
            continue
        item.bhs_id = map[item.short_name]
        item.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20170327_2136'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
