# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20170328_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='kind',
            field=models.IntegerField(choices=[(31, 'Quartet'), (32, 'Chorus'), (33, 'Very Large Quartet'), (34, 'Mixed Group')]),
        ),
        migrations.AlterField(
            model_name='entity',
            name='kind',
            field=models.IntegerField(choices=[('Organization', [(1, 'Organization')]), ('District', [(11, 'District'), (12, 'Noncompetitive'), (13, 'Affiliate')]), ('Division', [(21, 'Division')]), ('Group', [(31, 'Quartet'), (32, 'Chorus'), (33, 'Very Large Quartet'), (34, 'Mixed Group')])], help_text='\n            The kind of organization.'),
        ),
        migrations.AlterField(
            model_name='office',
            name='kind',
            field=django_fsm.FSMIntegerField(choices=[('Organization', [(1, 'Organization')]), ('District', [(11, 'District'), (12, 'Noncompetitive'), (13, 'Affiliate')]), ('Division', [(21, 'Division')]), ('Group', [(31, 'Quartet'), (32, 'Chorus'), (33, 'Very Large Quartet'), (34, 'Mixed Group')])]),
        ),
        migrations.AlterField(
            model_name='session',
            name='kind',
            field=models.IntegerField(choices=[(31, 'Quartet'), (32, 'Chorus'), (33, 'Very Large Quartet'), (34, 'Mixed Group')], help_text='\n            The kind of session.  Generally this will be either quartet or chorus,\n            with the exception being International and Midwinter which hold exclusive\n            Youth and Senior sessions respectively.'),
        ),
    ]
