# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 15:41
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Membership = apps.get_model('app', 'Membership')

    Membership.objects.filter(
        entity__kind__lt=30,
    ).delete()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20170329_1606'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
