# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20170331_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='arrangers',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='catalog',
            name='composers',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='catalog',
            name='holders',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
