# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20170331_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='representing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performers_representing', to='app.Entity'),
        ),
    ]
