# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_performer_representing'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='representing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='app.Entity'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='representing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performers_representing', to='app.Entity'),
        ),
    ]
