# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 15:41
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Person = apps.get_model('app', 'Person')

    items = Person.objects.filter(
        memberships__entity__kind=32
    )
    for item in items:
        item.representing = item.memberships.filter(
            entity__kind=32,
        ).first().entity
        item.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20170402_2153'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
