# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20170402_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='catalog',
        ),
    ]
