# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_remove_submission_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repertory',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomen', models.CharField(editable=False, max_length=500)),
                ('status', models.IntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=0)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repertories', to='app.Catalog')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repertories', to='app.Entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='repertory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='app.Repertory'),
        ),
    ]
