# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_auto_20170403_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='bhs_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
