# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 15:41
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Entity = apps.get_model('app', 'Entity')
    Submission = apps.get_model('app', 'Submission')
    Catalog = apps.get_model('app', 'Catalog')
    Repertory = apps.get_model('app', 'Repertory')

    entities = Entity.objects.filter(
        memberships__entity__kind__in=[31, 32]
    )
    for entity in entities:
        submissions = Submission.objects.filter(
            performer__entity=entity,
        ).distinct()
        for submission in submissions:
            if submission.bhs_catalog:
                try:
                    catalog = Catalog.objects.get(
                        bhs_id=submission.bhs_catalog,
                    )
                except Catalog.DoesNotExist:
                    catalog, created = Catalog.objects.get_or_create(
                        title=submission.title,
                        bhs_id=submission.bhs_catalog,
                    )
            else:
                catalog, created = Catalog.objects.get_or_create(
                    title=submission.title,
                    bhs_id=submission.bhs_catalog,
                )
            repertory, created = Repertory.objects.get_or_create(
                catalog=catalog,
                entity=entity,
            )
            submission.repertory = repertory
            submission.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20170403_2118'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
