# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_auto_20170403_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='app.Catalog'),
        ),
    ]
