# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 15:41
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Submission = apps.get_model('app', 'Submission')
    Catalog = apps.get_model('app', 'Catalog')
    Repertory = apps.get_model('app', 'Repertory')

    submissions = Submission.objects.filter(
        repertory=None
    )
    for submission in submissions:
        catalog, created = Catalog.objects.get_or_create(
            title=submission.title,
            bhs_id=None,
        )
        repertory, created = Repertory.objects.get_or_create(
            catalog=catalog,
            entity=submission.performer.entity,
        )
        submission.repertory = repertory
        submission.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_song_catalog'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
