# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 15:41
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Catalog = apps.get_model('app', 'Catalog')

    catalogs = Catalog.objects.filter(
        title=''
    )
    catalogs.delete()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_auto_20170403_2202'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
