# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 15:41
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Officer = apps.get_model('app', 'Officer')

    officers = Officer.objects.filter(
        office__short_name='DRCJ'
    )
    for officer in officers:
        divisions = officer.entity.children.filter(
            kind=21,
        )
        for division in divisions:
            Officer.objects.create(
                person=officer.person,
                office=officer.office,
                entity=division,
            )


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_auto_20170404_0840'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
