# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_award_spots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='spots',
        ),
        migrations.AddField(
            model_name='organization',
            name='spots',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
