# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160510_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='is_advancing',
            field=models.BooleanField(default=False),
        ),
    ]
