# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160220_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='kind',
            field=models.IntegerField(blank=True, choices=[(b'International', [(0, b'International'), (50, b'Harmony Incorporated')]), (b'District', [(10, b'District'), (20, b'Noncompetitive'), (30, b'Affiliate')]), (b'Division', [(40, b'Division')]), (b'Chapter', [(60, b'Chapter')])], help_text=b'\n            The kind of organization.', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='level',
            field=models.IntegerField(blank=True, choices=[(0, b'International'), (1, b'District/Affiliates'), (2, b'Division'), (3, b'Chapter')], null=True),
        ),
    ]
