# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_performance_is_advancing'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='num_songs',
            field=models.IntegerField(default=2),
        ),
    ]
