# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 06:50
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160220_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=200, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=255, populate_from=b'name', unique=True)),
                ('status', django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Active'), (20, b'Inactive')], default=0)),
                ('status_monitor', model_utils.fields.MonitorField(default=django.utils.timezone.now, help_text=b'Status last updated', monitor=b'status')),
                ('kind', models.IntegerField(choices=[(1, b'Championship'), (2, b'Qualifier')], help_text=b'\n            The objective of the contest.')),
                ('subsession_id', models.IntegerField(blank=True, null=True)),
                ('subsession_text', models.CharField(blank=True, default=b'', max_length=255)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='api.Award')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='api.Session')),
            ],
            options={
                'ordering': ('session', 'award', 'kind'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='contest',
            unique_together=set([('session', 'award', 'kind')]),
        ),
    ]
