# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160515_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='person',
        ),
        migrations.AlterField(
            model_name='contest',
            name='champion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contests', to='api.Contestant'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='api.Person'),
        ),
        migrations.AlterField(
            model_name='round',
            name='mt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mic_tester', to='api.Group'),
        ),
        migrations.AlterField(
            model_name='session',
            name='aca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_aca', to='api.Certification'),
        ),
        migrations.AlterField(
            model_name='session',
            name='administrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_ca', to='api.Person'),
        ),
        migrations.AlterField(
            model_name='session',
            name='ca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_ca', to='api.Certification'),
        ),
    ]
