# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160516_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='kind',
            field=models.IntegerField(choices=[(10, b'Official'), (20, b'Practice'), (30, b'Composite')]),
        ),
    ]
