# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20160516_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='aca',
        ),
        migrations.RemoveField(
            model_name='session',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='session',
            name='ca',
        ),
    ]
