# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160516_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='chart',
        ),
    ]
