# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_award_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='size',
            new_name='size_range',
        ),
        migrations.RemoveField(
            model_name='award',
            name='is_novice',
        ),
    ]
