# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_song_chart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='asterisk_test',
        ),
        migrations.RemoveField(
            model_name='score',
            name='dixon_test',
        ),
    ]
