# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20160221_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='size_name',
            new_name='size',
        ),
    ]
