# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160221_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.Award'),
        ),
    ]
