# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20160519_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convention',
            name='division',
        ),
    ]
