# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_award_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='size',
            field=models.IntegerField(blank=True, choices=[(0, b'All'), (100, b'Plateau 1'), (110, b'Plateau 2'), (120, b'Plateau 3'), (130, b'Plateau 4'), (140, b'Plateau A'), (150, b'Plateau AA'), (160, b'Plateau AAA'), (170, b'Plateau AAAA'), (180, b'Plateau B'), (190, b'Plateau I'), (200, b'Plateau II'), (210, b'Plateau III'), (220, b'Plateau IV'), (230, b'Small')], null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Active'), (20, b'Inactive'), (30, b'Idiomatic')], default=0),
        ),
    ]
