# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20160221_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='long_name',
        ),
        migrations.AddField(
            model_name='award',
            name='idiom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
