# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20160221_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='kind',
            field=models.IntegerField(blank=True, choices=[(1, b'Quartet'), (2, b'Chorus'), (3, b'Seniors'), (4, b'Collegiate'), (5, b'Novice'), (6, b'Youth')], null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='kind',
            field=models.IntegerField(choices=[(1, b'Quartet'), (2, b'Chorus'), (3, b'Seniors'), (4, b'Collegiate'), (5, b'Novice'), (6, b'Youth')], help_text=b'\n            The kind of session.  Generally this will be either quartet or chorus, with the exception being International and Midwinter which hold exclusive Collegiate and Senior sessions respectively.'),
        ),
    ]
