# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20160222_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ('organization__level', 'organization__name', 'kind', 'size')},
        ),
        migrations.AlterField(
            model_name='award',
            name='season',
            field=models.IntegerField(blank=True, choices=[(1, b'International'), (2, b'Midwinter'), (3, b'Fall'), (4, b'Spring'), (9, b'Video')], null=True),
        ),
    ]
