# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20160519_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='qualifier_rounds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
