# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_award_qualifier_rounds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='cutoff',
            new_name='threshold',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='cutoff',
            new_name='threshold',
        ),
    ]
