# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20160223_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ('session', 'award')},
        ),
        migrations.AlterUniqueTogether(
            name='contest',
            unique_together=set([('session', 'award')]),
        ),
    ]
