# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20160223_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='kind',
        ),
    ]
