# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_contest_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestant',
            options={'ordering': ('contest', 'place')},
        ),
        migrations.AlterUniqueTogether(
            name='contestant',
            unique_together=set([('performer', 'contest')]),
        ),
    ]
