# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_session_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='advance',
            field=models.FloatField(blank=True, help_text=b'The score threshold to advance to next round (if any) in multi-round qualification.', null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='is_multi',
            field=models.BooleanField(default=False, help_text=b'Award spans conventions; must be determined manually.'),
        ),
        migrations.AddField(
            model_name='award',
            name='is_qualification_required',
            field=models.BooleanField(default=False, help_text=b'Boolean; true means qualification is required.'),
        ),
        migrations.AlterField(
            model_name='award',
            name='championship_rounds',
            field=models.IntegerField(help_text=b'Number of rounds to determine the championship'),
        ),
        migrations.AlterField(
            model_name='award',
            name='minimum',
            field=models.FloatField(blank=True, help_text=b'The minimum score required for qualification (if any.)', null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='qualifier_rounds',
            field=models.IntegerField(blank=True, help_text=b'Number of rounds to qualify for the award.', null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='threshold',
            field=models.FloatField(blank=True, help_text=b'The score threshold for automatic qualification (if any.)', null=True),
        ),
    ]
