# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 11:23
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20160519_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Invited'), (20, b'Accepted'), (30, b'Declined'), (40, b'Dropped'), (45, b'Evaluation'), (50, b'Official'), (55, b'Disqualified'), (60, b'Finished'), (90, b'Final')], default=0),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (4, b'Opened'), (8, b'Closed'), (10, b'Validated'), (20, b'Started'), (30, b'Finished'), (45, b'Published')], default=0),
        ),
    ]
