# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20160223_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='api.Contest'),
        ),
    ]
