# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 16:45
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20160223_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Scheduled'), (15, b'Upcoming'), (20, b'Started'), (30, b'Finished'), (50, b'Final')], default=0),
        ),
    ]
