# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20160224_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='is_senior',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='performer',
            name='is_youth',
            field=models.BooleanField(default=False),
        ),
    ]
