# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20160225_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_novice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='is_senior',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='is_youth',
            field=models.BooleanField(default=False),
        ),
    ]
