# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 12:17
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20160520_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Started'), (20, b'Finished')], default=0),
        ),
    ]
