# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20160225_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='is_novice',
            field=models.BooleanField(default=False),
        ),
    ]
