# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 12:39
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20160520_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (25, b'Cleared'), (30, b'Flagged'), (35, b'Revised'), (40, b'Confirmed')], default=0),
        ),
    ]
