# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_performer_is_novice'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_chorus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='is_collegiate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='is_quartet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='performer',
            name='is_chorus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='performer',
            name='is_collegiate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='performer',
            name='is_quartet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='is_chorus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='is_collegiate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='is_quartet',
            field=models.BooleanField(default=False),
        ),
    ]
