# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20160225_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_qualifier',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
