# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 17:00
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20160520_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Active'), (20, b'Inactive')], default=0),
        ),
    ]
