# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 05:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20160225_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='date',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, help_text=b'\n            The convention dates (will be replaced by start/end).', null=True),
        ),
    ]
