# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20160225_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='size',
        ),
    ]
