# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20160226_0753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='rounds',
            new_name='num_rounds',
        ),
        migrations.RemoveField(
            model_name='award',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='award',
            name='status_monitor',
        ),
        migrations.AlterField(
            model_name='award',
            name='size',
            field=models.IntegerField(blank=True, choices=[(100, b'Plateau 1'), (110, b'Plateau 2'), (120, b'Plateau 3'), (130, b'Plateau 4'), (140, b'Plateau A'), (150, b'Plateau AA'), (160, b'Plateau AAA'), (170, b'Plateau AAAA'), (180, b'Plateau B'), (190, b'Plateau I'), (200, b'Plateau II'), (210, b'Plateau III'), (220, b'Plateau IV'), (230, b'Small')], null=True),
        ),
    ]
