# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 20:09
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_performer_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (2, b'Scheduled'), (4, b'Opened'), (8, b'Closed'), (10, b'Validated'), (20, b'Started'), (30, b'Finished'), (45, b'Published')], default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Pre-Submitted'), (20, b'Post-Submitted')], default=0),
        ),
    ]
