# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20160226_0928'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='award',
            unique_together=set([('organization', 'is_improved', 'size', 'idiom', 'kind')]),
        ),
    ]
