# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20160226_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='status_monitor',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='status_monitor',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='status_monitor',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='status_monitor',
        ),
        migrations.RemoveField(
            model_name='convention',
            name='status_monitor',
        ),
        migrations.RemoveField(
            model_name='group',
            name='status_monitor',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='status_monitor',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='status_monitor',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='status_monitor',
        ),
        migrations.RemoveField(
            model_name='performer',
            name='status_monitor',
        ),
        migrations.RemoveField(
            model_name='person',
            name='status_monitor',
        ),
        migrations.RemoveField(
            model_name='round',
            name='status_monitor',
        ),
        migrations.RemoveField(
            model_name='score',
            name='status_monitor',
        ),
        migrations.RemoveField(
            model_name='session',
            name='status_monitor',
        ),
        migrations.RemoveField(
            model_name='song',
            name='status_monitor',
        ),
    ]
