# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20160520_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='season',
            new_name='championship_season',
        ),
        migrations.AddField(
            model_name='award',
            name='qualifier_season',
            field=models.IntegerField(blank=True, choices=[(1, b'International'), (2, b'Midwinter'), (3, b'Fall'), (4, b'Spring'), (9, b'Video')], null=True),
        ),
    ]
