# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20160226_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='slots',
        ),
    ]
