# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20160522_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(editable=False, help_text=b'Award Name (auto-generated).', max_length=255, unique=True),
        ),
    ]
