# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20160524_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text=b'\n            The name of the resource.', max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='kind',
            field=models.IntegerField(choices=[(1, b'Quartet'), (2, b'Chorus'), (10, b'Seniors'), (20, b'Collegiate'), (30, b'Youth')], help_text=b'\n            The kind of session.  Generally this will be either quartet or chorus,\n            with the exception being International and Midwinter which hold exclusive\n            Collegiate and Senior sessions respectively.'),
        ),
    ]
