# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20160524_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='is_district_representative',
            field=models.BooleanField(default=False, help_text=b'Boolean; true means the district rep qualifies.'),
        ),
    ]
