# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20160227_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='is_qualifier',
            field=models.BooleanField(default=False),
        ),
    ]
