# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20160227_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='is_novice',
            field=models.BooleanField(default=False),
        ),
    ]
