# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_award_is_novice'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='level',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
