# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20160526_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='status',
            field=models.IntegerField(choices=[(0, b'New'), (10, b'Scheduled'), (20, b'Confirmed'), (25, b'Validated'), (30, b'Final')], default=0),
        ),
    ]
