# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_award_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='level',
            field=models.IntegerField(blank=True, choices=[(0, b'International'), (1, b'District'), (2, b'Division'), (3, b'Chapter')], null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='level',
            field=models.IntegerField(blank=True, choices=[(0, b'International'), (1, b'District/Affiliates'), (2, b'Division'), (3, b'Chapter')], editable=False, null=True),
        ),
    ]
