# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20160228_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='age',
            field=models.IntegerField(blank=True, choices=[(10, b'Seniors'), (20, b'Collegiate'), (30, b'Youth')], null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='age',
            field=models.IntegerField(blank=True, choices=[(10, b'Seniors'), (20, b'Collegiate'), (30, b'Youth')], null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='age',
            field=models.IntegerField(blank=True, choices=[(10, b'Seniors'), (20, b'Collegiate'), (30, b'Youth')], null=True),
        ),
        migrations.AlterField(
            model_name='convention',
            name='level',
            field=models.IntegerField(blank=True, choices=[(0, b'International'), (1, b'District'), (2, b'Division'), (3, b'Chapter')], editable=False, null=True),
        ),
    ]
