# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 18:04
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20160526_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Validated'), (25, b'Cleared'), (30, b'Flagged'), (35, b'Revised'), (40, b'Confirmed')], default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Validated'), (40, b'Confirmed'), (50, b'Final')], default=0),
        ),
    ]
