# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20160228_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='season',
            field=models.IntegerField(blank=True, choices=[(1, b'International'), (2, b'Midwinter'), (3, b'Fall'), (4, b'Spring'), (9, b'Video')], null=True),
        ),
    ]
