# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_convention_season'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([('convention', 'kind', 'age')]),
        ),
    ]
