# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 16:49
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20160526_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Registered'), (20, b'Accepted'), (30, b'Declined'), (40, b'Dropped'), (50, b'Validated'), (52, b'Scratched'), (55, b'Disqualified'), (57, b'Started'), (60, b'Finished')], default=0),
        ),
    ]
