# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20160228_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='kind',
            field=models.IntegerField(blank=True, choices=[(1, b'Quartet'), (2, b'Chorus')], null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='kind',
            field=models.IntegerField(choices=[(1, b'Quartet'), (2, b'Chorus')], help_text=b'\n            The kind of session.  Generally this will be either quartet or chorus, with the exception being International and Midwinter which hold exclusive Collegiate and Senior sessions respectively.'),
        ),
    ]
