# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 17:12
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20160527_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Opened'), (15, b'Closed'), (35, b'Validated'), (42, b'Finished'), (45, b'Published')], default=0),
        ),
    ]
