# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20160228_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='subsession_text',
            new_name='stix_name',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='subsession_id',
            new_name='stix_num',
        ),
    ]
