# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20160527_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='num_rounds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
