# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_contest_num_rounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='num_rounds',
            field=models.IntegerField(default=1),
        ),
    ]
