# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20160229_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convention',
            name='kind',
        ),
    ]
