# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 03:28
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20160527_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Validated'), (38, b'Finished'), (40, b'Confirmed'), (50, b'Final')], default=0),
        ),
    ]
