# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_remove_convention_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestant',
            options={'ordering': ('contest', 'rank')},
        ),
        migrations.RenameField(
            model_name='contestant',
            old_name='place',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='performance',
            old_name='place',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='performer',
            old_name='place',
            new_name='rank',
        ),
    ]
