# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20160527_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestantScore',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.IntegerField(blank=True, editable=False, help_text=b'\n            The final ranking relative to this contest.', null=True)),
                ('mus_points', models.IntegerField(blank=True, editable=False, null=True)),
                ('prs_points', models.IntegerField(blank=True, editable=False, null=True)),
                ('sng_points', models.IntegerField(blank=True, editable=False, null=True)),
                ('total_points', models.IntegerField(blank=True, editable=False, null=True)),
                ('mus_score', models.FloatField(blank=True, editable=False, null=True)),
                ('prs_score', models.FloatField(blank=True, editable=False, null=True)),
                ('sng_score', models.FloatField(blank=True, editable=False, null=True)),
                ('total_score', models.FloatField(blank=True, editable=False, null=True)),
                ('contestant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Contestant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerformanceScore',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_advancing', models.BooleanField(default=False, editable=False)),
                ('rank', models.IntegerField(blank=True, editable=False, help_text=b'\n            The final ranking relative to this round.', null=True)),
                ('mus_points', models.IntegerField(blank=True, editable=False, null=True)),
                ('prs_points', models.IntegerField(blank=True, editable=False, null=True)),
                ('sng_points', models.IntegerField(blank=True, editable=False, null=True)),
                ('total_points', models.IntegerField(blank=True, editable=False, null=True)),
                ('mus_score', models.FloatField(blank=True, editable=False, null=True)),
                ('prs_score', models.FloatField(blank=True, editable=False, null=True)),
                ('sng_score', models.FloatField(blank=True, editable=False, null=True)),
                ('total_score', models.FloatField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerformerScore',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.IntegerField(blank=True, editable=False, help_text=b'\n            The final ranking relative to this round.', null=True)),
                ('mus_points', models.IntegerField(blank=True, editable=False, null=True)),
                ('prs_points', models.IntegerField(blank=True, editable=False, null=True)),
                ('sng_points', models.IntegerField(blank=True, editable=False, null=True)),
                ('total_points', models.IntegerField(blank=True, editable=False, null=True)),
                ('mus_score', models.FloatField(blank=True, editable=False, null=True)),
                ('prs_score', models.FloatField(blank=True, editable=False, null=True)),
                ('sng_score', models.FloatField(blank=True, editable=False, null=True)),
                ('total_score', models.FloatField(blank=True, editable=False, null=True)),
                ('performer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Performer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SongScore',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mus_points', models.IntegerField(blank=True, editable=False, null=True)),
                ('prs_points', models.IntegerField(blank=True, editable=False, null=True)),
                ('sng_points', models.IntegerField(blank=True, editable=False, null=True)),
                ('total_points', models.IntegerField(blank=True, editable=False, null=True)),
                ('mus_score', models.FloatField(blank=True, editable=False, null=True)),
                ('prs_score', models.FloatField(blank=True, editable=False, null=True)),
                ('sng_score', models.FloatField(blank=True, editable=False, null=True)),
                ('total_score', models.FloatField(blank=True, editable=False, null=True)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Song')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='performance',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (5, b'Validated'), (10, b'Started'), (20, b'Finished'), (30, b'Entered')], default=0),
        ),
        migrations.AddField(
            model_name='performancescore',
            name='performance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Performance'),
        ),
    ]
