# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20160527_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongScore',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Song')),
                ('d_mus_points', models.IntegerField(blank=True, editable=False, null=True)),
                ('d_prs_points', models.IntegerField(blank=True, editable=False, null=True)),
                ('d_sng_points', models.IntegerField(blank=True, editable=False, null=True)),
                ('d_total_points', models.IntegerField(blank=True, editable=False, null=True)),
                ('d_mus_score', models.FloatField(blank=True, editable=False, null=True)),
                ('d_prs_score', models.FloatField(blank=True, editable=False, null=True)),
                ('d_sng_score', models.FloatField(blank=True, editable=False, null=True)),
                ('d_total_score', models.FloatField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
