# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20160601_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='num_rounds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
