# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20160229_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='cutoff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='cutoff',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (30, b'Did Not Qualify'), (50, b'Qualified'), (90, b'Final')], default=0),
        ),
    ]
