# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_songscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceScore',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('performance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Performance')),
                ('rank', models.IntegerField(blank=True, editable=False, help_text=b'\n            The final ranking relative to this round.', null=True)),
                ('mus_points', models.IntegerField(blank=True, editable=False, null=True)),
                ('prs_points', models.IntegerField(blank=True, editable=False, null=True)),
                ('sng_points', models.IntegerField(blank=True, editable=False, null=True)),
                ('total_points', models.IntegerField(blank=True, editable=False, null=True)),
                ('mus_score', models.FloatField(blank=True, editable=False, null=True)),
                ('prs_score', models.FloatField(blank=True, editable=False, null=True)),
                ('sng_score', models.FloatField(blank=True, editable=False, null=True)),
                ('total_score', models.FloatField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
