# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_session_num_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='actual_finish',
            field=models.DateTimeField(blank=True, help_text=b'\n            The actual performance window.', null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='actual_start',
            field=models.DateTimeField(blank=True, help_text=b'\n            The actual performance window.', null=True),
        ),
    ]
