# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_remove_contest_cutoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='kind',
            field=models.IntegerField(choices=[(1, b'Quartet'), (2, b'Chorus')]),
        ),
        migrations.AlterField(
            model_name='award',
            name='level',
            field=models.IntegerField(choices=[(0, b'International'), (1, b'District/Affiliates'), (2, b'Division'), (3, b'Chapter')], editable=False),
        ),
        migrations.AlterField(
            model_name='award',
            name='season',
            field=models.IntegerField(choices=[(1, b'International'), (2, b'Midwinter'), (3, b'Fall'), (4, b'Spring'), (9, b'Video')]),
        ),
        migrations.AlterField(
            model_name='award',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Active'), (20, b'Inactive')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='award',
            unique_together=set([('organization', 'is_improved', 'size', 'idiom', 'kind', 'age')]),
        ),
    ]
