# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 13:40
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20160603_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (2, b'Listed'), (4, b'Opened'), (8, b'Closed'), (10, b'Validated'), (20, b'Quarters Started'), (26, b'Quarters Finished'), (28, b'Quarters Published'), (30, b'Semis Started'), (36, b'Semis Finished'), (38, b'Semis Published'), (40, b'Finals Started'), (46, b'Finals Finished'), (48, b'Finals Published')], default=0),
        ),
    ]
