# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20160604_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='current',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_round', to='api.Round'),
        ),
    ]
