# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20160301_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ('level', 'is_primary', 'kind', 'age', 'size')},
        ),
        migrations.RemoveField(
            model_name='award',
            name='season',
        ),
    ]
