# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20160301_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='aca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_aca', to='api.Person'),
        ),
        migrations.AlterField(
            model_name='session',
            name='administrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_ca', to='api.Person'),
        ),
    ]
