# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 20:23
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import timezone_field.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20160301_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=255, populate_from=b'name', unique=True)),
                ('timezone', timezone_field.fields.TimeZoneField(default=b'US/Pacific', help_text=b'\n            The local timezone of the venue.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='convention',
            name='timezone',
        ),
    ]
