# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20160301_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='venue',
            field=models.ForeignKey(blank=True, help_text=b'\n            The venue for the convention.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conventions', to='api.Venue'),
        ),
    ]
