# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 13:35
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20160604_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Drawn'), (15, b'Validated'), (20, b'Started'), (25, b'Finished'), (50, b'Published')], default=0),
        ),
    ]
