# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_convention_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='kind',
            field=models.IntegerField(choices=[(1, b'Quartet'), (2, b'Chorus'), (10, b'Seniors'), (20, b'Collegiate'), (30, b'Youth')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='kind',
            field=models.IntegerField(choices=[(1, b'Quartet'), (2, b'Chorus'), (10, b'Seniors'), (20, b'Collegiate'), (30, b'Youth')], help_text=b'\n            The kind of session.  Generally this will be either quartet or chorus, with the exception being International and Midwinter which hold exclusive Collegiate and Senior sessions respectively.'),
        ),
    ]
