# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20160605_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancescore',
            name='slot',
            field=models.IntegerField(blank=True, editable=False, help_text=b'\n            The final ranking relative to this round.', null=True),
        ),
    ]
