# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_performancescore_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestantscore',
            name='contestant',
        ),
        migrations.RemoveField(
            model_name='performancescore',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='performerscore',
            name='performer',
        ),
        migrations.RemoveField(
            model_name='songscore',
            name='song',
        ),
        migrations.DeleteModel(
            name='ContestantScore',
        ),
        migrations.DeleteModel(
            name='PerformanceScore',
        ),
        migrations.DeleteModel(
            name='PerformerScore',
        ),
        migrations.DeleteModel(
            name='SongScore',
        ),
    ]
