# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20160302_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arranger',
            name='part',
        ),
        migrations.AlterField(
            model_name='arranger',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrangers', to='api.Catalog'),
        ),
    ]
