# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 16:37
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20160607_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Eligible'), (20, b'Ineligible'), (40, b'District Representative'), (50, b'Qualified'), (55, b'Validated'), (60, b'Finished'), (70, b'Scratched'), (80, b'Disqualified'), (90, b'Published')], default=0),
        ),
        migrations.AlterField(
            model_name='performance',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (5, b'Validated'), (10, b'Started'), (20, b'Finished'), (30, b'Entered'), (90, b'Published')], default=0),
        ),
        migrations.AlterField(
            model_name='performer',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Registered'), (20, b'Accepted'), (30, b'Declined'), (40, b'Dropped'), (50, b'Validated'), (52, b'Scratched'), (55, b'Disqualified'), (57, b'Started'), (60, b'Finished'), (90, b'Published')], default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Validated'), (38, b'Finished'), (40, b'Confirmed'), (50, b'Final'), (90, b'Published')], default=0),
        ),
    ]
