# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20160302_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arranger',
            name='name',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
