# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20160302_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='age',
        ),
        migrations.RemoveField(
            model_name='session',
            name='age',
        ),
    ]
