# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_session_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='champion',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
