# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20160302_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='history',
        ),
        migrations.RemoveField(
            model_name='session',
            name='history_monitor',
        ),
        migrations.RemoveField(
            model_name='session',
            name='scoresheet_csv',
        ),
        migrations.AlterUniqueTogether(
            name='award',
            unique_together=set([('organization', 'is_improved', 'is_novice', 'size', 'idiom', 'kind')]),
        ),
    ]
