# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20160609_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='num_rounds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
