# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 14:34
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_auto_20160611_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (2, b'Listed'), (4, b'Opened'), (8, b'Closed'), (10, b'Validated'), (20, b'Started'), (30, b'Finished'), (45, b'Published')], default=0),
        ),
    ]
