# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_auto_20160302_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ('level', 'organization', '-is_primary', 'kind', 'size')},
        ),
    ]
