# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20160302_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Chapter'),
        ),
    ]
