# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20160615_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='slot',
            new_name='num',
        ),
    ]
