# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20160617_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=255, unique=True)),
                ('status', django_fsm.FSMIntegerField(choices=[(0, b'New')], default=0)),
                ('num', models.IntegerField(default=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.DateTimeField(blank=True, null=True)),
                ('arrive', models.DateTimeField(blank=True, null=True)),
                ('depart', models.DateTimeField(blank=True, null=True)),
                ('backstage', models.DateTimeField(blank=True, null=True)),
                ('onstage', models.DateTimeField(blank=True, null=True)),
                ('performance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='api.Submission')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='api.Round')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together=set([('round', 'num')]),
        ),
    ]
