# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 03:19
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_person_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=255, populate_from=b'name', unique=True)),
                ('status', models.IntegerField(choices=[(0, b'New'), (10, b'Active'), (20, b'Inactive')], default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.Chapter')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.Person')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([('chapter', 'person')]),
        ),
    ]
