# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20160617_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='performance',
        ),
    ]
