# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 05:54
from __future__ import unicode_literals

import apps.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20160302_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='entry_form',
            field=models.FileField(blank=True, help_text=b'\n            The cj20 entry form.', null=True, upload_to=apps.api.models.generate_image_filename),
        ),
        migrations.AddField(
            model_name='session',
            name='song_list',
            field=models.FileField(blank=True, help_text=b'\n            The cj20 song list.', null=True, upload_to=apps.api.models.generate_image_filename),
        ),
    ]
