# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20160302_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=255, unique=True)),
                ('is_generic', models.BooleanField(default=False)),
                ('is_parody', models.BooleanField(default=False)),
                ('is_medley', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('arranger', models.CharField(blank=True, max_length=200)),
                ('composer', models.CharField(blank=True, max_length=200)),
                ('lyricist', models.CharField(blank=True, max_length=200)),
                ('bhs_id', models.IntegerField(blank=True, null=True)),
                ('bhs_published', models.DateField(blank=True, null=True)),
                ('bhs_arranger', models.CharField(blank=True, max_length=200)),
                ('bhs_fee', models.FloatField(blank=True, null=True)),
                ('bhs_songname', models.CharField(blank=True, max_length=200)),
                ('bhs_copyright_date', models.CharField(blank=True, max_length=200)),
                ('bhs_copyright_owner', models.CharField(blank=True, max_length=200)),
                ('bhs_difficulty', models.IntegerField(blank=True, choices=[(1, b'Very Easy'), (2, b'Easy'), (3, b'Medium'), (4, b'Hard'), (5, b'Very Hard')], null=True)),
                ('bhs_tempo', models.IntegerField(blank=True, choices=[(1, b'Ballad'), (2, b'Uptune'), (3, b'Mixed')], null=True)),
                ('bhs_medley', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='catalog',
            name='tune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='api.Tune'),
        ),
    ]
