# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_auto_20160618_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set([('performance', 'num')]),
        ),
    ]
