# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 17:03
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_auto_20160109_0212'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organization',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
