# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_auto_20160302_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='tune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charts', to='api.Tune'),
        ),
    ]
