# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20160118_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='kind',
            field=models.IntegerField(blank=True, choices=[(1, b'Quartet'), (2, b'Chorus'), (3, b'Seniors'), (4, b'Collegiate'), (5, b'Novice')], null=True),
        ),
    ]
