# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20160620_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='order',
            field=models.IntegerField(blank=True, choices=[(1, b'First'), (2, b'Second')], null=True),
        ),
    ]
