# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 00:06
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20160119_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='dates',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='dates',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Built'), (20, b'Started'), (30, b'Finished'), (50, b'Final')], default=0),
        ),
    ]
