# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_song_chart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='tune',
        ),
    ]
