# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20160620_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='num_rounds',
            field=models.IntegerField(),
        ),
    ]
