# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20160119_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panels', to='api.Person'),
        ),
    ]
