# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20160620_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='championship_season',
            field=models.IntegerField(blank=True, choices=[(1, b'Summer'), (2, b'Midwinter'), (3, b'Fall'), (4, b'Spring'), (9, b'Video')], null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='qualifier_season',
            field=models.IntegerField(blank=True, choices=[(1, b'Summer'), (2, b'Midwinter'), (3, b'Fall'), (4, b'Spring'), (9, b'Video')], null=True),
        ),
    ]
