# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_remove_catalog_tune'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='tune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='api.Tune'),
        ),
    ]
