# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_catalog_tune'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='tune',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='tune',
        ),
        migrations.RemoveField(
            model_name='song',
            name='tune',
        ),
    ]
