# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 17:19
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20160119_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (20, b'Started'), (25, b'Finished'), (30, b'Flagged'), (35, b'Validated'), (40, b'Confirmed'), (50, b'Final')], default=0),
        ),
    ]
