# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20160620_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='mus_points',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='mus_score',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='prs_points',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='prs_score',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='sng_points',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='sng_score',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='total_score',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='actual',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='is_advancing',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='scheduled',
        ),
        migrations.RemoveField(
            model_name='performer',
            name='soa',
        ),
        migrations.RemoveField(
            model_name='song',
            name='order',
        ),
    ]
