# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20160122_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text=b'\n            Flag field for Dixon test failure.'),
        ),
    ]
