# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20160624_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='season',
            field=models.IntegerField(choices=[(1, b'Summer'), (2, b'Midwinter'), (3, b'Fall'), (4, b'Spring'), (9, b'Video')]),
        ),
    ]
