# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20160303_1144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tune',
        ),
    ]
