# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 18:45
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_performance_is_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Built'), (15, b'Ready'), (20, b'Started'), (25, b'Finished'), (28, b'Confirmed'), (30, b'Final')], default=0),
        ),
    ]
