# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_delete_tune'),
    ]

    operations = [
        migrations.AddField(
            model_name='arranger',
            name='chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrangers', to='api.Chart'),
        ),
        migrations.AddField(
            model_name='setlist',
            name='chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setlist', to='api.Chart'),
        ),
    ]
