# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20160624_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='num',
            field=models.IntegerField(default=1),
        ),
    ]
