# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20160122_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='is_flagged',
        ),
    ]
