# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20160625_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='performance',
        ),
    ]
