# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20160303_1146'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='arranger',
            unique_together=set([('chart', 'person')]),
        ),
        migrations.AlterUniqueTogether(
            name='setlist',
            unique_together=set([('performer', 'chart')]),
        ),
    ]
