# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 19:26
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_remove_performance_is_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Started'), (20, b'Finished'), (30, b'Entered'), (40, b'Validated'), (50, b'Flagged'), (60, b'Confirmed'), (90, b'Final')], default=0),
        ),
    ]
