# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_remove_slot_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances', to='api.Slot', unique=True),
        ),
    ]
