# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_auto_20160303_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arranger',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='setlist',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='song',
            name='catalog',
        ),
    ]
