# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_performance_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='prelim',
            field=models.FloatField(blank=True, help_text=b'\n            The incoming prelim score.', null=True),
        ),
    ]
