# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_auto_20160303_1156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catalog',
        ),
    ]
