# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 23:30
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_auto_20160122_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Built'), (20, b'Started'), (25, b'Finished'), (28, b'Ranked'), (30, b'Final')], default=0),
        ),
        migrations.AlterField(
            model_name='performance',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Started'), (20, b'Finished'), (30, b'Entered'), (40, b'Flagged'), (50, b'Accepted'), (90, b'Final')], default=0),
        ),
        migrations.AlterField(
            model_name='round',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Built'), (15, b'Ready'), (20, b'Started'), (25, b'Finished'), (28, b'Ranked'), (30, b'Final')], default=0),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Built'), (20, b'Started'), (25, b'Ranked'), (30, b'Finished'), (50, b'Final')], default=0),
        ),
    ]
