# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_delete_catalog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chart',
            unique_together=set([('title', 'arranger', 'is_generic')]),
        ),
    ]
