# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_auto_20160122_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='prelim',
            field=models.FloatField(blank=True, help_text=b'\n            The incoming prelim score.', null=True),
        ),
        migrations.AlterField(
            model_name='performer',
            name='seed',
            field=models.IntegerField(blank=True, help_text=b'\n            The incoming rank based on prelim score.', null=True),
        ),
    ]
