# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_auto_20160124_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='kind',
        ),
        migrations.AddField(
            model_name='person',
            name='bhs_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='bhs_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='person',
            name='bhs_member_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='bhs_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='bhs_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='bhs_state',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
