# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_auto_20160303_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='season',
            field=models.IntegerField(blank=True, choices=[(1, b'International'), (2, b'Midwinter'), (3, b'Fall'), (4, b'Spring'), (9, b'Video')], null=True),
        ),
    ]
