# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_performer_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='api.Chart'),
        ),
    ]
