# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 17:47
from __future__ import unicode_literals

import apps.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_song_chart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['round__kind']},
        ),
        migrations.AddField(
            model_name='performer',
            name='csa_pdf',
            field=models.FileField(blank=True, help_text=b'\n            The historical PDF CSA.', null=True, upload_to=apps.api.models.generate_image_filename),
        ),
    ]
