# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_auto_20160125_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='goal',
            field=models.IntegerField(choices=[(1, b'Championship'), (2, b'Qualifier')], help_text=b'\n            The objective of the contest.'),
        ),
    ]
