# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_auto_20160303_1242'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='award',
            unique_together=set([('organization', 'is_improved', 'is_novice', 'size', 'scope', 'idiom', 'kind')]),
        ),
    ]
