# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 19:14
from __future__ import unicode_literals

import apps.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_auto_20160705_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='ann_pdf',
            field=models.FileField(blank=True, help_text=b'\n            The announcement PDF.', null=True, upload_to=apps.api.models.generate_image_filename),
        ),
    ]
