# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_round_ann_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='mus_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='mus_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='prs_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='prs_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='sng_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='sng_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
