# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_auto_20160125_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges', to='api.Session'),
        ),
    ]
