# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_auto_20160706_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['performance', 'num']},
        ),
    ]
