# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_auto_20160126_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='judge',
            options={'ordering': ('session', 'category', 'kind', 'slot')},
        ),
        migrations.AlterUniqueTogether(
            name='judge',
            unique_together=set([('session', 'category', 'kind', 'slot')]),
        ),
    ]
