# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_auto_20160303_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ('level', 'organization', '-is_primary', 'kind', 'size', 'scope')},
        ),
        migrations.RemoveField(
            model_name='performance',
            name='position',
        ),
    ]
