# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_auto_20160303_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='slot',
            field=models.IntegerField(),
        ),
    ]
