# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_auto_20160126_1516'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together=set([('round', 'position')]),
        ),
    ]
