# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 23:42
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_auto_20160304_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='setlist',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New')], default=0),
        ),
    ]
