# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Slot'),
        ),
    ]
