# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_setlist_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='bhs_group_id',
            new_name='bhs_id',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_id',
            new_name='bhs_id',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='bhs_group_id',
            new_name='bhs_id',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='member',
            new_name='bhs_id',
        ),
        migrations.AlterField(
            model_name='chart',
            name='bhs_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
