# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_auto_20160127_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='num',
        ),
    ]
