# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 17:57
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_remove_score_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (90, b'Final')], default=0),
        ),
    ]
