# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-05 18:57
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_auto_20160305_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=255, populate_from=b'name', unique=True)),
                ('part', models.IntegerField(choices=[(1, b'Tenor'), (2, b'Lead'), (3, b'Baritone'), (4, b'Bass'), (5, b'Director')])),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.Performer')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.Person')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set([('performer', 'person')]),
        ),
    ]
