# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-05 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_auto_20160305_1057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='director',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='director',
            name='performer',
        ),
        migrations.RemoveField(
            model_name='director',
            name='person',
        ),
        migrations.AlterUniqueTogether(
            name='singer',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='singer',
            name='performer',
        ),
        migrations.RemoveField(
            model_name='singer',
            name='person',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='Singer',
        ),
    ]
