# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_auto_20160713_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='kind',
            field=models.IntegerField(blank=True, choices=[(10, b'Chair'), (20, b'Past Chair'), (30, b'Specialist'), (40, b'Certified'), (50, b'Candidate')], null=True),
        ),
    ]
