# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_certification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bhs_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nomen',
            field=models.TextField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
