# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_auto_20160128_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='is_flagged',
        ),
        migrations.AddField(
            model_name='score',
            name='dixon_test',
            field=models.NullBooleanField(),
        ),
    ]
