# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-05 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_auto_20160305_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New')], default=0),
        ),
        migrations.AlterField(
            model_name='setlist',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setlists', to='api.Chart'),
        ),
        migrations.AlterField(
            model_name='setlist',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setlists', to='api.Performer'),
        ),
    ]
