# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_auto_20160714_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
