# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-05 23:28
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_auto_20160305_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New')], default=0),
        ),
    ]
