# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_auto_20160128_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='dixon_test',
        ),
        migrations.AddField(
            model_name='score',
            name='passes_dixon',
            field=models.BooleanField(default=True),
        ),
    ]
