# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_auto_20160714_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='nomen',
            field=models.TextField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='nomen',
            field=models.TextField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
