# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_auto_20160128_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='rounds',
        ),
    ]
