# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_chart_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='slug',
        ),
    ]
