# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_auto_20160714_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='chap_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='id_name',
        ),
    ]
