# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_auto_20160714_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='nomen',
            field=models.TextField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='nomen',
            field=models.TextField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='nomen',
            field=models.TextField(editable=False, max_length=255, unique=True),
        ),
    ]
