# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 06:01
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_remove_contest_rounds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='num_rounds',
        ),
        migrations.AlterField(
            model_name='convention',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Scheduled'), (20, b'Started'), (30, b'Finished'), (50, b'Final')], default=0),
        ),
    ]
