# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_auto_20160715_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='level',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='date',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='bhs_address',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='bhs_chapter_code',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='bhs_chapter_name',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='bhs_city',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='bhs_contact',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='bhs_district',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='bhs_group_name',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='bhs_name',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='bhs_phone',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='bhs_state',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='bhs_venue',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='bhs_website',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='bhs_zip',
        ),
        migrations.AddField(
            model_name='contest',
            name='champ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contests', to='api.Performer'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='kind',
            field=models.IntegerField(choices=[(10, b'Chair'), (20, b'Past Chair'), (30, b'Specialist'), (40, b'Certified'), (50, b'Candidate'), (60, b'Retired'), (70, b'Lapsed')]),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='bhs_id',
            field=models.IntegerField(unique=True),
        ),
    ]
