# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_auto_20160306_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_judge',
        ),
        migrations.AlterField(
            model_name='performer',
            name='prelim',
            field=models.FloatField(blank=True, editable=False, help_text=b'\n            The incoming prelim score.', null=True),
        ),
        migrations.AlterField(
            model_name='performer',
            name='seed',
            field=models.IntegerField(blank=True, editable=False, help_text=b'\n            The incoming rank based on prelim score.', null=True),
        ),
    ]
