# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_auto_20160129_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='year',
            field=models.IntegerField(editable=False),
        ),
    ]
