# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_auto_20160306_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='bhs_member_id',
        ),
    ]
