# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_auto_20160130_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='asterisk_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='dixon_test',
            field=models.NullBooleanField(),
        ),
    ]
