# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_remove_person_bhs_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='is_composite',
        ),
        migrations.RemoveField(
            model_name='session',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='song',
            name='arranger',
        ),
        migrations.RemoveField(
            model_name='song',
            name='title',
        ),
        migrations.AlterField(
            model_name='score',
            name='category',
            field=models.IntegerField(choices=[(1, b'Music'), (2, b'Presentation'), (3, b'Singing')]),
        ),
    ]
