# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_auto_20160715_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='date',
        ),
        migrations.AlterField(
            model_name='organization',
            name='kind',
            field=models.IntegerField(choices=[(b'International', [(0, b'International'), (50, b'Harmony Incorporated')]), (b'District', [(10, b'District'), (20, b'Noncompetitive'), (30, b'Affiliate')]), (b'Division', [(40, b'Division')]), (b'Chapter', [(60, b'Chapter')])], help_text=b'\n            The kind of organization.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='level',
            field=models.IntegerField(choices=[(0, b'International'), (1, b'District/Affiliates'), (2, b'Division'), (3, b'Chapter')]),
        ),
    ]
