# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_auto_20160130_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='asterisk_test',
            field=models.NullBooleanField(),
        ),
    ]
