# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_auto_20160306_1941'),
    ]

    operations = [
        migrations.RenameModel('Setlist', 'Submission')
    ]
