# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_auto_20160715_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='date',
        ),
        migrations.AlterField(
            model_name='session',
            name='kind',
            field=models.IntegerField(choices=[(1, b'Quartet'), (2, b'Chorus'), (10, b'Seniors'), (20, b'Collegiate'), (30, b'Youth')], help_text=b'\n            The kind of session.  Generally this will be either quartet or chorus,\n            with the exception being International and Midwinter which hold exclusive\n            Youth and Senior sessions respectively.'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='num',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='role',
            name='date',
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set([('group', 'person', 'start_date', 'end_date')]),
        ),
        migrations.RemoveField(
            model_name='round',
            name='date',
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together=set([('session', 'kind', 'num')]),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('song', 'judge')]),
        ),
    ]
