# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_auto_20160130_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='is_composite',
            field=models.BooleanField(default=False),
        ),
    ]
