# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_auto_20160306_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.Chart'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.Performer'),
        ),
    ]
