# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_auto_20160716_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='champion',
        ),
        migrations.RemoveField(
            model_name='convention',
            name='date',
        ),
        migrations.RemoveField(
            model_name='group',
            name='date',
        ),
    ]
