# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_auto_20160306_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestant',
            options={'ordering': ('contest', '-total_points')},
        ),
        migrations.AlterModelOptions(
            name='performer',
            options={'ordering': ('session', '-total_points', 'group')},
        ),
    ]
