# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_auto_20160716_0812'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set([('group', 'person', 'start_date', 'end_date')]),
        ),
    ]
