# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_score_is_composite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='round',
        ),
    ]
