# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_remove_judge_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='bhs_chapter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='group',
            name='bhs_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='group',
            name='bhs_website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
