# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_auto_20160309_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='champion',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='api.Contestant'),
        ),
    ]
