# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 17:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_contest_champion'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='date',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, help_text=b'\n            Active Dates', null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.Group'),
        ),
        migrations.AlterField(
            model_name='role',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Active'), (20, b'Inactive')], default=0),
        ),
    ]
