# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_auto_20160204_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='bhs_chapter',
            new_name='bhs_chapter_code',
        ),
        migrations.AddField(
            model_name='group',
            name='bhs_chapter_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
