# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import django_fsm
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_auto_20160716_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=255, unique=True)),
                ('status', django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Active')], default=0)),
                ('bhs_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('published', models.DateField(blank=True, null=True)),
                ('arranger', models.CharField(blank=True, max_length=200)),
                ('arranger_fee', models.FloatField(blank=True, null=True)),
                ('difficulty', models.IntegerField(blank=True, choices=[(1, b'Very Easy'), (2, b'Easy'), (3, b'Medium'), (4, b'Hard'), (5, b'Very Hard')], null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(1, b'Male'), (2, b'Female'), (3, b'Mixed')], null=True)),
                ('tempo', models.IntegerField(blank=True, choices=[(1, b'Ballad'), (2, b'Uptune'), (3, b'Mixed')], null=True)),
                ('is_medley', models.BooleanField(default=False)),
                ('is_learning', models.BooleanField(default=False)),
                ('voicing', models.IntegerField(blank=True, choices=[(1, b'Barbershop'), (2, b'Chorus + Quartet'), (3, b'Double Quartet'), (4, b'Ensemble + Soloist')], null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
