# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_auto_20160204_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.Contest'),
        ),
    ]
