# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_auto_20160310_0920'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set([('group', 'person')]),
        ),
    ]
