# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_auto_20160716_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='chart',
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='submission',
            name='chart',
        ),
    ]
