# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_auto_20160310_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='minimum',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
