# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-13 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_award_minimum'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chart',
            unique_together=set([('title', 'arranger', 'bhs_id')]),
        ),
    ]
