# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_auto_20160204_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='member',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
