# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_auto_20160716_2213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
