# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 17:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_auto_20160206_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='email',
            field=models.EmailField(blank=True, help_text=b'\n            The contact email of the resource.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='facebook',
            field=models.URLField(blank=True, help_text=b'\n            The facebook URL of the resource.', null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='twitter',
            field=models.CharField(blank=True, help_text=b'\n            The twitter handle (in form @twitter_handle) of the resource.', max_length=16, null=True, validators=[django.core.validators.RegexValidator(message=b'\n                    Must be a single Twitter handle\n                    in the form `@twitter_handle`.\n                ', regex=b'@([A-Za-z0-9_]+)')]),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='website',
            field=models.URLField(blank=True, help_text=b'\n            The website URL of the resource.', null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='email',
            field=models.EmailField(blank=True, help_text=b'\n            The contact email of the resource.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='facebook',
            field=models.URLField(blank=True, help_text=b'\n            The facebook URL of the resource.', null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='twitter',
            field=models.CharField(blank=True, help_text=b'\n            The twitter handle (in form @twitter_handle) of the resource.', max_length=16, null=True, validators=[django.core.validators.RegexValidator(message=b'\n                    Must be a single Twitter handle\n                    in the form `@twitter_handle`.\n                ', regex=b'@([A-Za-z0-9_]+)')]),
        ),
        migrations.AlterField(
            model_name='group',
            name='website',
            field=models.URLField(blank=True, help_text=b'\n            The website URL of the resource.', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, help_text=b'\n            The contact email of the resource.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='facebook',
            field=models.URLField(blank=True, help_text=b'\n            The facebook URL of the resource.', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='twitter',
            field=models.CharField(blank=True, help_text=b'\n            The twitter handle (in form @twitter_handle) of the resource.', max_length=16, null=True, validators=[django.core.validators.RegexValidator(message=b'\n                    Must be a single Twitter handle\n                    in the form `@twitter_handle`.\n                ', regex=b'@([A-Za-z0-9_]+)')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='website',
            field=models.URLField(blank=True, help_text=b'\n            The website URL of the resource.', null=True),
        ),
    ]
