# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_delete_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='level',
            field=models.IntegerField(choices=[(0, b'International'), (1, b'District'), (2, b'Division'), (3, b'Chapter')]),
        ),
    ]
