# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-13 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_auto_20160312_2111'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chart',
            unique_together=set([]),
        ),
    ]
