# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 19:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_auto_20160206_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='email',
            field=models.EmailField(blank=True, default=b'', help_text=b'\n            The contact email of the resource.', max_length=254),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='facebook',
            field=models.URLField(blank=True, default=b'', help_text=b'\n            The facebook URL of the resource.'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='location',
            field=models.CharField(blank=True, default=b'', help_text=b'\n            The geographical location of the resource.', max_length=200),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=b'', help_text=b'\n            The phone number of the resource.  Include country code.', max_length=128),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='twitter',
            field=models.CharField(blank=True, default=b'', help_text=b'\n            The twitter handle (in form @twitter_handle) of the resource.', max_length=16, validators=[django.core.validators.RegexValidator(message=b'\n                    Must be a single Twitter handle\n                    in the form `@twitter_handle`.\n                ', regex=b'@([A-Za-z0-9_]+)')]),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='website',
            field=models.URLField(blank=True, default=b'', help_text=b'\n            The website URL of the resource.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='email',
            field=models.EmailField(blank=True, default=b'', help_text=b'\n            The contact email of the resource.', max_length=254),
        ),
        migrations.AlterField(
            model_name='group',
            name='facebook',
            field=models.URLField(blank=True, default=b'', help_text=b'\n            The facebook URL of the resource.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='location',
            field=models.CharField(blank=True, default=b'', help_text=b'\n            The geographical location of the resource.', max_length=200),
        ),
        migrations.AlterField(
            model_name='group',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=b'', help_text=b'\n            The phone number of the resource.  Include country code.', max_length=128),
        ),
        migrations.AlterField(
            model_name='group',
            name='twitter',
            field=models.CharField(blank=True, default=b'', help_text=b'\n            The twitter handle (in form @twitter_handle) of the resource.', max_length=16, validators=[django.core.validators.RegexValidator(message=b'\n                    Must be a single Twitter handle\n                    in the form `@twitter_handle`.\n                ', regex=b'@([A-Za-z0-9_]+)')]),
        ),
        migrations.AlterField(
            model_name='group',
            name='website',
            field=models.URLField(blank=True, default=b'', help_text=b'\n            The website URL of the resource.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, default=b'', help_text=b'\n            The contact email of the resource.', max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='facebook',
            field=models.URLField(blank=True, default=b'', help_text=b'\n            The facebook URL of the resource.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.CharField(blank=True, default=b'', help_text=b'\n            The geographical location of the resource.', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=b'', help_text=b'\n            The phone number of the resource.  Include country code.', max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='twitter',
            field=models.CharField(blank=True, default=b'', help_text=b'\n            The twitter handle (in form @twitter_handle) of the resource.', max_length=16, validators=[django.core.validators.RegexValidator(message=b'\n                    Must be a single Twitter handle\n                    in the form `@twitter_handle`.\n                ', regex=b'@([A-Za-z0-9_]+)')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='website',
            field=models.URLField(blank=True, default=b'', help_text=b'\n            The website URL of the resource.'),
        ),
    ]
