# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_auto_20160313_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convention',
            options={'ordering': ['date', 'organization__name']},
        ),
        migrations.AlterField(
            model_name='convention',
            name='division',
            field=models.IntegerField(blank=True, choices=[(200, b'Division I'), (210, b'Division II'), (220, b'Division III'), (230, b'Division IV'), (240, b'Division V'), (250, b'Arizona Division'), (260, b'NE/NW Divisions'), (270, b'SE/SW Divisions'), (280, b'Division One/Packerland Divisions'), (290, b'Northern Plains Division'), (300, b'10,000 Lakes and Southwest Divisions'), (310, b'Atlantic Division'), (320, b'Northern and Western Divisions'), (330, b'Southern Division'), (340, b'Sunrise Division'), (342, b'Western Regional'), (344, b'Eastern Regional'), (350, b'NE/NW/SE/SW Divisions')], help_text=b'\n            Detail if division/combo convention.', null=True),
        ),
    ]
