# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_auto_20160716_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='person',
            name='organization',
        ),
        migrations.AlterField(
            model_name='performer',
            name='seed',
            field=models.IntegerField(blank=True, help_text=b'\n            The incoming rank based on prelim score.', null=True),
        ),
    ]
