# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_auto_20160206_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='api.Organization'),
        ),
    ]
