# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_group_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='bhs_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chapter',
            name='bhs_chapter_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chapter',
            name='bhs_chapter_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chapter',
            name='bhs_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chapter',
            name='bhs_contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chapter',
            name='bhs_district',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chapter',
            name='bhs_group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='bhs_group_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chapter',
            name='bhs_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chapter',
            name='bhs_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chapter',
            name='bhs_state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chapter',
            name='bhs_venue',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chapter',
            name='bhs_website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chapter',
            name='bhs_zip',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
