# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_auto_20160717_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_groups', to='api.Organization'),
        ),
    ]
