# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_auto_20160314_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='venue',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(editable=False, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='state',
            field=models.CharField(max_length=255),
        ),
    ]
