# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-15 14:08
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_auto_20160314_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Eligible'), (20, b'Ineligible'), (30, b'Did Not Qualify'), (50, b'Qualified'), (90, b'Final')], default=0),
        ),
    ]
