# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_auto_20160717_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performer',
            old_name='representing',
            new_name='district',
        ),
    ]
