# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_auto_20160315_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
