# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_auto_20160718_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='kind',
            field=models.IntegerField(choices=[(10, b'Chair'), (20, b'Past Chair'), (30, b'Specialist'), (35, b'DRCJ'), (40, b'Certified'), (50, b'Candidate'), (60, b'Retired'), (70, b'Lapsed')]),
        ),
    ]
