# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_award_is_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='year',
        ),
    ]
