# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 15:23
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_remove_session_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Scheduled'), (15, b'Upcoming'), (20, b'Started'), (30, b'Finished'), (40, b'Recent'), (50, b'Final')], default=0),
        ),
    ]
