# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 16:46
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_auto_20160718_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='organization',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications', to='api.Organization'),
        ),
    ]
