# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_certification_organization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certification',
            unique_together=set([('category', 'person', 'kind')]),
        ),
    ]
