# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_auto_20160213_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='code',
            field=models.CharField(blank=True, help_text=b'\n            The single-letter code, corresponding to chapter codes.', max_length=1),
        ),
    ]
