# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 15:49
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_auto_20160318_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Active'), (20, b'Inactive'), (30, b'Affiliate'), (50, b'Duplicate')], default=0),
        ),
    ]
