# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_auto_20160318_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='cycle',
            field=models.IntegerField(editable=False),
        ),
    ]
