# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 16:58
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_auto_20160718_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (1, b'Active'), (2, b'Inactive')], default=0),
        ),
    ]
