# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 21:53
from __future__ import unicode_literals

import apps.api.validators
import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_organization_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(error_messages={b'unique': b'The name must be unique.  Add middle initials, suffixes, years, or other identifiers to make the name unique.'}, help_text=b'\n            The name of the resource.', max_length=200, validators=[apps.api.validators.validate_trimmed]),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=255, populate_from=b'name', unique_with=(b'kind',)),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set([('name', 'kind')]),
        ),
    ]
