# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_auto_20160214_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bhs_member_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
