# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_auto_20160318_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='is_qualifier',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.Group'),
        ),
    ]
