# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_auto_20160214_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
