# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_auto_20160214_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='code',
            field=models.CharField(blank=True, help_text=b'\n            The chapter code.', max_length=200, null=True),
        ),
    ]
