# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_auto_20160718_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='api.Catalog'),
        ),
    ]
