# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 19:23
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_auto_20160321_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Qualified'), (20, b'Accepted'), (30, b'Declined'), (40, b'Dropped'), (50, b'Official'), (55, b'Disqualified'), (60, b'Finished'), (90, b'Final')], default=0),
        ),
    ]
