# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 17:42
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_auto_20160213_0845'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organization',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='group',
            old_name='district',
            new_name='organization',
        ),
    ]
