# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_submission_catalog'),
    ]

    operations = [
        migrations.operations.RenameModel("Judge", "Assignment")
    ]
