# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_auto_20160215_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='bhs_group_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
