# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_auto_20160718_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='judge',
            new_name='assignment',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='certification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='api.Certification'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='organization',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='api.Organization'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.Session'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('song', 'assignment')]),
        ),
    ]
