# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_auto_20160331_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='slot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together=set([]),
        ),
    ]
