# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_auto_20160215_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ('round', 'slot')},
        ),
        migrations.AddField(
            model_name='performance',
            name='slot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together=set([('round', 'slot')]),
        ),
    ]
