# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 14:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_session_cutoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='datetm',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, help_text=b'\n            The active dates of the resource.', null=True),
        ),
    ]
