# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 04:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_auto_20160215_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_novice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='is_senior',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='is_youth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(error_messages={b'unique': b'The name must be unique.  Add middle initials, suffixes, years, or other identifiers to make the name unique.'}, help_text=b'\n            The name of the resource.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='place',
            field=models.IntegerField(blank=True, editable=False, help_text=b'\n            The final ranking relative to this award.', null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(error_messages={b'unique': b'The name must be unique.  Add middle initials, suffixes, years, or other identifiers to make the name unique.'}, help_text=b'\n            The name of the resource.', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='level',
            field=models.IntegerField(blank=True, choices=[(0, b'International'), (1, b'District/Affiliates'), (2, b'Division')], null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text=b'\n            The name of the resource.', max_length=200),
        ),
        migrations.AlterField(
            model_name='performer',
            name='place',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(error_messages={b'unique': b'The name must be unique.  Add middle initials, suffixes, years, or other identifiers to make the name unique.'}, help_text=b'\n            The name of the resource.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='points',
            field=models.IntegerField(blank=True, help_text=b'\n            The number of points (0-100)', null=True, validators=[django.core.validators.MaxValueValidator(100, message=b'Points must be between 0 - 100'), django.core.validators.MinValueValidator(0, message=b'Points must be between 0 - 100')]),
        ),
    ]
