# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_auto_20160718_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='certification',
            new_name='judge',
        ),
        migrations.AlterField(
            model_name='judge',
            name='organization',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judges', to='api.Organization'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges', to='api.Person'),
        ),
    ]
