# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 03:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_auto_20160218_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='size',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True),
        ),
    ]
