# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_award_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='is_improved',
            field=models.BooleanField(default=False),
        ),
    ]
