# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_auto_20160720_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='performer_score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performer', to='api.PerformerScore'),
        ),
    ]
