# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 17:25
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_auto_20160403_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (4, b'Open'), (8, b'Closed'), (10, b'Ready'), (20, b'Started'), (30, b'Finished'), (40, b'Drafted'), (45, b'Published'), (50, b'Final')], default=0),
        ),
    ]
