# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_award_is_improved'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='size_name',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
