# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_auto_20160720_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performer',
            old_name='performer_score',
            new_name='performerscore',
        ),
    ]
