# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 18:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_auto_20160404_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='penalty',
            field=models.IntegerField(blank=True, help_text=b'\n            The penalty (0-100)', null=True, validators=[django.core.validators.MaxValueValidator(100, message=b'Points must be between 0 - 100'), django.core.validators.MinValueValidator(0, message=b'Points must be between 0 - 100')]),
        ),
        migrations.AddField(
            model_name='score',
            name='violation',
            field=django_fsm.FSMIntegerField(blank=True, choices=[(10, b'General')], null=True),
        ),
    ]
