# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_award_size_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='award',
            unique_together=set([]),
        ),
    ]
