# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_auto_20160720_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancescore',
            name='mus_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancescore',
            name='mus_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancescore',
            name='prs_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancescore',
            name='prs_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancescore',
            name='rank',
            field=models.IntegerField(blank=True, help_text=b'\n            The final ranking relative to this round.', null=True),
        ),
        migrations.AlterField(
            model_name='performancescore',
            name='sng_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancescore',
            name='sng_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancescore',
            name='total_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancescore',
            name='total_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
