# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 20:42
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_auto_20160404_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Started'), (20, b'Finished'), (50, b'Confirmed'), (90, b'Final')], default=0),
        ),
    ]
