# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0135_convention_datet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convention',
            name='date',
        ),
    ]
