# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0136_auto_20160721_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(0, b'New'), (1, b'Active'), (2, b'Inactive'), (3, b'Retired'), (5, b'Deceased'), (6, b'(Six)'), (9, b'(Nine)')], default=0),
        ),
    ]
