# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0139_auto_20160723_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performer',
            name='csa_pdf',
        ),
        migrations.RemoveField(
            model_name='performer',
            name='notification',
        ),
    ]
