# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 21:46
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0140_auto_20160408_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (10, b'Started'), (20, b'Finished'), (30, b'Completed'), (50, b'Confirmed'), (90, b'Final')], default=0),
        ),
    ]
