# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0141_auto_20160408_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='baritone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performers_baritone', to='api.Role'),
        ),
        migrations.AddField(
            model_name='performer',
            name='bass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performers_bass', to='api.Role'),
        ),
        migrations.AddField(
            model_name='performer',
            name='codirector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performers_codirector', to='api.Role'),
        ),
        migrations.AddField(
            model_name='performer',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performers_director', to='api.Role'),
        ),
        migrations.AddField(
            model_name='performer',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performers_lead', to='api.Role'),
        ),
        migrations.AddField(
            model_name='performer',
            name='tenor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performers_tenor', to='api.Role'),
        ),
    ]
