# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_contestantscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='performance',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (5, b'Validated'), (10, b'Started'), (20, b'Finished'), (30, b'Entered'), (40, b'Flagged'), (60, b'Cleared'), (90, b'Published')], default=0),
        ),
    ]
