# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_auto_20160410_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.Group'),
        ),
    ]
