# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0143_auto_20160410_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.Performer'),
        ),
    ]
