# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-04 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0143_auto_20160725_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
