# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_user_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
    ]
