# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import mptt.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0145_auto_20160411_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=255, unique=True)),
                ('status', models.IntegerField(choices=[(0, b'New')], default=0)),
                ('kind', models.IntegerField(choices=[(10, b'Official'), (20, b'Practice'), (25, b'Guest'), (30, b'Composite')])),
                ('organization', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisstants', to='api.Organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assisstants', to='api.Person')),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, b'New'), (4, b'Opened'), (8, b'Closed'), (10, b'Validated'), (20, b'Started'), (30, b'Finished'), (40, b'Drafted'), (45, b'Published'), (50, b'Final')], default=0),
        ),
        migrations.AddField(
            model_name='assistant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assisstants', to='api.Session'),
        ),
        migrations.AlterUniqueTogether(
            name='assistant',
            unique_together=set([('session', 'person')]),
        ),
    ]
