# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0146_user_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bhs_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
