# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0146_auto_20160411_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='organization',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistants', to='api.Organization'),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='api.Person'),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='api.Session'),
        ),
    ]
