# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0147_auto_20160906_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='nomen',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='nomen',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='nomen',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nomen',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sub',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
