# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0147_auto_20160411_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='convention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.Convention'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.Organization'),
        ),
    ]
