# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0148_auto_20160411_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='cursor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
