# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0149_session_cursor'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='airport',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
