# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0150_venue_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='chap_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
