# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0152_assistant_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='bhs_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
