# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0154_role_bhs_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set([]),
        ),
    ]
