# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0156_person_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text=b'\n            The name of the resource.', max_length=200),
        ),
    ]
