# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0157_auto_20160415_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='bhs_marketplace',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
