# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0158_chart_bhs_marketplace'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chart',
            unique_together=set([('title', 'bhs_marketplace')]),
        ),
    ]
