# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0159_auto_20160416_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
