# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 16:49
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0161_auto_20160418_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='risers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
