# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0162_convention_risers'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='kind',
            field=models.IntegerField(blank=True, choices=[(10, b'International'), (20, b'District'), (30, b'Division'), (40, b'District and Division')], null=True),
        ),
    ]
