# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0164_auto_20160419_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(help_text=b'\n            The name of the resource.', max_length=200),
        ),
    ]
