# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0165_auto_20160420_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='kind',
            field=models.IntegerField(choices=[(1, b'Quartet'), (2, b'Chorus')], help_text=b'\n            The kind of group; choices are Quartet or Chorus.'),
        ),
    ]
