# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0166_auto_20160421_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='performer',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
