# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0167_auto_20160421_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='baritone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performers_baritone', to='api.Role'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='bass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performers_bass', to='api.Role'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='codirector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performers_codirector', to='api.Role'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performers_director', to='api.Role'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performers_lead', to='api.Role'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='tenor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performers_tenor', to='api.Role'),
        ),
    ]
