# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0168_auto_20160421_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='baritone_p',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performers_baritone', to='api.Person'),
        ),
        migrations.AddField(
            model_name='performer',
            name='bass_p',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performers_bass', to='api.Person'),
        ),
        migrations.AddField(
            model_name='performer',
            name='codirector_p',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performers_codirector', to='api.Person'),
        ),
        migrations.AddField(
            model_name='performer',
            name='director_p',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performers_director', to='api.Person'),
        ),
        migrations.AddField(
            model_name='performer',
            name='lead_p',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performers_lead', to='api.Person'),
        ),
        migrations.AddField(
            model_name='performer',
            name='tenor_p',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performers_tenor', to='api.Person'),
        ),
    ]
