# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0169_auto_20160422_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performer',
            old_name='organization',
            new_name='representing',
        ),
    ]
