# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0170_auto_20160422_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='mt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mic_tester', to='api.Group'),
        ),
    ]
