# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0171_round_mt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performer',
            name='baritone_p',
        ),
        migrations.RemoveField(
            model_name='performer',
            name='bass_p',
        ),
        migrations.RemoveField(
            model_name='performer',
            name='codirector_p',
        ),
        migrations.RemoveField(
            model_name='performer',
            name='director_p',
        ),
        migrations.RemoveField(
            model_name='performer',
            name='lead_p',
        ),
        migrations.RemoveField(
            model_name='performer',
            name='tenor_p',
        ),
    ]
