# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0172_auto_20160423_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='api.Submission'),
        ),
    ]
