# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0173_song_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='aca',
        ),
        migrations.AddField(
            model_name='judge',
            name='certification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panels', to='api.Certification'),
        ),
    ]
