# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0175_auto_20160425_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='risers',
            field=models.IntegerField(blank=True, help_text=b'\n            The number of risers select.', null=True),
        ),
        migrations.AlterField(
            model_name='performer',
            name='men',
            field=models.IntegerField(blank=True, help_text=b'\n            The number of men on stage.', null=True),
        ),
    ]
