# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0177_performer_is_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='name',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
