# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0178_auto_20160426_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='api.Person'),
        ),
    ]
