# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0180_auto_20160427_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='level',
            field=models.IntegerField(choices=[(0, b'International'), (1, b'District'), (2, b'Division'), (3, b'Chapter')], editable=False),
        ),
    ]
