# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0182_auto_20160428_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='aca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_aca', to='api.Certification'),
        ),
        migrations.AddField(
            model_name='session',
            name='ca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_ca', to='api.Certification'),
        ),
    ]
