# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0186_auto_20160502_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_qualifier',
            field=models.BooleanField(default=False),
        ),
    ]
