# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0187_participant_is_qualifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
