# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0188_auto_20160503_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='bhs_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
