# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0190_auto_20160504_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='bhs_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convention',
            name='division',
            field=models.IntegerField(blank=True, choices=[(200, b'EVG Division I'), (210, b'EVG Division II'), (220, b'EVG Division III'), (230, b'EVG Division IV'), (240, b'EVG Division V'), (250, b'FWD Arizona Division'), (260, b'FWD NE/NW Divisions'), (270, b'FWD SE/SW Divisions'), (280, b'LOL Division One/Packerland Divisions'), (290, b'LOL Northern Plains Division'), (300, b'LOL 10,000 Lakes and Southwest Divisions'), (322, b'MAD Northern Division'), (324, b'MAD Central Division'), (330, b'MAD Southern Division'), (340, b'NED Sunrise Division'), (342, b'NED Western Regional'), (344, b'NED Eastern Regional'), (350, b'SWD NE/NW/SE/SW Divisions')], help_text=b'\n            Detail if division/regional convention.', null=True),
        ),
    ]
