# Generated by Django 2.1.8 on 2019-06-08 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmanager', '0002_auto_20190607_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appearances', to='smanager.Entry'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appearances', to='bhs.Group'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='rmanager.Round'),
        ),
        migrations.AlterField(
            model_name='contender',
            name='appearance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenders', to='rmanager.Appearance'),
        ),
        migrations.AlterField(
            model_name='contender',
            name='outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenders', to='rmanager.Outcome'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='cmanager.Award'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='rmanager.Round'),
        ),
        migrations.AlterField(
            model_name='panelist',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panelists', to='bhs.Person'),
        ),
        migrations.AlterField(
            model_name='panelist',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panelists', to='rmanager.Round'),
        ),
        migrations.AlterField(
            model_name='round',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='smanager.Session'),
        ),
        migrations.AlterField(
            model_name='score',
            name='panelist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='rmanager.Panelist'),
        ),
        migrations.AlterField(
            model_name='score',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='rmanager.Song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='appearance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='rmanager.Appearance'),
        ),
        migrations.AlterField(
            model_name='song',
            name='chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='bhs.Chart'),
        ),
    ]
