# Generated by Django 2.1.8 on 2019-05-07 23:37

from django.db import migrations

def forward(apps, schema_editor):
    OldVenue = apps.get_model('api.venue')
    NewVenue = apps.get_model('stage.venue')
    OldGrid = apps.get_model('api.grid')
    NewGrid = apps.get_model('stage.grid')

    venues = OldVenue.objects.values()
    for venue in venues:
        NewVenue.objects.create(**venue)

    grids = OldGrid.objects.values()
    for grid in grids:
        NewGrid.objects.create(**grid)

class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
