# Generated by Django 2.2.3 on 2019-07-08 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0002_auto_20190707_1651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grid',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
