# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170115_1456'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='score',
            name='assignment',
        ),
    ]
