# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170120_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='baritone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='performer',
            name='bass',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='performer',
            name='codirector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='performer',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='performer',
            name='lead',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='performer',
            name='tenor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
