# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170127_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='legacy_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='legacy_parent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
