# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 00:28
from __future__ import unicode_literals

from django.db import migrations

from app.models import (
    Assignment,
    Award,
    Chapter,
    Convention,
    Entity,
    Host,
    Judge,
)


def copy_fks(apps, schema_editor):
    items = Assignment.objects.exclude(organization=None)
    for i in items:
        i.entity = Entity.objects.get(legacy_id=i.organization.id.hex)
        i.save()
    items = Award.objects.exclude(organization=None)
    for i in items:
        i.entity = Entity.objects.get(legacy_id=i.organization.id.hex)
        i.save()
    items = Chapter.objects.exclude(organization=None)
    for i in items:
        i.entity = Entity.objects.get(legacy_id=i.organization.id.hex)
        i.save()
    items = Convention.objects.exclude(organization=None)
    for i in items:
        i.entity = Entity.objects.get(legacy_id=i.organization.id.hex)
        i.save()
    items = Host.objects.exclude(organization=None)
    for i in items:
        i.entity = Entity.objects.get(legacy_id=i.organization.id.hex)
        i.save()
    items = Judge.objects.exclude(organization=None)
    for i in items:
        i.entity = Entity.objects.get(legacy_id=i.organization.id.hex)
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170127_1626'),
    ]

    operations = [
        migrations.RunPython(copy_fks),
    ]
