# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 13:13
from __future__ import unicode_literals

from django.db import migrations

from app.models import (
    Entity,
    Performer,
)


def update_performers(apps, schema_editor):
    ps = Performer.objects.exclude(group=None)
    for p in ps:
        p.entity = Entity.objects.get(
            legacy_id=p.group.id.hex
        )
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_performer_entity'),
    ]

    operations = [
        migrations.RunPython(update_performers),
    ]
