# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20170128_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='part',
            field=models.IntegerField(blank=True, choices=[(1, b'Tenor'), (2, b'Lead'), (3, b'Baritone'), (4, b'Bass'), (5, b'Director')], null=True),
        ),
    ]
