# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_membership_part'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([]),
        ),
    ]
