# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 13:49
from __future__ import unicode_literals

from django.db import migrations

from app.models import (
    Entity,
    Membership,
    Role,
)


def update_parts(apps, schema_editor):
    rs = Role.objects.all()
    i = 1
    for r in rs:
        person = r.person
        entity = Entity.objects.get(legacy_id=r.group.id.hex)
        try:
            membership = Membership.objects.get(
                person=person,
                entity=entity,
            )
        except Membership.DoesNotExist:
            membership = Membership(
                person=person,
                entity=entity,
                status=r.status,
                part=r.part,
                start_date=r.start_date,
                end_date=r.end_date,
            )
        membership.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20170128_0549'),
    ]

    operations = [
        migrations.RunPython(update_parts)
    ]
