# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20170128_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='nomen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
