# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 15:00
from __future__ import unicode_literals

from django.db import migrations
from app.models import (
    Office
)

fixture = [
    {'name': 'Certified Admin', 'short_name': '', 'status': 10, 'kind': 30,},
    {'name': 'Certified Music', 'short_name': '', 'status': 10, 'kind': 30,},
    {'name': 'Certified Presentation', 'short_name': '', 'status': 10, 'kind': 30,},
    {'name': 'Certified Singing', 'short_name': '', 'status': 10, 'kind': 30,},
    {'name': 'Candidate Admin', 'short_name': '', 'status': 10, 'kind': 30,},
    {'name': 'Candidate Music', 'short_name': '', 'status': 10, 'kind': 30,},
    {'name': 'Candidate Presentation', 'short_name': '', 'status': 10, 'kind': 30,},
    {'name': 'Candidate Singing', 'short_name': '', 'status': 10, 'kind': 30,},
    {'name': 'Specialist Admin', 'short_name': '', 'status': 10, 'kind': 30,},
    {'name': 'Specialist Music', 'short_name': '', 'status': 10, 'kind': 30,},
    {'name': 'Specialist Presentation', 'short_name': '', 'status': 10, 'kind': 30,},
    {'name': 'Specialist Singing', 'short_name': '', 'status': 10, 'kind': 30,},
]


def add_cj(apps, schema_editor):
    for item in fixture:
        Office.objects.create(**item)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20170128_0705'),
    ]

    operations = [
        migrations.RunPython(add_cj),
    ]
