# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 15:08
from __future__ import unicode_literals

from django.db import migrations

from app.models import (
    Entity,
    Person,
    Membership,
)


def add_bhs(apps, schema_editor):
    persons = Person.objects.all()
    entity = Entity.objects.get(kind=1)
    for person in persons:
        Membership.objects.create(
            entity=entity,
            person=person
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20170128_0705'),
    ]

    operations = [
        migrations.RunPython(add_bhs),
    ]
