# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20170128_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(-10, b'Archived'), (0, b'New'), (10, b'Scheduled'), (20, b'Confirmed'), (25, b'Validated'), (30, b'Final')], default=0),
        ),
    ]
