# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 18:05
from __future__ import unicode_literals

from django.db import migrations

from app.models import (
    Award,
    Person,
    Venue,
)

def convert_status(apps, schema_editor):
    items = Award.objects.filter(status=20)
    for i in items:
        i.status = -10
        i.save()

    items = Person.objects.filter(status=2)
    for i in items:
        i.status = -10
        i.save()

    items = Venue.objects.filter(status=20)
    for i in items:
        i.status = -10
        i.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20170128_1005'),
    ]

    operations = [
        migrations.RunPython(convert_status),
    ]
