# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 18:20
from __future__ import unicode_literals

from django.db import migrations

from app.models import (
    Membership,
    Office,
)

def convert_stragglers(apps, schema_editor):
    items = Membership.objects.filter(status=20)
    for i in items:
        i.status = -10
        i.save()

    items = Office.objects.filter(status=20)
    for i in items:
        i.status = -10
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20170128_1015'),
    ]

    operations = [
        migrations.RunPython(convert_stragglers),
    ]
