# Generated by Django 2.1.9 on 2019-06-24 22:49

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rmanager', '0001_initial'),
        ('bhs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanFlat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CleanPanelist',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('season', models.IntegerField(choices=[(1, 'Summer'), (2, 'Midwinter'), (3, 'Fall'), (4, 'Spring')])),
                ('district', models.CharField(max_length=255)),
                ('convention', models.CharField(max_length=255)),
                ('session', models.IntegerField(choices=[(32, 'Chorus'), (41, 'Quartet'), (42, 'Mixed'), (43, 'Senior'), (44, 'Youth'), (45, 'Unknown'), (46, 'VLQ')])),
                ('round', models.IntegerField(choices=[(1, 'Finals'), (2, 'Semi-Finals'), (3, 'Quarter-Finals')])),
                ('category', models.IntegerField(choices=[(30, 'Music'), (40, 'Performance'), (50, 'Singing')])),
                ('num', models.IntegerField()),
                ('legacy_person', models.CharField(max_length=255)),
                ('scores', django.contrib.postgres.fields.jsonb.JSONField()),
                ('panelist', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rmanager.Panelist')),
            ],
        ),
        migrations.CreateModel(
            name='CleanSong',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('season', models.IntegerField(choices=[(1, 'Summer'), (2, 'Midwinter'), (3, 'Fall'), (4, 'Spring')])),
                ('district', models.CharField(max_length=255)),
                ('convention', models.CharField(max_length=255)),
                ('session', models.IntegerField(choices=[(32, 'Chorus'), (41, 'Quartet'), (42, 'Mixed'), (43, 'Senior'), (44, 'Youth'), (45, 'Unknown'), (46, 'VLQ')])),
                ('round', models.IntegerField(choices=[(1, 'Finals'), (2, 'Semi-Finals'), (3, 'Quarter-Finals')])),
                ('appearance_num', models.IntegerField()),
                ('song_num', models.IntegerField()),
                ('legacy_group', models.CharField(max_length=255)),
                ('legacy_chart', models.CharField(max_length=255)),
                ('scores', django.contrib.postgres.fields.jsonb.JSONField()),
                ('appearance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rmanager.Appearance')),
                ('song', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rmanager.Song')),
            ],
        ),
        migrations.CreateModel(
            name='Complete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_id', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('season_kind', models.IntegerField(blank=True, choices=[(1, 'Summer'), (2, 'Midwinter'), (3, 'Fall'), (4, 'Spring')], null=True)),
                ('district_code', models.CharField(blank=True, max_length=255)),
                ('convention_name', models.CharField(blank=True, max_length=255)),
                ('session_kind', models.IntegerField(blank=True, choices=[(32, 'Chorus'), (41, 'Quartet'), (42, 'Mixed'), (43, 'Senior'), (44, 'Youth'), (45, 'Unknown'), (46, 'VLQ')], null=True)),
                ('round_kind', models.IntegerField(blank=True, choices=[(1, 'Finals'), (2, 'Semi-Finals'), (3, 'Quarter-Finals')], null=True)),
                ('category_kind', models.IntegerField(blank=True, choices=[(30, 'Music'), (40, 'Performance'), (50, 'Singing')], null=True)),
                ('points', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('panelist', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rmanager.Panelist')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completes', to='bhs.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('complete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='keller.Complete')),
                ('score', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rmanager.Score')),
            ],
        ),
        migrations.CreateModel(
            name='RawPanelist',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('season', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('convention', models.CharField(max_length=255)),
                ('session', models.CharField(max_length=255)),
                ('round', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('judge', models.CharField(max_length=255)),
                ('scores', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='RawSong',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('district', models.CharField(max_length=255)),
                ('event', models.CharField(max_length=255)),
                ('session', models.CharField(max_length=255)),
                ('group_name', models.CharField(max_length=255)),
                ('appearance_num', models.IntegerField()),
                ('song_num', models.IntegerField()),
                ('song_title', models.CharField(max_length=255)),
                ('totals', models.IntegerField()),
                ('scores', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mark', models.BooleanField(default=False)),
                ('row_id', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('season_kind', models.IntegerField(blank=True, choices=[(1, 'Summer'), (2, 'Midwinter'), (3, 'Fall'), (4, 'Spring')], null=True)),
                ('district_code', models.CharField(blank=True, max_length=255)),
                ('convention_name', models.CharField(blank=True, max_length=255)),
                ('session_kind', models.IntegerField(blank=True, choices=[(32, 'Chorus'), (41, 'Quartet'), (42, 'Mixed'), (43, 'Senior'), (44, 'Youth'), (45, 'Unknown'), (46, 'VLQ')], null=True)),
                ('round_kind', models.IntegerField(blank=True, choices=[(1, 'Finals'), (2, 'Semi-Finals'), (3, 'Quarter-Finals')], null=True)),
                ('group_name', models.CharField(blank=True, max_length=255)),
                ('appearance_num', models.IntegerField(blank=True, null=True)),
                ('song_num', models.IntegerField(blank=True, null=True)),
                ('song_title', models.CharField(blank=True, max_length=255)),
                ('totals', models.IntegerField(blank=True, null=True)),
                ('points', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('song', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rmanager.Song')),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='keller.Selection'),
        ),
        migrations.AddField(
            model_name='cleanflat',
            name='cleanpanelist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanflats', to='keller.CleanPanelist'),
        ),
        migrations.AddField(
            model_name='cleanflat',
            name='cleansong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanflats', to='keller.CleanSong'),
        ),
        migrations.AddField(
            model_name='cleanflat',
            name='score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rmanager.Score'),
        ),
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together={('complete', 'selection', 'score')},
        ),
        migrations.AlterUniqueTogether(
            name='cleanflat',
            unique_together={('cleanpanelist', 'cleansong')},
        ),
    ]
