# Generated by Django 2.2.4 on 2019-08-17 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keller', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cleanflat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cleanflat',
            name='cleanpanelist',
        ),
        migrations.RemoveField(
            model_name='cleanflat',
            name='cleansong',
        ),
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='flat',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='selection',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='RawPanelist',
        ),
        migrations.DeleteModel(
            name='RawSong',
        ),
        migrations.DeleteModel(
            name='CleanFlat',
        ),
        migrations.DeleteModel(
            name='CleanPanelist',
        ),
        migrations.DeleteModel(
            name='CleanSong',
        ),
        migrations.DeleteModel(
            name='Complete',
        ),
        migrations.DeleteModel(
            name='Flat',
        ),
        migrations.DeleteModel(
            name='Selection',
        ),
    ]
