# Generated by Django 2.1.8 on 2019-05-23 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0002_auto_20190515_0709'),
        ('keller', '0003_auto_20190523_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completes', to='bhs.Person'),
        ),
    ]
