# Generated by Django 2.1.8 on 2019-05-24 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keller', '0004_complete_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='row',
            new_name='row_id',
        ),
    ]
