# Generated by Django 2.1.8 on 2019-05-26 14:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keller', '0006_auto_20190524_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawPanelist',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('season', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('convention', models.CharField(max_length=255)),
                ('session', models.CharField(max_length=255)),
                ('round', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('judge', models.CharField(max_length=255)),
                ('points', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='complete',
            name='mark',
        ),
    ]
