# Generated by Django 2.1.8 on 2019-05-27 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_panelist_legacy_row_id'),
        ('keller', '0009_rawsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawpanelist',
            name='panelist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Panelist'),
        ),
    ]
