# Generated by Django 2.1.8 on 2019-05-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keller', '0011_rawpanelist_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawpanelist',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
