# Generated by Django 2.1.8 on 2019-05-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keller', '0014_cleansong'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleanpanelist',
            old_name='judge',
            new_name='legacy_person',
        ),
        migrations.RenameField(
            model_name='cleansong',
            old_name='group_name',
            new_name='legacy_chart',
        ),
        migrations.RenameField(
            model_name='cleansong',
            old_name='song_title',
            new_name='legacy_group',
        ),
        migrations.RemoveField(
            model_name='rawpanelist',
            name='panelist',
        ),
    ]
