# Generated by Django 2.1.8 on 2019-05-28 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190528_1529'),
        ('keller', '0016_remove_cleansong_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleansong',
            name='appearance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Appearance'),
        ),
    ]
