# Generated by Django 2.1.8 on 2019-05-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complete',
            old_name='panelist_name',
            new_name='panelist_raw',
        ),
        migrations.RenameField(
            model_name='complete',
            old_name='points',
            new_name='points_raw',
        ),
        migrations.RenameField(
            model_name='complete',
            old_name='row',
            new_name='row_id',
        ),
    ]
