# Generated by Django 2.1.8 on 2019-05-23 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keller', '0002_auto_20190523_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complete',
            old_name='points_raw',
            new_name='points',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='category_raw',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='convention_raw',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='district_raw',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='num_appearances',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='num_panelists',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='num_rounds',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='num_sessions',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='panelist_num',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='panelist_raw',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='round_raw',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='season_raw',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='session_raw',
        ),
        migrations.RemoveField(
            model_name='complete',
            name='slips',
        ),
    ]
