# Generated by Django 2.1.8 on 2019-05-24 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keller', '0005_auto_20190524_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='district_raw',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='event_raw',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='num_appearances',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='num_panelists',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='num_rounds',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='num_sessions',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='season_raw',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='session_raw',
        ),
    ]
