# Generated by Django 2.1.8 on 2019-05-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keller', '0010_rawpanelist_panelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawpanelist',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
