# Generated by Django 2.1.8 on 2019-05-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keller', '0015_auto_20190528_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleansong',
            name='totals',
        ),
    ]
