# Generated by Django 2.1.8 on 2019-05-28 23:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_score_legacy_panelist'),
        ('keller', '0017_cleansong_appearance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanFlat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('cleanpanelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanflats', to='keller.CleanPanelist')),
                ('cleansong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanflats', to='keller.CleanSong')),
                ('score', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Score')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cleanflat',
            unique_together={('cleanpanelist', 'cleansong')},
        ),
    ]
