# Generated by Django 2.1.8 on 2019-06-08 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmanager', '0002_auto_20190607_2253'),
        ('keller', '0018_auto_20190528_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanflat',
            name='score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rmanager.Score'),
        ),
        migrations.AlterField(
            model_name='cleanpanelist',
            name='panelist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rmanager.Panelist'),
        ),
        migrations.AlterField(
            model_name='cleansong',
            name='appearance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rmanager.Appearance'),
        ),
        migrations.AlterField(
            model_name='cleansong',
            name='song',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rmanager.Song'),
        ),
        migrations.AlterField(
            model_name='complete',
            name='panelist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rmanager.Panelist'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rmanager.Score'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='song',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rmanager.Song'),
        ),
    ]
