# Generated by Django 2.2.27 on 2023-08-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20230819_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(default='', help_text='\n            e.g. Far Western District', max_length=255, verbose_name='District Name'),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(default='', help_text='\n            e.g. FWD Northwest', max_length=255, verbose_name='Division Name'),
        ),
    ]
