# Generated by Django 2.2.27 on 2023-08-21 12:13

import apps.organizations.fields
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20230820_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.FileField(blank=True, default='', help_text='Logo should be 108px x 108px in JPG format.', storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=apps.organizations.fields.UploadPath('organization_logos')),
        ),
    ]
